twilight-rs/twilight

- gateway/src/cluster/impl.rs
Shard_to & shard_from can be removed by iterating over the shards in the cluster.
> refactor(gateway/cluster): remove shard_from & shard_to fields

- http/src/request/validate.rs
Update HTTP validation to take into account the new Select Menu Option limits. Label and descriptions lengths have been increased from 25 to 100.
API docs: <https://github.com/discord/discord-api-docs/commit/02870dd7ccc9bed981f540e693ee7991c1f418c4>
> chore(http/validate): new select option limits

- http/src/response/future.rs
These errors should be the other way around
> fix(http): Correct error type for in_flight error

- cache/in-memory/src/event/guild.rs
- cache/in-memory/src/event/member.rs
- cache/in-memory/src/event/message.rs
- cache/in-memory/src/event/presence.rs
- cache/in-memory/src/event/reaction.rs
- cache/in-memory/src/lib.rs
- cache/in-memory/src/model/emoji.rs
- cache/in-memory/src/model/guild.rs
- cache/in-memory/src/model/member.rs
- cache/in-memory/src/model/message.rs
- cache/in-memory/src/model/presence.rs
- cache/in-memory/src/model/voice_state.rs
Instead of exposing the fields of models directly, expose them behind getters. This will allow us to add new fields without causing a breaking change.
> Cache model field getters

- gateway/src/shard/impl.rs
- gateway/src/shard/processor/impl.rs
- http/src/response/mod.rs
Discord recommends explicitly stating the encoding.
> chore(gateway, http): small code nits

- http/src/error.rs
This makes an unknown body much easier to read in the errors if it's not compressed. For compressed bodies the current behavior is kept
> Log response body parsing error body as text if UTF-8

- http/src/response/mod.rs
Add a `model` alias for the `Response::models` method in `Response<ListBody<T>>` and `Response<MemberListBody>` implementations.
This clears up some confusion and allows users to have a form of consistency if they choose to have it.
> Add HTTP response `model` alias for `models`

- http/src/api_error.rs
Add HTTP API error code 30040, described as "Maximum number of prune requests has been reached. Try again later".
API documentation: https://github.com/discord/discord-api-docs/pull/3655
> HTTP API error code 30040 "max prune requests reached"

- model/src/application/command/option.rs
If this set is set to `true` Discord will respond with an error (as reported in #1018).
Discord has now [documented](https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups) this too:
>Using subcommands or subcommand groups will make your base command unusable. You can't send the base `/permissions` command as a valid command if you also have `/permissions add | remove` as subcommands or subcommand groups.
I don't know if `is_required` returning `None` for `SubCommand | SubCommandGroup` is better than returning `false`
Closes #1018
> fix(model/application/command): remove `required` field from `OptionsCommandOptionData`

- http/README.md
- http/src/lib.rs
Update the documentation to state that the `tracing` dependency and feature are now optional.
This was changed by #910.
Closes #1124.
> Document that HTTP's `tracing` dependency is now optional

- http/src/response/status_code.rs
Add support for comparing `StatusCode`s with `u16`s, such as simply doing `status_code == 200`. This is equivalent to calling `status_code.raw() == 200`.
Closes #1114.
> Add comparing `StatusCode` with u16s

- gateway/src/shard/processor/impl.rs
Shards resume themselves many times a day, this is intended and is not very interesting info for the user. The frequency is also a bit too high such that it can dominate logs.
Attached screenshot is ~48h from a simple bot I run, note that this is running just one shard.
> chore(gateway): shard resumption message info -> debug

- cache/in-memory/src/lib.rs
Add methods for retrieving integrations by their guild and integration ID - exposed via the `InMemoryCache::integration` method - and for retrieving a list of a guild's integrations via the `InMemoryCache::guild_integrations` method.
Closes #1089.
> Add cache integration retrieval methods

- gateway/src/cluster/impl.rs
- gateway/src/cluster/scheme.rs
- model/src/channel/message/mod.rs
Fix two missed relative links by replacing them with intradoc links.
> Fix two missed relative links

- http/src/request/application/set_command_permissions.rs
Fix the serialized body of the `SetCommandPermissions` request builder. The request builder would serialize a command's permission as a single object, but Discord wants it in an array. Additionally, the request should support multiple permissions while we were only supporting one permission per command.
The functionality has been able to be fixed without causing a breaking change.
> Fix HTTP Set Command Permissions serialized body

- model/src/application/command/option.rs
This fixes that the deserializer for command options would erroneously
fail instead of setting missing options to default.
> Model: Do not error if options is missing

- util/Cargo.toml
- util/src/snowflake.rs
Also added a comment on why converting to a `Duration` is necessary
> docs(util/snowflake): use time 0.3 in  timestamp example

- .github/workflows/doc.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
I noticed that the cache used for the CI was inefficient : all dependencies are recompiled each time, with make the CI very long to run. This PR replaces the existing cache with the [`Swatinem/rust-cache`](https://github.com/Swatinem/rust-cache/)  action, that correctly cache dependencies. This cache is used in [other big projects](https://github.com/rust-analyzer/rust-analyzer/blob/b73b321478d3b2a98d380eb79de717e01620c4e9/.github/workflows/ci.yaml#L53-L54) like `rust-anlayser`.
> Example CI run of my last PR. Although there is other previous commits on the branch and no dependency has been updated, all dependencies are being downloaded and compiled again.
>
> ![image](https://user-images.githubusercontent.com/22115890/132191689-66e2a2f7-5213-4ff0-a24a-366ded557e91.png)
> Improve CI cache

- gateway/src/cluster/builder.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/config.rs
- gateway/src/shard/processor/impl.rs
Support users setting the properties to send during identify via the new `ClusterBuilder::identify_properties` and `ShardBuilder::identify_properties` methods. When not set a default will be used.
Closes #1119.
> Support setting identify properties in gateway

- gateway/src/shard/processor/compression/mod.rs
Allow the `clippy::unnecessary_wraps` lint in the `compression` gateway module when compression is disabled.
> Allow `clippy::unnecessary_wraps` lint in gateway compression

- cache/in-memory/src/event/member.rs
- cache/in-memory/src/event/message.rs
- cache/in-memory/src/event/mod.rs
- cache/in-memory/src/event/voice_state.rs
- cache/in-memory/src/lib.rs
Separate the `users` cache field from being a tuple of the user and its guild relations to being in two separate fields, as is consistent with other resources.
> refactor(cache/in-memory): separate user relations

- gateway/src/cluster/impl.rs
- gateway/src/shard/command.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/mod.rs
- gateway/tests/test_shard_state_events.rs
- lavalink/examples/basic-lavalink-bot/src/main.rs
Add a sealed `Command` marker trait for use with `Cluster::command` and `Shard::command`. These methods take anything that implements `serde::Serialize` but by instead using a marker trait we can limit what typed commands can be sent. If users want to send arbitrary messages `Cluster::send` and `Shard::send` are alternatives.
Closes #978.
> Add gateway `Command` marker trait

- cache/in-memory/src/event/channel.rs
- cache/in-memory/src/event/emoji.rs
- cache/in-memory/src/event/guild.rs
- cache/in-memory/src/event/interaction.rs
- cache/in-memory/src/event/message.rs
- cache/in-memory/src/event/mod.rs
- cache/in-memory/src/event/reaction.rs
- cache/in-memory/src/event/role.rs
- cache/in-memory/src/event/stage_instance.rs
- cache/in-memory/src/event/voice_state.rs
- cache/in-memory/src/lib.rs
- cache/in-memory/src/permission.rs
- cache/in-memory/src/stats.rs
Instead of returning returning owned copies of resources from the cache return immutable references. This introduces some additional care that users need to take but removes cloning on public API methods sans `InMemoryCache::update`.
In order to facilitate this a new type named `Reference` exists. `Reference` wraps DashMap's reference type in order to not expose it. It has two methods: `key` and `value`. `key` returns an immutable reference to the key used to obtain the resource and `value` returns an immutable reference to the underlying value.
The internal type `GuildItem` has been renamed to `GuildResource` and has been exposed. `GuildResource` exists for resources that don't contain the ID of the guild themselves. It has two methods: `guild_id` and `resource`. `guild_id` returns a …
> Return references instead of clones of cache resources

- lavalink/src/client.rs
- model/src/gateway/payload/incoming/ready.rs
- standby/src/lib.rs
Change the `twilight_model::gateway::payload::incoming::Ready::shard` field from being an `Option<[u64; 2]>` to being just a `[u64; 2]`; this field is always present and does not need to be wrapped in an `Option`.
The field has, additionally, been documented.
> Make `Ready::shard` required

- model/src/application/command/mod.rs
I missed this when reviewing #1053, so this is technically part of it.
> fix(model): actually re-export `Number`

- model/src/application/command/mod.rs
- model/src/application/command/option.rs
- util/src/builder/command.rs
This PR adds the `channel_type` field for application commands (https://github.com/discord/discord-api-docs/pull/3825).
**BREAKING CHANGE :** A new type `ChannelCommandOptionData` is introduced.
> Add `channel_type` field in application commands

- http/src/client/mod.rs
- http/src/request/application/command/set_global_commands.rs
- http/src/request/application/command/set_guild_commands.rs
- model/README.md
- model/src/application/command/mod.rs
- model/src/lib.rs
- util/src/builder/command.rs
Links to the `CommandBuilder` where it may be useful.`api.twilight.rs`
links were used since the builder isn't released yet.
Additionally, moves the `CommandBuilder` example to module-level.
> chore: link to command builder where applicable

- http/src/request/audit_reason.rs
- http/src/request/user/update_current_user.rs
This adds the audit log reason trait to the modify current member endpoint.
closes #1183
> Add audit reason to update current member

- model/src/voice/voice_region.rs
This Pull Request is to fix a breaking change from Discord, that the `vip` field is now removed (the documentation has yet to reflect the change).
> remove `vip` field from `VoiceRegion`

- model/src/application/interaction/application_command/data/mod.rs
- model/src/application/interaction/mod.rs
The old implementation contained unnecessary code duplication and clones
~~depends on #1216~~
> refactor(model): improve `CommandDataOption` serde implementation

- http/src/request/application/command/mod.rs
- model/src/application/command/mod.rs
- model/src/application/command/option.rs
- model/src/id.rs
- util/src/builder/command.rs
Also adds a `CommandVersionId` identifier.
Closes #1172
> chore(model): Add `Command::version` field

- lavalink/Cargo.toml
- lavalink/src/lib.rs
Promotes `http` to a required dependency. Changes the feature tag on the `http` module definition so that it is correctly enabled with its feature.
Fixes #1222.
> fix(lavalink): reconfigure default features

- .github/workflows/test.yml
- README.md
- cache/in-memory/README.md
- cache/in-memory/src/lib.rs
- command-parser/README.md
- command-parser/src/lib.rs
- embed-builder/README.md
- embed-builder/src/lib.rs
- gateway/README.md
- gateway/src/lib.rs
- http/README.md
- http/src/lib.rs
- lavalink/README.md
- lavalink/src/lib.rs
- mention/README.md
- mention/src/lib.rs
- model/README.md
- model/src/lib.rs
- standby/README.md
- standby/src/lib.rs
- twilight/src/lib.rs
- util/README.md
- util/src/lib.rs
Code coverage action, right now just uploads coverage report to github with the upload-artifact action, and skips examples as well
> feat: tarpaulin coverage action

- examples/model-webhook-slash/Cargo.toml
- examples/model-webhook-slash/src/main.rs
Adds the contents of `twilight-rs/examples` to the new examples directory.
If you are having rust-analyzer false positives, it is because ed25519-dalek sets a configuration option that hides its entire contents from its public API while in test mode. Since rust-analyzer compiles in test mode, this causes the false positive. This will be fixed in the 1.1 release of that crate.
Add this line to VS Code settings, or equivalently configure your rust-analyzer settings:
```
"rust-analyzer.cargo.unsetTest": [
"ed25519-dalek"
],
```
> chore(examples): fold in webhook-slash

- model/src/application/interaction/application_command/data/mod.rs
- model/src/application/interaction/mod.rs
Because the json doubles sent by discord sometimes seems to be without
trailing decimals (eg `5.0` was sent as `5`) it would sometimes cause
the deserialzation to fail. This pr rewrites the deserialzation of
`CommandDataOption` to look at the type of the value when
deserialzation happens so it will convert `5` to a double iff the type
is a `Number`.
> fix(model): account for the `type` of `CommandDataOption` in deserialization

- http/src/request/mod.rs
- http/src/request/prelude.rs
#1257 accidentally caused a breaking change. This reverts it to the extent where it is no longer breaking.
> fix(http): readd and deprecate prelude

- util/src/builder/command.rs
These options are not meant to be sent to Discord so there's no need to customize them.
Also renames the `SubCommandGroupBuilder::options` method -> `subcommands` to better communicate that there's only one valid option.
> chore(util/builder): `CommandBuilder` remove unnecessary options

- .github/workflows/lint.yml
- model/Cargo.toml
Will catch if newer features are unintentionally used without a dependency bump. Note that `model`'s minimal versions bubble up to all its dependents.
Inspired by Tokio's CI.
> chore(gh-actions): check minver deps

- http-ratelimiting/src/request.rs
- http/src/routing/route.rs
This should fix a lot of issues when responding to lots of interactions, because currently they're being handled as the same bucket when they actually aren't.
I'm not 100% sure about the documentation for the Path variants, it feels kind of weird to describe the difference as "as a bot" and "as a webhook", but I think this should accurately reflect Discord's docs.
PR made against next because of the ratelimiting changes in next making porting from main to next a little hard.
Fixes #840
> fix(http-ratelimiting): Webhook token is major parameter

- cache/in-memory/src/event/member.rs
- cache/in-memory/src/model/member.rs
`PartialEq` should be implemented for the Owned variants.
Split out of #1278
> fix(cache): use normal partialeq impl

- model/src/channel/thread/member.rs
- model/src/channel/thread/mod.rs
- model/src/gateway/payload/incoming/thread_members_update.rs
- model/src/gateway/presence/mod.rs
- model/src/guild/member.rs
This injects the guild ID into the fields member and presence for
THREAD_MEMBERS_UPDATE.
Closes #1262
> Deserialize thread member by injecting the guild id

- http/src/request/application/interaction/create_followup_message.rs
This PR deprecates the avatar_url & username functions from the CreateFollowupMessage struct. Associated PR for removal: #1287
> deprecate: avatar_url & username from CreateFollowupMessage

- .github/workflows/lint.yml
The previous implementation invalidated its cache every day (nightly) and it used the pre-minver `Cargo.lock` file as a cache key.
> chore(ci): improve min-vers

- http/src/request/application/interaction/delete_followup_message.rs
- http/src/request/application/interaction/get_followup_message.rs
- http/src/request/application/interaction/update_followup_message.rs
This is breaking, however the previous commit has not been released.
Hotfix followup to #1286.
> fix(http)!: interaction followups have no `thread_id`

- http/Cargo.toml
- http/README.md
- http/src/client/builder.rs
- http/src/client/mod.rs
- http/src/lib.rs
This adds back [trust-dns](https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/) support to twilight-http. It used to be possible to use this via reqwest's trust-dns feature flag and was no longer possible after the switch to hyper.
trust-dns is desirable because it replaces the default [GaiResolver](https://docs.rs/hyper/latest/hyper/client/connect/dns/struct.GaiResolver.html) in hyper, which uses a blocking getaddrinfo call and runs that in a tokio threadpool. trust-dns instead provides a fully async DNS resolver on application level.
trust-dns also provides advanced features like DNS-over-HTTPS, DNS-over-TLS and DNSSEC, which can be enabled by adding e.g. this to Cargo.toml: `hyper-trust-dns = { version = "0.3", default-features = false, features = ["dns-over-rustls", …
> http: Support trust-dns

- http/src/client/builder.rs
Fixes an issue introduced in #1310: Now that the `HttpConnector` is being created manually, the HTTP scheme enforcement must be disabled.
> fix(http): Don't enforce HTTP scheme in connector

- http/src/request/application/interaction/create_followup_message.rs
- http/src/request/application/interaction/delete_followup_message.rs
- http/src/request/application/interaction/delete_original_response.rs
- http/src/request/application/interaction/get_followup_message.rs
- http/src/request/application/interaction/get_original_response.rs
- http/src/request/application/interaction/interaction_callback.rs
- http/src/request/application/interaction/update_followup_message.rs
- http/src/request/application/interaction/update_original_response.rs
Don't send the configured bot token authorization header for interaction requests. The interaction token is the authorization, and so sending the bot token is unnecessary and may count towards the bot's global ratelimits.
> Don't send auth header for HTTP interactions

- command-parser/src/parser.rs
- examples/lavalink-basic-bot/src/main.rs
- gateway-queue/src/day_limiter.rs
- gateway-queue/src/large_bot_queue.rs
- gateway-queue/src/lib.rs
- gateway/src/cluster/scheme.rs
- http/src/request/application/interaction/update_followup_message.rs
- http/src/request/channel/webhook/update_webhook_message.rs
- model/src/gateway/event/gateway.rs
Fix a variety of clippy lints across the command parser, gateway queue, gateway, http, and model crates, as well as the lavalink bot example.
These range from lints about unused bindings depending on feature set to new stdlib APIs to simplify operations.
> Fix a variety of clippy lints

- http/src/client/mod.rs
Conditionally remember whether the configured client token is invalid by only performing the check on requests that are using the client authorization token. This means that requests such as webhooks and interactions will be excluded, as they use their own authorization.
Closes #1299.
> Conditionally invalidate HTTP client token

- http/src/api_error.rs
Fix the ordering of the `ApiError::Ratelimited` variant, which had a lower priority compared to the `ApiError::Message` variant and was erroneously being deserialized into.
Closes #1302.
> Fix HTTP API error ratelimited variant ordering

- http/src/request/application/command/mod.rs
Renames the `kind` field to `type` when serializing a `CommandBorrowed`. Fixes an issue brought up in [a support thread].
[a support thread]: https://discord.com/channels/745809834183753828/745811192102125578/918361932510162984
> fix(http): properly serialize `CommandBorrowed::kind`

- model/src/invite/mod.rs
The `twilight_model::invite::Invite::channel` field is optional in Discord's API.
[Documentation for this change][1].
[1]: https://github.com/discord/discord-api-docs/commit/b9663021282673f07d08728147a7bdc6cc45a82a
> chore!(model/invite): channel is optional

- http/src/api_error.rs
Add two new HTTP error codes:
- 20029: The write action you are performing on the server has hit the write rate limit[1]
- 50055: Invalid Guild[2]
[1]: https://github.com/discord/discord-api-docs/pull/4214
[2]: https://github.com/discord/discord-api-docs/pull/4212
> enhancement(http): add error codes 20029 and 50055

- http/src/routing/route_display.rs
Improve the test coverage of the `twilight_http::routing::route_display` module by testing the `Display` implementations of routes.
This also fixes route implementations for three routes, discovered by creating these tests:
- Create Guild Prune w/ `include_roles` query param
- Sync Guild Integration
- Update Current User Voice State
**Todo**:
> enhancement(http/routing): improve test coverage

- cache/in-memory/src/model/emoji.rs
The docs for `CachedEmoji::available` and `CachedEmoji::animated` were swapped by accident.
> fix(cache-inmemory): swapped docs for CachedEmoji

- http/src/client/mod.rs
- lavalink/src/player.rs
- model/src/gateway/payload/outgoing/request_guild_members.rs
These were found by running
```sh
grep -R "\`\`\`" --include \*.rs -A 5 | grep marker
```
> docs: remove needless id marker imports

- cache/in-memory/Cargo.toml
- lavalink/Cargo.toml
- standby/Cargo.toml
No relevant API changes so allow 4.0 and 5.0
> deps: allow `Dashmap` 5

- model/src/channel/message/sticker/mod.rs
- model/src/channel/message/sticker/pack.rs
implements discord/discord-api-docs#4245
> chore(model): mark `StickerPack.banner_asset_id` Optional

- cache/in-memory/src/model/member.rs
Currently, the `member.rs` file returns a nickname for the avatar function. This PR makes the function return the proper avatar.
Fixes #1340
> fix(model): CachedMember#avatar returning nicknames

- gateway/Cargo.toml
- gateway/src/cluster/builder.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/config.rs
- gateway/src/shard/mod.rs
- gateway/src/shard/processor/impl.rs
- gateway/src/shard/tls.rs
This saves a lot of memory when `native-tls` is used and a moderate
amount when `rustls` is used.
This pr depends on #1276.
> Gateway: Reuse tls connectors between shards

- gateway/src/shard/tls.rs
Handling of TlsErrorType would in some cases cause compilation errors,
this patch remidies that.
This removes a borrow to make sure that the pattern is counted as
empty when it is so. 
This is a compiler issue tracked at https://github.com/rust-lang/rust/issues/24885.
It also adds a gate to let a variable go unused.
> Fix incorrect handling of TlsErrorType

- http-ratelimiting/src/in_memory/bucket.rs
Buckets store three headers of note: `remaining`, `retry_after`, and `started_at`. `remaining` is the number of remaining requests in the bucket until the next reset, `retry_after` is the number of milliseconds until the next reset (as of the response generation time), and `started_at` is an internal duration of when the bucket "started" counting up to the reset time (`retry_after`).
In theory, this is all fine: assuming a bucket with 5 requests in a 5000 millisecond time period, when we get the response and process it we start the internal `started_at` timer and wait the `retry_after`.
However, we had an error in our logic. We would only reset the `started_at` clock if the bucket had been manually reset, such as when the `remaining` is 0. This meant that if you waited more than 5000 …
> fix(http-ratelimiting): rework started at time

- cache/in-memory/src/lib.rs
- gateway/src/cluster/impl.rs
Remove old interior Arc cloning comments that were missed in #1067.
Closes #1346.
> docs(cache,gateway): remove old clone comments

- gateway/src/shard/impl.rs
Instead of ticketing the ratelimiter after a successful send, tick it before sending. By ticking the ratelimiter after sending we were at best simply blocking the task that performed the successful send, allowing shards to hit the ratelimit still.
> fix(gateway/shard): tick ratelimiter before send

- http/src/client/builder.rs
- http/src/client/mod.rs
- http/src/response/future.rs
Simplify token invalidation state by removing a field on `Client` and removing a token invalidation state wrapper specific to `ResponseFuture`.
> refactor(http): simplify token invalidation

- .github/workflows/check-lib.yml
- .github/workflows/codecov-lib.yml
- .github/workflows/deploy-lib.yml
It is implied when root the workspace, i.e. it's only useful when the current directory isn't root.
As it's already left out for most steps never using it is less confusing.
> actions: Remove `--workspace` flag

- http/src/routing/route_display.rs
Fix the Display implementation for the `GetActiveThreads` route. The start of the formatted path was `guild_id/` instead of `guilds/`.
Closes #1385.
> fix(http/routing): display for get active threads

- cache/in-memory/README.md
- cache/in-memory/src/lib.rs
- model/README.md
- model/src/lib.rs
Fix some named anchors that didn't have references in the READMEs of the `twilight-cache-inmemory` and `twilight-model` crates.
> docs(cache/in-memory,model): fix named anchors

- cache/in-memory/src/event/message.rs
- cache/in-memory/src/iter.rs
- cache/in-memory/src/lib.rs
Add a new iterator named `ChannelMessages` returning the message IDs of a channel. This is made available via the `InMemoryCache::channel_messages` method.
Closes #1358.
> feat(cache/in-memory): add channel messages iter

- README.md
- command-parser/README.md
- command-parser/src/lib.rs
- twilight/src/lib.rs
Deprecate the Command Parser crate because we now reasonably support interactions and deprecation of the message content intent is around the block.
> chore(command-parser): deprecate crate

- http/src/routing/route_display.rs
This did not make the endpoint not work, but it may cause isses
The errornous url used: `https://discord.com/api/v9//oauth2/applications/@me`
I have looked through the rest of the file and found no other instances of this.
> Remove erroneous forward slash

- http/src/response/future.rs
Support pre-flight request cancelation via a new method, `ResponseFuture::set_pre_flight`. This allows users to configure pre-flight checks to determine whether the request should be sent once it has cleared ratelimit queues.
Closes #574.
> feat(http/response): pre-flight cancelation

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR add a new GitHub Actions workflow that use [fuxingloh/multi-labeler](https://github.com/fuxingloh/multi-labeler) to automatically label pull requests depending on the file changes and the PR title:
- `c-*` and `t-github-actions` are added depending on the files changed by the PR. These labels are synced (except `c-all` and `t-github-actions`) so they will be automatically removed if the PR does no longer change these files.
- `t-*` and `m-breaking change` are added depending on the PR title. This will only work if the title respects the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
I made an example PR on my fork to test the action: https://github.com/baptiste0928/twilight/pull/1
> ci: automatically label pull request

- cache/in-memory/src/event/channel.rs
- cache/in-memory/src/event/guild.rs
- examples/model-webhook-slash/src/main.rs
- http/src/client/mod.rs
- http/src/response/future.rs
- lavalink/src/node.rs
- lavalink/src/player.rs
Instead borrowing the resource. Follows the Rust ecosystem's move away from this keyword and makes the codebase more consistent.
`&` and `&mut` were previously (rust <1.26) not supported in match statements and is probably why the keyword was used.
> refactor: don't use the `ref` keyword

- http-ratelimiting/src/headers.rs
Support the `x-ratelimiting-scope` header, which indicates the scope of a ratelimit. Possible values are "global" (an application global ratelimit), "shared" (shared ratelimit between applications across a resource), and "user" (individual ratelimit, e.g. for an individual bucket).
> feat(http-ratelimiting): support 'scope' header

- examples/model-webhook-slash/src/main.rs
- model/src/application/callback/callback_data.rs
- model/src/application/callback/mod.rs
- util/src/builder/callback_data.rs
Currently it's not possible to remove embeds of a message from a component interaction in the first response. This PR should fix this.
Example: 
```rs
http.interaction_callback(
component.id,
&component.token
&InteractionResponse::UpdateMessage(
CallbackData {
allowed_mentions: None,
components: None,
content: None,
embeds: Vec::new(), // This field gets skipped if empty so embeds cannot be removed
flags: None,
tts: None,
}
)
)
```
> fix(model)!: make CllbackData#embeds an option

- gateway/src/shard/processor/impl.rs
Correctly handle gateway close codes 4010, 4011 and 4012
| Code | Description         |
|------|---------------------|
| 4010 | Invalid shard       |
| 4011 | Sharding required   |
| 4012 | Invalid API version |
closes #1377
> chore(gateway): handle previously unhandled error codes 4010-4012

- cache/in-memory/src/lib.rs
This was missing for some reason, even though the data necessary to provide it is kept in the cache.
> feat(cache-inmemory): InMemoryCache::guild_voice_states

- cache/in-memory/src/lib.rs
- util/src/lib.rs
`#[cfg(feature)]` implies `#[doc(cfg(feature))]`
> doc: Remove explicit `doc(cfg)`

- cache/in-memory/src/event/member.rs
- cache/in-memory/src/permission.rs
- model/src/gateway/payload/incoming/member_update.rs
adds the field to the member update payload and makes the cache update with it
> feat(model,cache-inmemory): communication_disabled_until on member update

- model/src/gateway/payload/incoming/thread_list_sync.rs
Typing was wrong in this model. Technically a breaking change but targeted at main since it's an an incorrect mapping
> fix(model): thread sync has channel ids, not guild ids

- model/src/guild/audit_log/change.rs
- model/src/guild/audit_log/change_key.rs
Reference: https://github.com/discord/discord-api-docs/commit/c63a4d5a604b6c2dbb5e5b5c1e3c2a101e96df44
> feat(model): add CommunicationDisabledUntil audit log

- gateway/src/shard/processor/impl.rs
This is way too noisy for warnings, the gateway emits events twilight doesn't know about (yet) non stop
> feat(gateway): drop failed event parsing to debug

- gateway/src/shard/processor/session.rs
Discord counts a heartbeat ACK as 1 of the 120 allowed gateway payloads and regularly request these. By reserving twice the payloads for heartbeating we should have enough capacity to respond to these without going over the rate limit and get disconnected.
> fix(gateway): reserve extra capacity for heartbeat response

- cache/in-memory/src/event/thread.rs
- model/src/gateway/payload/incoming/thread_delete.rs
- standby/src/event.rs
ThreadDelete could not be deserialized as it expected a full channel struct while we only get a few fields as per the docs: https://discord.com/developers/docs/topics/gateway#thread-delete.
Targeted against main despite being a breaking change as it's an incorrect mapped struct that can't deserialize otherwise
> fix(model): correctly deserialize ThreadDelete events

- gateway/src/shard/json.rs
- gateway/src/shard/processor/impl.rs
Bumping it up to error for visibility on both the general error and the payload. This allows easier tracking down of broken payloads even in production environments where the debug level is way too verbose when you are looking for a single broken payload type without knowing what event type is failing.
> feat(gateway): make parse errors much more visible

- cache/in-memory/Cargo.toml
- lavalink/Cargo.toml
- standby/Cargo.toml
Using `Ref::value` with `dashmap` 5 may produce a reference that outlive the Ref and thus cause undefined behavior. Issues with the cache [have been reported on Discord](https://discord.com/channels/745809834183753828/745811216579952680/929856218120462396) and *may* be related to that. See https://github.com/xacrimon/dashmap/issues/167 for more information.
I think we should downgrade dashmap until a patch is released, as `Ref::value` is used in some places with the cache. The issue is not affecting dashmap 4.
This reverts https://github.com/twilight-rs/twilight/pull/1336.
> chore: downgrade to `dashmap` 4

- http/src/client/interaction.rs
- http/src/request/application/command/create_global_command/chat_input.rs
- http/src/request/application/command/create_global_command/message.rs
- http/src/request/application/command/create_global_command/mod.rs
- http/src/request/application/command/create_global_command/user.rs
- http/src/request/application/command/create_guild_command/chat_input.rs
- http/src/request/application/command/create_guild_command/message.rs
- http/src/request/application/command/create_guild_command/mod.rs
- http/src/request/application/command/create_guild_command/user.rs
- validate/src/command.rs
This PR improves validation of slash command names and command options names. It checks that chat input command names and options names does not contain non-alphanumeric characters nor uppercase characters.
As the validation depend on the command type, the name is no longer validated in `create_guild_command` or `create_global_command` methods. The validation has been moved to `chat_input`, `user` and `message` methods.
> feat(validate, http)!: validate command and options names

- cache/in-memory/src/lib.rs
As C-SEALED recommends, most Twilight's traits are already sealed.
> feat(cache)!: Seal `UpdateCache`

- gateway/src/shard/processor/session.rs
This code is from the first implementation of `gateway`, back then `Drop` contained this code:
```rust
impl Drop for Session {
fn drop(&mut self) {
let handle = Arc::clone(&self.heartbeater_handle);
tokio::spawn(async move {
if let Some(handle) = handle.lock().await.take() {
handle.abort();
}
});
}
}
```
Because `handle` is no longer wrapped around an Async Mutex there's no await, and no need to spawn a new task.
The current implementation is just:
```rust
impl Session {
// ...
pub fn stop_heartbeater(&self) {
if let Some(handle) = self
.heartbeater_handle
.lock()
.expect("heartbeater poisoned")
.take()
{
handle.abort();
}
}
// ...
}
impl Drop for Session {
fn drop(&mut self) {
self.stop_heartbeater();
}
}
```
removing the need for `Arc`.
> refactor(gateway/session): Remove `Arc` around heartbeat handle

- .github/workflows/check-lib.yml
The issue causing workflows to fail with [`baptiste0928/cargo-install`](https://github.com/baptiste0928/cargo-install) had been fixed in version 1.0.1.
> ci: restore `baptiste0928/cargo-install` action

- http/src/request/application/interaction/mod.rs
- http/src/request/channel/invite/mod.rs
- http/src/request/channel/message/mod.rs
- http/src/request/channel/mod.rs
- http/src/request/channel/reaction/mod.rs
- http/src/request/channel/stage/mod.rs
- http/src/request/channel/thread/mod.rs
- http/src/request/guild/ban/mod.rs
- http/src/request/guild/member/mod.rs
- http/src/request/guild/mod.rs
- http/src/request/template/mod.rs
- http/src/request/user/mod.rs
These were missed in the validate crate PR. They do not need to be public anymore.
> refactor(http)!: remove unneeded public modules

- cache/in-memory/src/model/member.rs
- cache/in-memory/src/model/presence.rs
Currently the implementations of `PartialEq` in the cache are using two different methods. This PR changes this to one in sake of consistency.
> refactor(cache): implement `PartialEq` in a consistent way

- http/src/request/channel/reaction/mod.rs
- http/src/routing/route_display.rs
> refactor(http/request/reaction)!: impl `Display` on `RequestReactionType`

- gateway/Cargo.toml
`>=0.14, <0.19` can't be used since 0.18 drops the `std` feature
Targeting next so users aren't forced to update metrics locally.
> feat(gateway): Update `metrics` to 0.18

- gateway/src/cluster/builder.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/impl.rs
This was intened to land at the same time as `twilight_http::Client` constructor's got reworked in the same way.
> feat(gateway)!: Constructors take `String`, not `Into<String>`

- cache/in-memory/src/event/stage_instance.rs
- model/src/channel/stage_instance/mod.rs
- model/src/channel/stage_instance/privacy_level.rs
> refactor(model)!: stage discovery has been removed

- model/src/guild/widget.rs
As indicated in the [docs](https://discord.com/developers/docs/resources/guild#guild-widget-object) the returning object's `channel_id` can be `null`
> fix(model)!: `GuildWidget::channel_id` can be `None`

- gateway/src/cluster/builder.rs
- gateway/src/cluster/config.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/config.rs
Provides a function that takes a closure which allows setting a shard's presence based on its id.
Closes #1472.
> feat(gateway): custom shard presences on identify

- gateway/Cargo.toml
- gateway/README.md
- gateway/src/lib.rs
- gateway/src/shard/processor/compression/mod.rs
~~This feature was broken, hence removing it.~~ Also needed for `cargo hack --feature-powerset check` to work.
Sort of related to #1314
Removing the feature is too breaking even through it was broken since it was publicly recommended, so it's to be removed in another PR on next. This PR "disables" the feature and moves the logic into `cfg(any(feature = "zlib-stock", feature = "zlib-simd"))`, similarly to how http manages it's TLS backends
> refactor(gateway): Move compression logic from `compression` feature to `zlib-*`

- model/src/id/mod.rs
Type was only used one time: inside of Serialize impl. Replaced by Id's own Display impl, which is identical.
And no, this does not allocate more, `serializer.collect_str`'s default implementation calls `.to_string()`
> refactor(model/id): Remove internal `IdStringDisplay`

- .github/workflows/check-lib.yml
This will still run CI on all pull requests, however for more complicated PRs that require authors creating their own branches on the main repository, this prevents CI from running twice, saving resources.
> ci: restrict push runs to `main` and `next`

- model/src/id/mod.rs
Just wanted to update to the latest `0.9.0` release and noticed that you can get the `Id<T>` as a `u64` but not the real inner value `NonZeroU64`.
This is especially helpful if you already used the inner `NonZeroU64` from the old ID types (as in my case). Currently the only way to get the value as that type is to do `NonZeroU64::new(id.get()).unwrap()` and I would like to avoid the `unwrap` (even though it can't fail).
This PR adds convenient `From` conversions for `u64` and `NonZeroU64` as well, so you can call `into()` in many cases.
﻿
> Allow retrieving the `NonZeroU64` from `Id<T>`

- cache/in-memory/src/event/guild.rs
- cache/in-memory/src/event/mod.rs
Added a test to showcase what the behaviour looks like now: Guild gets marked as unavailable, guild entities are removed from the cache.
Previously, the guild was removed from the cache, but entities remained (especially in `guild_members` and `members`). When the guild went available again, it was added to the cache, but `guild_members` was cleared and all member inserts were skipped due to the members already being in `members` cache.
> fix(cache-inmemory): Proper handling and cleanup on UnavailableGuild

- gateway/src/cluster/builder.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/config.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/processor/impl.rs
- gateway/src/shard/processor/session.rs
Via `Config::payload_ratelimiting`. This logically requires making ratelimiting information on `Information` optional, since it might be disabled.
Part of #1488
> feat(gateway)!: Allow disabling payload ratelimiting

- http/src/client/interaction.rs
- http/src/request/application/command/set_global_commands.rs
- http/src/request/application/command/set_guild_commands.rs
- model/src/application/callback/callback_data.rs
- model/src/application/command/mod.rs
it'd be nice if it linked to api.twilight.rs if the link is clicked there, but i don't think that's doable easily.. also is there any other broken links in the docs?
> docs(http,model): fix broken associated builder links 

- model/src/channel/message/flags.rs
Updates the `MessageFlags` bitflags to the current state of the Discord docs, and document each flag.
Closes #1496.
> feat(model): bring `MessageFlags` up to date

- http/src/request/scheduled_event/create_guild_scheduled_event/external.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/mod.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/stage_instance.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/voice.rs
- http/src/request/scheduled_event/update_guild_scheduled_event.rs
- model/src/scheduled_event/mod.rs
Adds `GuildScheduledEvent::image`. Adds methods to `CreateGuildScheduledEvent`'s derivatives and `UpdateGuildScheduledEvent` to add and update the image.
Closes #1502.
> feat(http,model): scheduled event cover images

- http/src/request/application/interaction/create_followup.rs
- http/src/request/application/interaction/update_followup.rs
- http/src/request/application/interaction/update_response.rs
- http/src/request/channel/message/create_message.rs
- http/src/request/channel/message/update_message.rs
- http/src/request/channel/webhook/execute_webhook.rs
- http/src/request/channel/webhook/update_webhook_message.rs
- validate/src/message.rs
Ensure attachment filenames are composed of ASCII alphanumeric characters, dots, dashes, or underscores.
Closes #1465.
> feat(http,validate)!: validate attachment filenames

- util/src/builder/command.rs
Add the attachment command builder that was missing in #1537.
Related: #1523
> feat(util): add attachment command builder

- model/src/guild/audit_log/event_type.rs
Previously, the `AuditLogEventType` enum did not contain values for guild scheduled events. This PR fixes that.
Closes #1546.
> fix(model): add scheduled event action types

- http/src/request/application/interaction/create_followup.rs
- http/src/request/channel/message/create_message.rs
- http/src/request/channel/message/update_message.rs
- http/src/request/channel/webhook/execute_webhook.rs
This PR replaces all methods of setting `MessageFlags` (`ephemeral`, `suppress_embeds`) with a simpler and more flexible `flags` method.
Closes #1470.
> feat(http)!: support setting `MessageFlags` on applicable methods

- gateway/Cargo.toml
- gateway/src/shard/processor/impl.rs
- lavalink/Cargo.toml
This update contains no changes relevant for us, only support for sending raw frames and adaptation to changes regarding the `sha1` crate.
> build(gateway, lavalink): Update to tokio-tungstenite 0.17

- examples/model-webhook-slash.rs
- model/src/http/interaction.rs
This PR implements `Default` on `InteractionResponseData`. Since it is a type that is only sent to Discord, it could reasonably be assumed that its default value is empty. This is helpful when users wish to only send `content`, without using a builder:
```rust
let response = InteractionResponse {
kind: InteractionResponseType::ChannelMessageWithSource,
data: Some(InteractionResponseData {
content: Some("some content".into()),
..Default::default()
}),
};
```
> feat(http): impl `Default` on `InteractionResponseData`

- model/src/application/command/command_type.rs
- model/src/application/command/option.rs
- model/src/application/component/kind.rs
- model/src/application/interaction/application_command_autocomplete/option.rs
- model/src/application/interaction/interaction_type.rs
- model/src/channel/channel_type.rs
- model/src/channel/message/activity_type.rs
- model/src/channel/message/kind.rs
- model/src/channel/message/sticker/format_type.rs
- model/src/channel/message/sticker/kind.rs
- model/src/channel/webhook/kind.rs
- model/src/gateway/presence/activity_type.rs
- model/src/gateway/presence/status.rs
- model/src/guild/audit_log/event_type.rs
- model/src/http/interaction.rs
- model/src/invite/target_type.rs
- model/src/user/premium_type.rs
These enums have no obvious order to them from the point of view of the user.
Experts knowledgeable of Discords internal integer mapping can still compare them by first casting to an integer.
> fix(model)! Remove suspicious `Ord` implementations

- cache/in-memory/src/event/sticker.rs
- cache/in-memory/src/test.rs
`InMemoryCache::cache_stickers` operates by first retrieving a mutable reference to the set of sticker IDs for a guild and then allocating a Vec of the removed delta of sticker IDs between the cached set and the new set of IDs. The list of removed sticker IDs is then iterated over to remove it from the guild's set of IDs, and then iterated over again to remove the stickers from the cache.
We can instead call `HashSet::retain` to mutate over the set of guild stickers and remove from the set as necessary, removing from the cached stickers map at the same time if not retaining.
This removes two iterations (filtering removed IDs and one of the two actual removal iterations) and an allocation.
> perf(cache): remove iters, allocation when caching stickers

- cache/in-memory/src/event/emoji.rs
- cache/in-memory/src/event/guild.rs
- cache/in-memory/src/event/member.rs
- cache/in-memory/src/event/presence.rs
- cache/in-memory/src/event/sticker.rs
- cache/in-memory/src/event/voice_state.rs
- cache/in-memory/src/model/emoji.rs
- cache/in-memory/src/model/guild.rs
- cache/in-memory/src/model/member.rs
- cache/in-memory/src/model/message.rs
- cache/in-memory/src/model/mod.rs
- cache/in-memory/src/model/presence.rs
- cache/in-memory/src/model/sticker.rs
- cache/in-memory/src/model/voice_state.rs
Update the in-memory cache models with new fields from their `twilight_model` equivalents. To ensure that these models stay up to date in the future, initializers for most models have been extracted from being in the business logic of the library to being initializer functions on the cached model types themselves. To go along with this, initializers now exhaustively destructure models' fields to ensure that when a new field is added to the `twilight_model` variant of a cached model, it must be handled in the cached model's initializer as well.
The following fields have been added:
- `CachedGuild::max_video_channel_users`
- `CachedMessage::application_id`
- `CachedMessage::components`
- `CachedMessage::interaction`
- `CachedMessage::thread_id`
Field and implementation tests for all cached …
> feat(cache): add missing cached model fields

- cache/in-memory/src/event/presence.rs
- model/src/gateway/payload/incoming/presence_update.rs
- standby/src/event.rs
Presence Update Events are actually just the same as the Presence model, so we can just make the event a newtype of the presence.
> refactor(model)!: presence updates are presences

- validate/src/component.rs
Validate the required fields on buttons. In particular, this adds two new error variants: `ButtonConflict`, which occurs when a button has both a custom ID and URL; and `ButtonStyle`, which occurs when a button that has a style of `Link` does not have a URL or when a button that does not have a style of `Link` does not have a custom ID.
New validation in `component_inner` has been added, along with the two new error variants and tests. This also fixes two invalid portions of existing tests.
> feat(validate): button styles and required fields

- validate/src/component.rs
Separate out the validation logic for each type of component from the `component` function to individual `action_row`, `button`, `select_menu`, and `text_input` functions. This allows users to validate components that aren't wrapped in action rows.
> feat(validate): individual component validators

- .github/workflows/check-lib.yml
- cache/in-memory/src/lib.rs
- command-parser/src/lib.rs
- embed-builder/src/lib.rs
- gateway/src/lib.rs
- http-ratelimiting/src/lib.rs
- http/src/lib.rs
- lavalink/src/lib.rs
- mention/src/lib.rs
- model/src/lib.rs
- standby/src/lib.rs
- util/src/lib.rs
- validate/src/lib.rs
See
<https://github.com/rust-unofficial/patterns/blob/main/anti_patterns/deny-warnings.md>
Equivalent to #1598
> ci: move deny warnings to only ci

- http/src/request/guild/member/update_guild_member.rs
Rename `communication_disabled_util` field to `communication_disabled_until` in `twilight_http::Client::update_guild_member`
Closes #1611
> fix(http): communication_disabled_util => communication_disabled_until

- model/src/application/interaction/mod.rs
- model/src/application/interaction/modal/mod.rs
- model/src/http/interaction.rs
This adds the `guild_locale`, `locale` and `message` property to the `ModalSubmitInteraction` struct.
`message` is available when a modal response comes from a message component interaction.
Reference: https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure
> feat(model): add missing fields to `ModalSubmitInteraction`

- http/src/client/mod.rs
- http/src/request/channel/webhook/create_webhook.rs
- http/src/request/channel/webhook/update_webhook.rs
- http/src/request/channel/webhook/update_webhook_with_token.rs
- http/src/request/guild/create_guild/mod.rs
- http/src/request/guild/emoji/create_emoji.rs
- http/src/request/guild/update_guild.rs
- http/src/request/template/create_guild_from_template.rs
- http/src/request/user/update_current_user.rs
For the sake of consistency this changes every Image Data to be provided through a `&'a [u8]`.
> refactor(http)!: make Image Data to take a &'a [u8]

- .github/workflows/check-lib.yml
I suspect that a bottleneck in our workflow is how long it can take to compile. This adds a unique key segment based on the ref name.
> ci: use a custom cache key per job

- model/src/id/mod.rs
This is to ensure layout compatibility with NonZeroU64 (and by extension u64).
> feat(model): add `#[repr(transparent)]` to `Id`

- model/src/id/marker.rs
- model/src/id/mod.rs
Dropping `Debug` too should be fine imo, but it's not as "wrong" as `Clone` & `Copy`
> refactor(model)!: Drop unneeded marker trait impls

- model/src/guild/audit_log/change.rs
- model/src/guild/audit_log/change_key.rs
This adds the `image_hash` audit log change key which is being used when a guild scheduled event cover image gets updated.
Reference: https://github.com/discord/discord-api-docs/pull/4707
Closes: #1627
> feat(model): add `image_hash` audit log change key

- validate/src/component.rs
A text input's label has a min length of 1 (since it's a required property) and a max length of 45.
Reference: https://github.com/discord/discord-api-docs/pull/4689
Closes: #1630
> fix(validate): text input label min length is 1 and max is 45

- http/src/request/attachment.rs
- model/src/http/attachment.rs
- model/src/http/interaction.rs
Previously, `Attachment` structs sent inside `InteractionResponseData` would both serialize the entire file in the JSON body and fail to include its ID, which made it inefficient and impossible for Discord to associate attachment metadata with attachment data.
As a result, users are now required to specify their own ID when adding attachments to all create-message-like request builders. While breaking and annoying, this is a more robust solution than others, which would require a lot more code to temporarily fix a problem.
> fix(http,model)!: properly serialize attachments in `CreateResponse`

- http/src/request/application/interaction/create_followup.rs
- http/src/request/application/interaction/update_followup.rs
- http/src/request/application/interaction/update_response.rs
These were missed in previous refactoring, these are private types.
> refactor(http): rename interaction field structs

- http/src/request/channel/stage/create_stage_instance.rs
Add the ability to notify everyone when a stage instance starts when creating stage instances.
Closes #1651.
> feat(http): stage instance everyone notification

- model/src/channel/channel_type.rs
Add the new "Guild Directory" channel type, implemented as `ChannelType::GuildDirectory` with a value of 14.
Closes #1654.
> feat(model): add guild directory channel type

- model/src/user/flags.rs
Slightly tweak the `UserFlags::HYPESQUAD` flag's documentation to say "HypeSquad events member" instead of "HypeSquad events coordinator" to match Discord's documentation:
<https://github.com/discord/discord-api-docs/pull/4685>
> docs(model): tweak hypesquad user flag docs

- http/src/request/guild/update_guild.rs
Add a notice to the `UpdateGuild::features` method that adding or removing the "COMMUNITY" feature requires the `ADMINISTRATOR` permission.
Closes #1662.
> docs(http): update guild community feature notice

- mention/src/parse/error.rs
- mention/src/parse/impl.rs
- mention/src/parse/iter.rs
- mention/src/parse/mod.rs
Remove support for nickname mentions due to Discord removing them from documentation:
<https://github.com/discord/discord-api-docs/commit/a8f7638e79391bb70e15996d1d88488a3b6364b2>
> refactor(mention)!: remove nickname mention support

- README.md
- gateway-queue/README.md
- gateway-queue/src/lib.rs
- http-ratelimiting/README.md
- http-ratelimiting/src/lib.rs
- lavalink/README.md
- lavalink/src/lib.rs
- twilight/src/lib.rs
Add missing links to the `tracing` crate in crate-level documentation for `gateway-queue`, `http-ratelimiting`, and `lavalink`. This causes rustdoc errors when building individual crates.
> docs: add missing tracing crate links

- model/src/oauth/application.rs
The `twilight_model::oauth::Application::owner` field is now optional according to Discord's documentation:
<https://github.com/discord/discord-api-docs/blob/a8f7638e79391bb70e15996d1d88488a3b6364b2/docs/resources/Application.md>
> refactor(model)!: application owner is optional

- .github/workflows/check-lib.yml
After using these custom keys for a while, I'm noticing more often than not the cache missing resulting in a longer run time overall.
This reverts commit a23f25f7e4bd1784adf909c245c9dac15f5f4401.
> ci: revert custom cache key

- http/src/response/status_code.rs
Deprecate `twilight_http::response::StatusCode::raw` and rename the function to `get`, which aligns with other newtype-like getters such as IDs and smart pointers.
> refactor(http): rename statuscode::raw to get

- cache/in-memory/src/permission.rs
In the permission calculator extension, the `parent_overwrites` function was meant to combine a thread's permission overwrites with its parent channel's overwrites. However, this function's previous behavior was to retrieve itself from the cache again, and combine its overwrites with itself. This PR fixes this by actually retrieving the channel from the `parent_id` field, if it exists, and combining the overwrites in a clearer way.
> fix(cache): rework `parent_overwrites`

- lavalink/src/node.rs
Add the missing header due to a regression in `tokio-tungstenite`.
Closes #1647.
> fix(lavalink): include `Sec-WebSocket-Key` header

- model/src/channel/channel_type.rs
As a stopgap before future work on Forum channels, add their channel type in order to stop deserialization errors which would be more correctly fixed in #1550.
> feat(model): add `ChannelType::GuildForum`

- cache/in-memory/src/event/emoji.rs
- cache/in-memory/src/event/member.rs
- cache/in-memory/src/event/mod.rs
- cache/in-memory/src/event/reaction.rs
- cache/in-memory/src/event/sticker.rs
- cache/in-memory/src/event/voice_state.rs
- cache/in-memory/src/lib.rs
- gateway/src/shard/impl.rs
- http-ratelimiting/src/in_memory/bucket.rs
- http/src/request/mod.rs
- lavalink/src/node.rs
- mention/src/parse/iter.rs
Prefer to use `if let`s over `match`es on Options and Results. This is generally an "idiomatic" thing to do and also reduces indentation.
> refactor: use `if let` on matches over options and results

- cache/in-memory/README.md
- cache/in-memory/src/lib.rs
- cache/in-memory/src/stats.rs
Document the ability to retrieve statistics about the resources in the cache in the crate-level documentation, and add an example for using the statistics interface on the `InMemoryCacheStats` type itself.
> docs(cache/in-memory): stats in crate-level docs

- cache/in-memory/src/stats.rs
Fix some typos in the stats docs that left underscores in place of where there should be spaces.
> docs(cache/in-memory): fix typos in stats docs

- gateway/Cargo.toml
- gateway/src/lib.rs
- http/Cargo.toml
- http/src/lib.rs
After updating our MSRV to 1.60, this dependency restriction is no longer required.
This reverts commit 0d41c21c3e8795012195c6767d11b9964eb5880d.
> build(gateway,http): revert #1596

- http/src/routing.rs
Simplify the `Routing::GetGuildScheduledEventUsers` Display implementation by letting Discord decide how to take precedence, rather than us doing the logic for the API and possibly making the implementation out of date in the future.
This was created out of discussion from #1657.
> refactor(http)!: simplify scheduled event routing

- model/src/guild/permissions.rs
This adds the `USE_EXTERNAL_STICKERS` permission flag (1 << 37).
Reference: https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
> feat(model): add `USE_EXTERNAL_STICKERS` permission flag

- cache/in-memory/src/model/message.rs
- model/src/channel/message/mod.rs
- model/src/gateway/payload/incoming/message_update.rs
Add caveats to the documentation for `twilight_model::channel::Message` about receiving the attachments, components, content, and embeds of messages. Additionally, add light documentation for them on `twilight_cache_inmemory::model::Message` and `twilight_model::gateway::payload::incoming::MessageUpdate`, pointing to the documentation for `Message` for additional information.
> docs(cache, model): message content intent caveats

- http/src/request/guild/ban/get_bans.rs
- http/src/routing.rs
- validate/src/request.rs
Support pagination on the `GetGuildBans` request via three new builder methods:
- `after`, to retrieve bans after a user ID
- `before`, to retrieve bans before a user ID
- `limit`, to specify the maximum number of bans to retrieve, up to 1000
A new route, `GetBansWithParameters`, has been added due to being unable to modify the `GetBans` variant.
`twilight_validate::request::get_guild_bans_limit` has been added, checking the new constant `GET_GUILD_BANS_LIMIT_MAX` and returning an error of type `GetGuildBans` if the provided limit is over the maximum.
Closes #1656.
> feat(http): support get guild bans pagination

- model/src/guild/permissions.rs
This adds the `MANAGE_EVENTS` permission flag (1 << 33).
Reference: https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
> feat(model): add `MANAGE_EVENTS` permission flag

- gateway/src/shard/impl.rs
- gateway/src/shard/mod.rs
Prominently show an example for chunking a guild's members by moving the example from `Shard::command` to the `shard` module-level documentation under its own header. Adds an example to update the shard's presence in its place on `Shard::command`, similar to that of `Cluster::command`.
> docs(gateway): prominently show member chunking

- cache/in-memory/Cargo.toml
- lavalink/Cargo.toml
- standby/Cargo.toml
[`dashmap` v5.3.0](https://github.com/xacrimon/dashmap/releases/tag/v5.3.0) introduced a MSRV breaking change which makes the CI fails ([example](https://github.com/twilight-rs/twilight/runs/6241189438)). This pins the dashmap version to any semver version below `5.3` to fix the CI while waiting to bump the MSRV.
See also https://github.com/twilight-rs/twilight/pull/1699
> fix: pin dashmap version

- model/src/http/interaction.rs
I've done some testing and `Interaction::ModalSubmit` seems to be allowed to be responded to with these types, `DeferredChannelMessageWithSource` is still allowed but it creates another deferred message that replies to the bot's original message.
> docs(model): modal submits valid for `DeferredUpdateMessage` and `UpdateMessage`

- cache/in-memory/src/event/message.rs
A cache configured with `message_cache_size(1)` could fit up to two messages instead of one.
This corrects it to fit upto the configured value.
Closes #1696
> fix(cache): correct `channel_messages` max len

- model/src/application/interaction/modal/mod.rs
> fix(model): `ModalSubmitInteraction` `message` gets orphaned and not nulled

- http/src/request/channel/message/create_message.rs
Currently it is not possible to set the `fail_if_not_exists` property to `false`. This changes that by adding a boolean option to `fail_if_not_exists` so the user can indicate whether to fail or not.
Closes: #1676
> fix(http)!: `CreateMessage` take a boolean option for `fail_if_not_exists`

- gateway/src/event.rs
`COMMAND_PERMISSIONS_UPDATE` was accidentally duplicated, this PR fixes that.
> fix(gateway)!: remove duplicate `EventTypeFlags` value

- model/src/application/interaction/mod.rs
All variants of `Interaction` contain a token and most methods only require a reference to it, so this method would be very convenient and be used frequently
There's the possible overhead of unnecessary matches on the 5 variants of `Interaction` but i'd assume it's very very tiny
This also can't be `const` because of the coercion from `String` to `&str`
> Add method to retrieve token of interaction

- http/src/error.rs
See <https://discord.com/developers/docs/reference#error-messages>.
Closes #1116
> feat(http): print API 8 error messages

- .github/dependabot.yml
Monitoring github actions' versions is tedious task that's better left to be automated.
Note that rust dependencies are *excluded* and are left for us humans to monitor.
> ci: add dependabot monitoring of github-actions

- cache/in-memory/Cargo.toml
- lavalink/Cargo.toml
- standby/Cargo.toml
DashMap has since 5.1 undergone critical security and bug fixes that could potentially cause deadlocks in extremely rare cases along with performance improvements for hashing. Lets update to 5.3.
> Update dashmap to 5.3

- http-ratelimiting/src/headers.rs
Catch erroneous boolean header values by checking that headers are valid UTF-8 and then parsing into a boolean.
Split out from PR #1720.
> refactor(http-ratelimiting): catch erroneous bool headers

- http-ratelimiting/src/headers.rs
- http-ratelimiting/src/in_memory/mod.rs
See individual commit messages for more info.
This could be split into two PRs, but the changes are so small that it felt needless.
I hope to rework and document `http-ratelimiting` further to increase its maintainability.
> refactor(http-ratelimiting): cleanup `InMemory::entry`

- gateway/README.md
- gateway/src/lib.rs
> docs(gateway): mention that TLS is optional

- gateway/src/shard/processor/socket_forwarder.rs
The previous nested `Either` was very hard to read and delegating the timeout to a function is also more self documenting.
> refactor(gateway): use timeout over sleep

- http-ratelimiting/src/in_memory/mod.rs
- http-ratelimiting/src/lib.rs
Methods returning `bool` should generally be prefixed with `is_`.
> refactor(http-ratelimiting)!: rename method to be idiomatic

- gateway-queue/README.md
- gateway-queue/src/lib.rs
EOF links in markdown require a blankline separating them from the rest of the file. Add one for it to properly link
> docs(gateway-queue): fix the sharding for very large bots hyperlink

- .github/workflows/check-lib.yml
- gateway-queue/Cargo.toml
- gateway-queue/src/lib.rs
- gateway/src/cluster/builder.rs
Instead of testing some packages' feature combinations, check them all with `cargo hack check --feature-powerset`. Tests aren't feature dependent so running `cargo check` is good enough and also faster.
depends on ~~#1483~~, ~~#1482~~, ~~#1392~~
> ci: check all feature combinations

- http-ratelimiting/Cargo.toml
- http-ratelimiting/src/in_memory/bucket.rs
Improves readability as each tracing call uses the same parent span.
> refactor(http-ratelimiting): use `instrument` for spans

- http/src/request/guild/update_guild_welcome_screen.rs
- http/src/request/mod.rs
- refactor(http): remove `request::slice_is_empty()`
- refactor(http): clean up `request::audit_header`
- refactor(http): derive `Serialize` on `NullableField`
> refactor(http): nits in the `request` module

- http/src/client/mod.rs
- http/src/request/channel/webhook/create_webhook.rs
- http/src/request/channel/webhook/update_webhook.rs
- http/src/request/channel/webhook/update_webhook_with_token.rs
- http/src/request/guild/create_guild/mod.rs
- http/src/request/guild/emoji/create_emoji.rs
- http/src/request/guild/update_guild.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/external.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/mod.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/stage_instance.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/voice.rs
- http/src/request/scheduled_event/update_guild_scheduled_event.rs
- http/src/request/template/create_guild_from_template.rs
- http/src/request/user/update_current_user.rs
Discord expects that Data URIs get send as a string therefore we should take a &str accordingly.
> fix(http)!: imaga Data URIs need to be a string

- gateway/src/shard/processor/compression/mod.rs
Allow the `clippy::ptr_arg` lint on `compression::add_url_feature`, which conditionally uses the provided `&mut String`. Clippy recommends making this take `&mut str` where zlib is disabled since it's not used, but because we'll always be passing an allocated string in anyway this isn't worth breaking the function up to fix.
> refactor(gateway): allow `ptr_arg` lint on conditional

- model/src/guild/integration.rs
The `enabled` field of `GuildIntegration` isn't always present and is optional.
Closes #1714.
> feat!(model): `integration::enabled` is optional

- http/src/request/channel/thread/create_thread.rs
- http/src/request/channel/thread/create_thread_from_message.rs
- model/src/channel/mod.rs
- model/src/channel/thread/metadata.rs
Document that thread automatic archive durations are no longer boost locked, where 3-day and 7-day durations were previously locked behind guild boosting.
Closes #1713.
> docs(http, model): auto archives not boost locked

- http/src/request/channel/webhook/create_webhook.rs
- http/src/request/channel/webhook/update_webhook.rs
- http/src/request/channel/webhook/update_webhook_with_token.rs
- http/src/request/guild/create_guild/mod.rs
- http/src/request/guild/emoji/create_emoji.rs
- http/src/request/guild/update_guild.rs
- http/src/request/mod.rs
- http/src/request/scheduled_event/create_guild_scheduled_event/mod.rs
- http/src/request/scheduled_event/update_guild_scheduled_event.rs
- http/src/request/template/create_guild_from_template.rs
- http/src/request/user/update_current_user.rs
Backport the fixes from #1744 to serialize image data as strings. We can achieve this by still accepting bytes, but serializing them as strings.
Relates to #1744.
> fix(http): backport #1744 string image serializers

- http/src/request/application/interaction/create_followup.rs
- http/src/request/application/interaction/update_followup.rs
- http/src/request/application/interaction/update_response.rs
- http/src/request/channel/message/create_message.rs
- http/src/request/channel/message/update_message.rs
- http/src/request/channel/update_channel.rs
- http/src/request/channel/webhook/execute_webhook.rs
- http/src/request/channel/webhook/update_webhook.rs
- http/src/request/channel/webhook/update_webhook_message.rs
- http/src/request/channel/webhook/update_webhook_with_token.rs
- http/src/request/guild/member/update_guild_member.rs
- http/src/request/guild/role/update_role.rs
- http/src/request/guild/update_guild.rs
- http/src/request/guild/update_guild_widget.rs
- http/src/request/guild/user/update_current_user_voice_state.rs
- http/src/request/mod.rs
- http/src/request/scheduled_event/update_guild_scheduled_event.rs
- http/src/request/user/update_current_user.rs
Shorter to write and the type is generic; not just for fields.
> refactor(http): rename `NullableField` to `Nullable`

- model/src/http/attachment.rs
Add example and clarify the purpose of the id field on Attachment.
> docs(model): expand `Attachment` documentation

- cache/in-memory/src/event/interaction.rs
- model/src/application/interaction/application_command/data.rs
- model/src/application/interaction/application_command/mod.rs
- model/src/application/interaction/application_command/option.rs
- model/src/application/interaction/mod.rs
Add the `CommandData::guild_id` field, which denotes the ID of the guild the command is registered in.
Closes #1716.
> feat(model): add command data guild_id field

- gateway/src/cluster/builder.rs
- gateway/src/shard/builder.rs
- http/src/client/builder.rs
- http/src/request/base.rs
- http/src/request/multipart.rs
- model/src/channel/message/allowed_mentions/builder.rs
Conservative first change for our `#[must_use]` policy.
> refactor: `#[must_use]` on builders, not methods

- gateway/Cargo.toml
- gateway/README.md
This means that it is no longer nessesary to make sure that zlib-stock
is anywhere in the dependency to make sure it is used instead of
zlib-ng.
For more information see: https://internals.rust-lang.org/t/psa-flate2-now-supports-zlib-ng-natively-via-libz-ng-sys/16706
> Use zlib-ng directly instead of through zlib-sys

- .github/workflows/check-lib.yml
1. Checkout
2. Install toolchain
3. Cache dependencies
4. Problem matchers
5. Custom tools installation
6. build/check/lint/test
Also replaces `baptiste0928/cargo-install` with `taiki-e/install-action`, which suppots shorter configuration and is more mainstrem (also already used for nextest installation).
> ci: standardize job steps order and actions

- cache/in-memory/src/builder.rs
- cache/in-memory/src/event/emoji.rs
- cache/in-memory/src/event/guild.rs
- cache/in-memory/src/event/interaction.rs
- cache/in-memory/src/event/message.rs
- cache/in-memory/src/event/role.rs
- cache/in-memory/src/event/voice_state.rs
- cache/in-memory/src/lib.rs
- cache/in-memory/src/model/emoji.rs
- cache/in-memory/src/model/member.rs
- cache/in-memory/src/model/voice_state.rs
- cache/in-memory/src/permission.rs
- cache/in-memory/src/test.rs
Based on #1644, standardize clippy lints and fix new ones that appear.  Some exceptions have been made.
> refactor(cache): standardize clippy lints

- gateway-queue/src/large_bot_queue.rs
- gateway-queue/src/lib.rs
> refactor(gateway-queue): standardize clippy lints

- http-ratelimiting/src/lib.rs
> refactor(http-ratelimiting): standardize clippy lints

- standby/src/event.rs
- standby/src/lib.rs
> refactor(standby): standardize clippy lints

- util/src/lib.rs
- util/src/snowflake.rs
Based on #1644, standardize clippy lints nd fix new ones that appear.
> refactor(util): standardize clippy lints

- validate/src/lib.rs
Based on #1644, standardize clippy lints nd fix new ones that appear.
> refactor(validate): standardize clippy lints

- http/Cargo.toml
- http/src/client/connector.rs
This PR updates the `hyper-trust-dns` dependency to `0.4`. Upstream breaking changes have been addressed. However, there should be no breaking changes for the consumers of `twilight-http`. Thanks! 🎉
> deps(http): upgrade `hyper-trust-dns`

- gateway-queue/README.md
Update the documentation link for large bot sharding due to the link section being renamed.
> Fix the large bot sharding hyperlink

- lavalink/src/client.rs
- lavalink/src/http.rs
- lavalink/src/lib.rs
- lavalink/src/model.rs
- lavalink/src/node.rs
- lavalink/src/player.rs
> refactor(lavalink): standardize clippy lints

- cache/in-memory/README.md
- examples/gateway-intents.rs
- examples/gateway-request-members.rs
- examples/gateway-shard.rs
- examples/lavalink-basic-bot.rs
- gateway/src/cluster/builder.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/config.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/mod.rs
- gateway/tests/test_shard_command_ratelimit.rs
- gateway/tests/test_shard_state_events.rs
- lavalink/README.md
- standby/README.md
This makes little sense and allows for removing `http_client` on ShardBuilder and making some methods infallible + no longer async. Instead, Cluster has to store a HTTP client for now.
> refactor(gateway)!: Don't validate tokens in ShardBuilder

- model/src/application/command/command_type.rs
Fix a typo on the documentation for `CommandType::User`.
> docs(model): fix command type typo

- model/src/application/component/mod.rs
Serialization length was incorrect for `Component::Button` struct, causing weird results with some formats ( `serde_json` is unaffected, but this gives an incorrect result with `rmp-serde` and `ciborium`).
> fix(model): button component serialization length

- .github/labeler.yml
- .github/workflows/book.yml
- .github/workflows/check.yml
- .github/workflows/deploy-lib.yml
- .gitignore
- Cargo.toml
- book/LICENSE.md
- book/README.md
- book/book.toml
- book/src/SUMMARY.md
- book/src/chapter_1_crates/section_1_model.md
- book/src/chapter_1_crates/section_2_http.md
- book/src/chapter_1_crates/section_3_gateway.md
- book/src/chapter_1_crates/section_4_cache_inmemory.md
- book/src/chapter_1_crates/section_6_standby.md
- book/src/chapter_1_crates/section_7_first_party/section_2_mention.md
- book/src/chapter_1_crates/section_7_first_party/section_3_lavalink.md
- book/src/chapter_1_crates/section_7_first_party/section_4_util.md
- book/src/chapter_1_crates/section_7_first_party/section_5_gateway_queue.md
- book/src/chapter_1_crates/section_7_first_party/summary.md
- book/src/chapter_1_crates/section_8_third_party.md
- book/src/chapter_1_crates/summary.md
- book/src/chapter_2_multi-serviced_approach.md
- book/src/chapter_3_bots_using_twilight.md
- book/src/chapter_4_changelogs.md
- book/src/overview.md
- book/src/support.md
- book/tests/Cargo.toml
- book/tests/build.rs
- book/tests/src/lib.rs
Inline the twilight documentation book hosted at our `twilight-rs.github.io` repository into the main repository `twilight`. This allows us to keep the book updated much more easily (at the same time as things are done!), and by being in the main repository it can have more attention through notifications and being in more of a spotlight.
Unfortunately, because of how GitHub Pages works we would not have been able to easily maintain having it located at the root of twilight.rs, which is a requirement due to it being our main entry point for our website. Because of this, the next best we can do is switch to Cloudflare's Pages. We already use for the API documentation and for DNS, so this is an easy switch over.
A live hosted version of documentation built from these changes can be found at …
> feat: inline book into repo

- .github/workflows/deploy-lib.yml
One of the steps for deploying API docs now excludes the book as a result of #1798, and while the `--exclude` flag was included for this the paired `--workspace` flag was missed.
> ci(deploy): add missing workspace flag

- lavalink/src/node.rs
Actual fix to #1647. `tungstenite` seems to have a strict header requirement which is best created via their `IntoClientRequest` trait.
This does however require a slightly nastier APIs for adding the headers for lavalink.
> fix: Properly initialize the tungstenite request via IntoClientRequest

- model/src/channel/reaction.rs
- model/src/gateway/payload/incoming/thread_members_update.rs
- model/src/gateway/payload/incoming/typing_start.rs
- model/src/guild/member.rs
- model/src/voice/voice_state.rs
Removed the `OptionalMemberDeserializer` that took an arbitrary guild_id before being replaced with the proper one, if available.
Also now correctly skips optional `Reaction` fields on serialization.
> refactor(model): rework optional member deserialization

- gateway-queue/Cargo.toml
- gateway-queue/src/lib.rs
- gateway/Cargo.toml
- twilight/Cargo.toml
`LargeBotQueue` requires a `Client` from `twilight-http`, meaning that users have to also depend on `twilight-http`. It makes more sense for them to specify their TLS requirements there, instead of also in `gateway-queue`.
Also fixes the README, which errorously mentions the non existant `twilight-http` feature.
This PR finally fixes all errors to `gateway-queue` introduced in #1690
Closes #1514 as gateway TLS support no longer pulls in `twilight-http`
> refactor(gateway-queue)!: drop TLS features

- gateway/src/cluster/builder.rs
- gateway/src/shard/builder.rs
- model/src/id/mod.rs
This attribute sets the panic info location to the caller's location, see https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#useful-line-numbers-in-option-and-result-panic-messages for more information.
> feat: set `#[track_caller]` on public panicable functions

- cache/in-memory/src/event/message.rs
- cache/in-memory/src/iter.rs
- cache/in-memory/src/lib.rs
This type is stable, so exposing it is fine.
> feat(cache)!: expose `VecDequeue` from `channel_messages`

- cache/in-memory/src/model/guild.rs
- model/src/guild/feature.rs
- model/src/guild/mod.rs
- model/src/guild/partial_guild.rs
Eases matching on guilds' features and removes some heap allocations at cost of `GuildFeature` being 32 bytes vs `String`'s 24.
> feat(model)!: add `GuildFeature`

- cache/in-memory/src/event/reaction.rs
- cache/in-memory/src/test.rs
Compares emoji IDs if the emojis are custom or emoji names if they're unicode instead of comparing every field of the emoji
> fix(cache): compare reaction emojis by resource instead of object

- .github/workflows/check.yml
- .github/workflows/deploy-lib.yml
- CONTRIBUTING.md
- book/tests/Cargo.toml
- cache/in-memory/Cargo.toml
- cliff.toml
- embed-builder/Cargo.toml
- gateway-queue/Cargo.toml
- gateway/Cargo.toml
- gen-changelogs.sh
- http/Cargo.toml
- lavalink/Cargo.toml
- mention/Cargo.toml
- release.sh
- release.toml
- standby/Cargo.toml
- twilight/Cargo.toml
- util/Cargo.toml
- validate/Cargo.toml
This PR configures steps to automate patch releases using `git-cliff` (`cliff.toml`, `gen-changelogs.sh`) and `cargo-release` (`release.toml`, `release.sh`). In order to achieve this, it also does the following:
- rename `twilight-book` to `book`
- add crate's version to all `Cargo.toml` files alongside its path, so cargo-release can automatically increment it
- add instructions to `CONTRIBUTING.md`
This is currently untested, but I'm pretty sure it works. I would like more sets of eyes on it before I run it for real.
> build: release automation

- gateway/src/event.rs
- model/src/gateway/intents.rs
Syncs [Discord's docs on intents](https://discord.com/developers/docs/topics/gateway#gateway-intents) with Twilight's and adds the documented events to `EventTypeFlags` constants for intents
> fix(gateway): Add missing received events per intent

- util/src/builder/embed/author.rs
Already set in `new`, aligns with other builders
> refactor(util)!: remove `EmbedAuthorBuilder::name`

- model/src/channel/mod.rs
Change the type of channel's message_count to u64 to allow for larger integers, since Discord is starting to track more detailed counts. I've recently been receiving integers much larger than 50, such that a u8 would not suffice. This is currently not documented, however, I have clarified with a Discord staff and it is the intended behaviour.
> fix(model): fix thread max message count

- model/src/gateway/payload/incoming/thread_members_update.rs
Modify `ThreadMembersUpdate::member_count` to be a larger signed integer - i32 - rather than a u8. The member count can be -1, and because thread message counts can be larger than 50 now we should increase this field to be safe as well.
> fix(model): signed thread member update count

- lavalink/src/client.rs
- lavalink/src/node.rs
> refactor(lavalink)!: remove obsolete `Num-Shards` header

- twilight-model/src/channel/mod.rs
- twilight-model/src/template/mod.rs
Today Discord has been sending `"user_limit": 10000`. Currently this is stored in a u8 which means deserialization breaks.
> fix(model): bump user_limit from u8 to u32

- twilight-http/src/client/mod.rs
- twilight-http/src/request/user/create_private_channel.rs
This method is incorrectly documented, threw me off for a moment.
> docs(http): fix create_private_channel description

- .github/workflows/book.yml
According to the [action's docs], `workingDirectory` is camel cased and belongs in the `with` section.
[action's docs]: https://github.com/cloudflare/wrangler-action#configuration
> ci(book): use camelCase for workingDirectory

- twilight-model/src/application/command/mod.rs
- twilight-model/src/application/command/option.rs
- twilight-model/src/application/interaction/application_command/mod.rs
- twilight-model/src/application/interaction/application_command/option.rs
- twilight-model/src/application/interaction/mod.rs
- twilight-model/src/gateway/event/dispatch.rs
- twilight-model/src/gateway/event/mod.rs
- twilight-model/src/gateway/payload/incoming/interaction_create.rs
- twilight-model/src/http/interaction.rs
- twilight-util/src/builder/command.rs
Deriving `Eq` for `Number` in it's current implementation is just plain wrong. As `Eq` is not necessary for these types this is fine. `Eq` is mostly for `HashMap` keys, which is not a usecase for any of these types.
Why not fix `Number` so that it's `Eq` and `Hash` implementation is correct?
Because floating point numbers are notoriously hard to deal with.
> refactor(model)!: remove `Number`

- .github/workflows/check.yml
- .github/workflows/deploy-lib.yml
`actions-rs` is now unmaintained.
> ci: use `dtolnay/rust-toolchain` over `actions-rs`

- twilight-model/src/application/command/mod.rs
- `dm_permission` no longer nullable
- `default_member_permissions` no longer optional
Closes #1843.
> refactor(model): command field changes

- .github/workflows/book.yml
- book/book.toml
Setting the `theme` option searches for a directory. Only the `default-theme` option is needed.
> ci(book): fix build

- twilight-model/src/gateway/event/dispatch.rs
- twilight-model/src/gateway/event/mod.rs
Variant was added to `Event`, but not to `DispatchEvent`, which prevented it from being deserializable.
> fix(model): deserialize `Event::GuildStickersUpdate`

- Cargo.toml
The default for normal crates as of the Rust 2021 edition, it's not enabled by default for workspaces. Version 2 of the feature resolver improves intercrate shared dependency feature resolution. See https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2 for more info.
> build: use version 2 of the feature resolver

- twilight-http-ratelimiting/src/request.rs
Fixes an issue brought up in [our support channel] where this path wasn't accounted for.
[our support channel]: https://discord.com/channels/745809834183753828/1014172376595955812
> fix(http-ratelimiting): `/channels/id/thread-members/id` parsing

- twilight-http/src/request/application/interaction/create_followup.rs
- twilight-http/src/request/application/interaction/update_followup.rs
- twilight-http/src/request/application/interaction/update_response.rs
- twilight-http/src/request/channel/message/create_message.rs
- twilight-http/src/request/channel/message/update_message.rs
- twilight-http/src/request/channel/webhook/execute_webhook.rs
- twilight-http/src/request/channel/webhook/update_webhook_message.rs
- twilight-validate/src/message.rs
Also adds a function to validate attachments.
Reference: https://github.com/discord/discord-api-docs/pull/5233
Closes: #1889
> feat!(http,validate): validate attachment descriptions

- twilight-gateway/README.md
- twilight-gateway/src/stream.rs
Previously, if a shard within a stream encountered any error, not just a failure, it would never re-insert back into the futures list because it never executed its drop implementation. This change always returns the shard when polling `ShardEventStream` or `ShardMessageStream`, regardless of if an error occurred, which ensures it is re-inserted.
Co-authored-by: Zeyla Hellyer <zeyla@hellyer.dev>
> fix(gateway)!: within a stream, reinsert shard on error

- twilight-gateway/src/shard.rs
`shard.status().[anything]` did not work previously as all `ConnectionStatus` methods took owned self, meanwhile `shard.status()` returns `&ConnectionStatus`.
> fix(gateway)!: `ConnectionStatus` methods borrow

- twilight-gateway/src/cluster/impl.rs
- twilight-gateway/src/shard/builder.rs
- twilight-gateway/src/shard/config.rs
- twilight-gateway/src/shard/impl.rs
- twilight-gateway/src/shard/processor/impl.rs
- twilight-gateway/src/shard/processor/session.rs
- twilight-model/src/gateway/payload/incoming/ready.rs
- twilight-standby/src/lib.rs
This adds handling for the new `gateway_resume_url`, which is provided in the `READY` dispatch. Resuming should happen on that URL instead of the normal `wss://gateway.discord.gg`.
I tested this using `ClusterBuilder`:
```rs
let shards = ShardScheme::try_from((0..1, 1))?;
let (cluster, _) = ClusterBuilder::new(token.clone(), Intents::None)
.shard_scheme(shards)
.build()
.await?;
cluster.up().await;
tokio::time::sleep(Duration::from_secs(1)).await;
let hashmap = cluster.down_resumable();
let (cluster, _) = ClusterBuilder::new(token, Intents::None)
.shard_scheme(shards)
.resume_sessions(hashmap)
.build()
.await?;
cluster.up().await;
```
Reference: https://github.com/discord/discord-api-docs/pull/5282
> feat(gateway,model): Add handling for gateway resume url

- twilight-gateway-queue/src/large_bot_queue.rs
The term "buckets" here was not immediately obvious to me; I had to ask for clarification, so let's spell it out.
> docs(gateway-queue): clarify `buckets` for large bot queue

- twilight-model/src/channel/message/mention.rs
When `Mention.member` is none on the gateway, Discord doesn't send the actual value. 
Can be easily reproduced by replying to a message with a mention in it. The docs aren't clear on what the intended behaviour is though.
Raw gateway message: 
```json
{
"t": "MESSAGE_CREATE",
"s": 19,
"op": 0,
"d": {
"type": 19,
"tts": false,
"timestamp": "2022-09-10T13:05:21.238000 00:00",
"referenced_message": {
"webhook_id": "1013877314175647817",
"type": 0,
"tts": false,
"timestamp": "2022-09-10T12:41:39.145000 00:00",
"pinned": false,
"mentions": [{
"username": "Blue",
"public_flags": 131136,
"id": "357048939503026177",
"discriminator": "6405",
"avatar_decoration": null,
"avatar": "5cf4a0e3880cce33cf5dfda6f8e8c7b6"
}],
"mention_roles": [],
"mention_everyone": false,
"id": "1018139190577348638", …
```
> fix(model): don't serialize `Mention.member` if None

- twilight-http/src/request/guild/create_guild/builder.rs
- twilight-http/src/request/guild/role/create_role.rs
- twilight-http/src/request/guild/role/update_role.rs
- twilight-util/src/builder/embed/mod.rs
Embeds when you input color 0 it will actually give you a black embed
Also role colors [specify in the documentation](https://discord.com/developers/docs/topics/permissions#role-object-role-structure
) that 0 will be ignored so i also updated that
> docs(http,util): fix mention on how color works

- twilight-http/src/request/audit_reason.rs
- twilight-http/src/request/guild/update_guild_mfa.rs
Discord supports the `x-audit-log-reason` header for the update guild mfa endpoint.
Reference: https://github.com/discord/discord-api-docs/pull/5072
Closes: #1866
> feat(http): implement `AuditLogReason` for `UpdateGuildMfa`

- twilight-model/src/user/connection.rs
When the connection has a corresponding thrid party OAuth2 token `two_way_link` will be set to `true`.
Reference: https://github.com/discord/discord-api-docs/pull/5259
Closes: #1917
> feat(model): add `two_way_link` to `Connection`

- twilight-gateway/Cargo.toml
- twilight-gateway/README.md
- twilight-gateway/src/lib.rs
- twilight-gateway/src/stream.rs
Allows projects not using Discord's HTTP API to opt out of building `twilight_http`. Can be useful for gateway proxies.
HTTP allows the gateway to retrieve Discord's recommended shard count (exposed in the `twilight_gateway::stream::start_recommended` function).
The last commit in this PR ([fff53e1](https://github.com/twilight-rs/twilight/pull/1760/commits/fff53e17d06286afcae6b5d880bbecb495c31941)) makes the TLS features, combined with `twilight_http`, no build `twilight_http` with the same TLS variants. This allows projects requiring WSS but not HTTPS; HTTP could in this case be proxied by, for example, twilight-http-proxy.
> feat(gateway)!: turn `twilight_http` optional

- twilight-model/src/guild/feature.rs
Discord has added a new guild feature, which when enabled pauses all invites, preventing new users from joining.
Reference: https://github.com/discord/discord-api-docs/pull/5269
Closes: #1905
> feat(model): add `GuildFeature::InvitesDisabled`

- twilight-http/src/client/interaction.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/request/application/interaction/create_followup.rs
- twilight-http/src/request/application/interaction/update_followup.rs
- twilight-http/src/request/application/interaction/update_response.rs
- twilight-http/src/request/channel/message/create_message.rs
- twilight-http/src/request/channel/webhook/execute_webhook.rs
- twilight-http/src/request/channel/webhook/execute_webhook_and_wait.rs
- twilight-http/src/request/channel/webhook/update_webhook_message.rs
Discord now allows users to send messages which only contain components.
Reference: https://github.com/discord/discord-api-docs/pull/5435
Closes: #1902
> docs(http): document component only messages

- twilight-http/src/request/guild/update_guild.rs
Discord only allows the `COMMUNITY`, `DISCOVERABLE` and `INVITES_DISABLED` features to be edited manually.
Reference: https://github.com/discord/discord-api-docs/pull/5270
Closes: #1906
> docs(http): document mutable guild features

- twilight-model/src/guild/audit_log/event_type.rs
- twilight-model/src/guild/audit_log/mod.rs
- twilight-model/src/guild/audit_log/optional_entry_info.rs
Add `application_commands` to audit log.
Add `AutoModerationFlagToChannel` and `AutoModerationUserCommunicationDisabled` audit log event types.
Add `auto_moderation_rule_name` and `auto_moderation_rule_trigger_type` optional entry info.
Reference: https://github.com/twilight-rs/twilight/issues/1903
Closes: #1903
> feat(model)!: bring audit log up to date

- twilight-model/src/guild/integration.rs
Discord provides the scopes which the integration has been authorized for.
Reference: https://github.com/discord/discord-api-docs/pull/5311
Closes: #1914
> feat(model): add `scopes` to `GuildIntegration`

- twilight-model/src/gateway/event/gateway.rs
- twilight-model/src/gateway/event/mod.rs
Almost all incoming gateway events are dispatch events, so boxing the `GatewayEvent::Dispatch` variant, although it being the largest one, is unnecessary, especially since it's immediately unboxed when converted to the (user received) `Event` enum.
> perf(model)!: unbox `GatewayEvent::Dispatch`

- twilight-cache-inmemory/src/event/guild.rs
- twilight-cache-inmemory/src/permission.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/request/channel/thread/create_thread.rs
- twilight-http/src/request/channel/thread/create_thread_from_message.rs
- twilight-http/src/request/channel/thread/get_public_archived_threads.rs
- twilight-http/src/request/channel/thread/remove_thread_member.rs
- twilight-http/src/request/channel/update_channel.rs
- twilight-model/src/channel/channel_type.rs
- twilight-model/src/channel/mod.rs
- twilight-util/src/permission_calculator/mod.rs
- twilight-validate/src/channel.rs
Discord has renamed a few channel types:
- `GuildNews` => `GuildAnnouncement`
- `GuildNewsThread` => `GuildAnnouncementThread`
- `GuildPublicThread` => `PublicThread`
- `GuildPrivateThread` => `PrivateThread`
Reference: https://github.com/discord/discord-api-docs/pull/5322
Closes: #1908
> refactor(cache/inmemory,http,model,util,validate)!: update `ChannelType` names

- twilight-gateway/src/shard/impl.rs
Add the gateway URL to the shard information since it is no longer static.
> feat(gateway): Add gateway url to the shard information

- twilight-gateway/src/event.rs
- twilight-gateway/src/json.rs
- twilight-gateway/src/shard.rs
The gateway refactor forgot about this important optimization. It's reimplemented it as an additional loop inside of `next_event` (loop again if the event is unwanted).
> fix(gateway): respect `EventTypeFlags`

- twilight-gateway/src/connection.rs
- twilight-gateway/src/tls.rs
As the `WebSocketConfig` parameter is always provided, it's confusing to pass it inside of an `Option`.
> refactor(gateway): don't pass `WEBSOCKET_CONFIG` in an `Option`

- twilight-gateway/src/error.rs
- twilight-gateway/src/shard.rs
Simplifies the `ConnectionStatus::from_close_frame` method and corrects its documentation.
Changed `ConnectionStatus::FatallyClosed` to contain a `CloseCode`, as unknown ones are not considered fatal.
> refactor(gateway)!: simplify `ConnectionStatus::from_close_frame`

- twilight-gateway/src/channel.rs
- twilight-gateway/src/command.rs
- twilight-gateway/src/shard.rs
- twilight-model/src/gateway/payload/outgoing/heartbeat.rs
#1934 accidentally assumed that the heartbeat sequence is known when heartbeating starts.
`Shards` will now send `null` as the heartbeat sequence until they receives their first sequence in the `Ready` event.
`Shard`s would before #1934 and this PR not send Heartbeats *at all* until it had received a `Ready` event (after identifying).
`Heartbeat`'s sequence is now optional.
> fix(gateway)!: heartbeat with a `null` sequence until a session is initialized

- twilight-gateway/src/shard.rs
The `resume_gateway_url` is recieved in `Ready` events, but should not be re-used if reconnecting to this URL fails or if the `Shard`'s session was invalidated.
See https://discord.com/developers/docs/topics/gateway
> fix(gateway): reset `resume_gateway_url` on reconnect failure and invalidated sessions

- twilight-gateway/src/latency.rs
* Clarifies `Latency::received`'s behaviour to no longer sound like it'll always be `Some` after having received the first heartbeat ACK.
* Fixes `Latency::recent` documenting the reverse order
* Replace "duration of the session" with "lifetime of the shard" as there's no connection to `Session`
* Document how latencies are calculated
> docs(gateway): redo and clarify `Latency` docs

- twilight-gateway/src/json.rs
- twilight-gateway/src/shard.rs
- twilight-model/src/gateway/event/gateway.rs
- twilight-model/src/gateway/opcode.rs
* Renames `OpCode::Event` to `OpCode::Dispatch`
* Replaces the `TryFrom<u8>` impl with a `from(u8) -> Option<Self>` method
* Removes the deprecated and undocumented `OpCode::VoiceServerPing` variant
* Extends the `OpCode` documentation
> refactor(model)!: redo `gateway::OpCode`

- twilight-gateway/Cargo.toml
- twilight-gateway/src/future.rs
To spread out server load, Discord wants gateway users to randomize the initial heartbeat event time.
See https://discord.com/developers/docs/topics/gateway#heartbeat-interval
> feat(gateway): heartbeat jitter

- twilight-gateway/src/config.rs
- twilight-gateway/src/shard.rs
The official docs on the effects of `shard_id` and `num_shards` is terrible, so this PR adds a lot of documentation to `ShardId` explaining its nuances.
> docs(gateway): touch up `ShardId` and add section about receiving events

- twilight-gateway/Cargo.toml
- twilight-gateway/src/future.rs
- twilight-gateway/src/shard.rs
Replaces the `TickHeartbeatFuture` future with tokio's `Interval` that does the same thing.
The tokio `Interval` struct does not require pinnig to be polled and also keeps the `Sleep` around instead of recreating it on every call to `NextMessageFuture`, which can be called hundred times per second depending on the load of the shard.
Supersedes #1900
> perf(gateway): use `tokio::time::Interval` for heartbeating

- twilight-http/src/client/mod.rs
- twilight-http/src/request/scheduled_event/create_guild_scheduled_event/mod.rs
Previously, the request builder would fail to add a value for `privacy_level` at all. This ensures that it is set in the first place.
Fixes #1960.
This request could be further refactored to include `name` in the initial builder call, but that's for another pr.
> fix(http)!: require privacy_level in `CreateGuildScheduledEvent`

- twilight-gateway/src/latency.rs
- twilight-gateway/src/shard.rs
I encountered this panic during normal operation:
```
2022-10-21T15:29:41.171756Z DEBUG shard{id=[0, 1]}: twilight_gateway::shard: sending heartbeat sequence=Some(11)
2022-10-21T15:29:41.284294Z DEBUG shard{id=[0, 1]}: twilight_gateway::shard: received heartbeat ack
2022-10-21T15:30:22.421292Z DEBUG shard{id=[0, 1]}: twilight_gateway::shard: sending heartbeat sequence=Some(11)
2022-10-21T15:30:27.519472Z DEBUG shard{id=[0, 1]}: twilight_gateway::shard: received websocket close message
2022-10-21T15:30:28.521889Z DEBUG shard{id=[0, 1]}:connect: twilight_gateway::connection: shaking hands with remote url="wss://gateway-us-east1-c.discord.gg/?v=10&encoding=json&compress=zlib-stream"
2022-10-21T15:30:28.691873Z DEBUG shard{id=[0, 1]}:connect: tungstenite::handshake::client: Client handshake …
```
> fix(gateway): don't panic on zombied connection

- book/tests/Cargo.toml
- twilight-cache-inmemory/Cargo.toml
- twilight-gateway-queue/Cargo.toml
- twilight-gateway/Cargo.toml
- twilight-http-ratelimiting/Cargo.toml
- twilight-http/Cargo.toml
- twilight-lavalink/Cargo.toml
- twilight-mention/Cargo.toml
- twilight-model/Cargo.toml
- twilight-standby/Cargo.toml
- twilight-util/Cargo.toml
- twilight-validate/Cargo.toml
- twilight/Cargo.toml
Specifying default manifest values[^1] is confusing as they're usually only specified when the default is overwritten.
Removes default manifest values from all `Cargo.toml` files.
[^1]: https://doc.rust-lang.org/cargo/reference/manifest.html
> build: remove keys with default value

- twilight-gateway/src/latency.rs
`Latency::recent` slices the entire `recent` field (initialized as `[Duration::ZERO; Self::RECENT_LEN]`), but since latencies are never 0 it should instead only slice "real" latencies and not expose this implementation detail.
> feat(gateway): `Latency::recent` filter zero

- twilight-gateway/src/ratelimiter.rs
- twilight-gateway/src/shard.rs
This PR aims to clean up documentation leftovers from before #1947 and contains also contains a lot of touch ups. Most importantly it removes all mentions of an interval on public methods (as it's unclear what the interval is).
> docs(gateway): ratelimiter hygiene & don't mention internals

- twilight-model/src/channel/forum.rs
Fixes #1977 by flattening `DefaultReaction` and `ForumTag` and documenting invariants, as they would otherwise need custom deserializers and serializers.
Also fixes `DefaultReaction`'s fields to now be public.
> fix(model)!: flatten `DefaultReaction` and `ForumTag`

- examples/lavalink-basic-bot.rs
In `.split_once()` examples:
```
assert_eq!("cfg".split_once('='), None);
assert_eq!("cfg=foo".split_once('='), Some(("cfg", "foo")));
```
so
`!join *anything*` → works
`!join` → matches to default
> docs(lavalink): minor fix in example

- twilight-cache-inmemory/src/event/voice_state.rs
- twilight-http/src/request/guild/create_guild/builder.rs
- twilight-http/src/request/guild/get_guild_prune_count.rs
This was somehow missed in the previous Rust 1.65 Clippy fix PR (#1985).
> fix: clippy 1.65 lints round 2

- README.md
- book/src/overview.md
I have added for the book `Intents::MESSAGE_CONTENT` that the example can work as well
> docs: add `Intents::MESSAGE_CONTENT` to examples

- twilight-model/src/user/premium_type.rs
This makes the size 2 bytes instead of 1, but it makes it less likely to cause issues with serialization.
--------------------------------
Add unknown variant to [`PremiumType`], this is a slight breaking change as the type is no longer `repr(u8)` which means conversions with the `as` keyword is no longer possible. Instead `Into` and `From` should be used instead. ([#1996])
[`PremiumType`]: https://docs.rs/twilight-model/latest/twilight_model/user/enum.PremiumType.html
[#1996]: https://github.com/twilight-rs/twilight/pull/1996
> fix(model)!: add a unknown variant to `PremiumType`

- twilight-gateway/src/shard.rs
Fixes the following issue happening:
```terminal
2022-10-29T17:42:05.858258Z DEBUG shard{id=[47, 50]}: twilight_gateway::shard: sending heartbeat sequence=Some(1)
2022-10-29T17:42:05.968093Z DEBUG shard{id=[47, 50]}: twilight_gateway::shard: received heartbeat ack
...
2022-10-29T17:42:46.117107Z DEBUG shard{id=[47, 50]}: twilight_gateway::shard: received reconnect
2022-10-29T17:42:47.118972Z DEBUG shard{id=[47, 50]}:connect: twilight_gateway::connection: shaking hands with gateway url="wss://gateway-us-east1-b.discord.gg/?v=10&encoding=json&compress=zlib-stream"
2022-10-29T17:42:47.522472Z DEBUG shard{id=[47, 50]}:connect: tungstenite::handshake::client: Client handshake done.
2022-10-29T17:42:47.522573Z DEBUG shard{id=[47, 50]}: twilight_gateway::shard: sending heartbeat sequence=Some(1) …
```
> fix(gateway): reset `heartbeat_interval` on disconnect

- twilight-gateway/src/shard.rs
Ratelimiter depends upon the received `heartbeat_interval` in Hello, so it should be reset when disconnecting.
Related to #1974
> fix(gateway): reset ratelimiter on disconnect

- examples/gateway-reshard.rs
- twilight-gateway/README.md
- twilight-gateway/src/config.rs
- twilight-gateway/src/stream.rs
Renames the `start_` functions in the `stream` module to `create_` to better reflect the fact that shards are only "started" when `next_message` is called on them. Additionally, `start_cluster` is renamed to `create_bucket` to better align with the previous `ShardScheme::Bucket` naming and now has an associated example. Also documents the fact that a shared session queue is *not* set by default; users must specify it in the `Fn(ShardId) -> Config` cluster.
> docs(gateway)!: touch up `stream` and rename `start_` fns -> `create_`

- twilight-model/src/application/interaction/mod.rs
This makes it a lot easier to get user information about the interaction author. For instance, my current bot has this function to get the `Username#Discriminator` tag of a user:
```rs
fn get_tag(event: &Interaction) -> String {
event
.user
.as_ref()
.or(event.member.as_ref().and_then(|m| m.user.as_ref()))
.map(|user| format!("{}#{}", user.name, user.discriminator()))
.expect("Could not resolve user for event!")
}
```
With this new method, I can do this much simpler:
```rs
fn get_tag(event: &Interaction) -> String {
event
.author()
.map(|user| format!("{}#{}", user.name, user.discriminator()))
.expect("Could not resolve user for event!")
}
```
> feat(model): Add Interaction::author

- twilight-model/src/guild/role_tags.rs
- twilight-model/src/visitor.rs
Abstract the `RoleTags::premium_subscriber` null boolean visitor to the visitor module. Work is being done on adding a new field that functions exactly like `RoleTags::premium_subscriber`, where a missing field means false and a null value means true. It's best to abstract the visitor built for the field so it can be re-used elsewhere.
> refactor(model): abstract null boolean visitor

- twilight-model/src/guild/role_tags.rs
The tests used for Role Tags weren't sets of role tags one would find in the real world. In particular, the test for "all" role tag fields can't happen because bots can't be premium subscribers. To fix this there are now three tests: one for bots, one for premium subscribers, and one for no role tags.
> test(model): add real-world role tag tests

- twilight-model/src/user/premium_type.rs
Add the `NitroBasic` variant to the `PremiumType` enum.
API docs PR: https://github.com/discord/discord-api-docs/pull/5568
> feat(model): add nitro basic user premium type

- twilight-model/src/guild/feature.rs
Add the `DeveloperSupportServer` variant to `GuildFeature`, which maps to the value "DEVELOPER_SUPPORT_SERVER".
API docs PR: https://github.com/discord/discord-api-docs/pull/5572
> feat(model): add dev support server guild feature

- twilight-cache-inmemory/src/event/guild.rs
- twilight-cache-inmemory/src/model/guild.rs
- twilight-cache-inmemory/src/permission.rs
- twilight-cache-inmemory/src/test.rs
- twilight-http/src/request/guild/create_guild/mod.rs
- twilight-model/src/guild/afk_timeout.rs
- twilight-model/src/guild/mod.rs
- twilight-model/src/guild/partial_guild.rs
- twilight-model/src/guild/template/guild.rs
- twilight-model/src/guild/template/mod.rs
The AFK timeout of a guild has been represented as an integer, despite the fact that the AFK timeout of a guild can only be a select list of integers rather than a freeform value. To achieve a nice UX while maintaining the representation of an integer, a newtype over an integer with associated constants for known valid values has been introduced.
Example:
```rust
use twilight_model::guild::AfkTimeout;
assert_eq!(300, AfkTimeout::FIVE_MINUETES.get());
assert_eq!(300, AfkTimeout::FIVE_MINUTES); // impl PartialEq<AfkTimeout> for u16
```
Reference: https://github.com/twilight-rs/twilight/issues/1904
Closes: #1904
> feat(cache,http,model)!: add `AfkTimeout` for `Guild::afk_timeout`

- twilight-gateway/src/error.rs
- twilight-gateway/src/future.rs
- twilight-gateway/src/shard.rs
Instead of shards transparently reconnecting they should send out a close message and only reconnect after the gateway drops the connection, which it does after having first sent out a close message reply. Users are then notified of the shard disconnecting/reconnecting and can handle it as they whish (this was previously achieved through `ShardEvent::Disconnected`).
To achieve I had to add a new `Io` `ReceiveMessageErrorType` variant (Tungstenite disconnects on errors) which sadly reintroduces #1428, hence the awkward workaround for it. I plan to land a propper fix in tokio-rustls after which the workaround can be dropped.
> feat(gateway): notify on disconnect

- twilight-gateway/src/json.rs
- twilight-gateway/src/shard.rs
- twilight-model/src/gateway/event/gateway.rs
- twilight-model/src/gateway/event/mod.rs
Unifies the awkward `GatewayEventDeserializerOwned` into `GatewayEventDeserializer` by using a `Cow` for the event type.
> reafactor(model)!: unify event deserialization into one type

- twilight-model/src/channel/message/kind.rs
Add methods on `MessageType` to determine whether the message can be deleted, as some messages can't be deleted even by server administrators. This uses [the table present on the documentation](https://discord.com/developers/docs/resources/channel#message-object-message-types) for message types. Because this information is documented, we should expose it. Some message types can only be deleted by people with certain documented permissions, which at the moment is only `AUTO_MODERATION_ACTION` which requires the `MANAGE_MESSAGES` permission.
Included are two methods: `deletable` which doesn't check against a set of permissions, and `deletable_by_permissions` which *does* check against a set of permissions. Tests are included (and simplified along with the rest of the tests).
Example: …
> feat(model): message type deletable check methods

- twilight-model/src/guild/integration.rs
- twilight-model/src/oauth/install_params.rs
- twilight-model/src/oauth/mod.rs
- twilight-model/src/oauth/scope.rs
Adds constants for scope values to a new module,
`twilight_model::oauth::scope`. A sample constant is `IDENTIFY`, which maps to the `"identify"` value.
> feat(model): constants for scope values

- twilight-model/src/guild/invite/guild.rs
- twilight-model/src/guild/invite/mod.rs
Use the `GuildFeature` type for the `InviteGuild`'s list of features instead of Strings. This aligns `InviteGuild` with `Guild` and `PartialGuild`.
> fix!(model): use typed features for guild invite

- examples/gateway-parallel.rs
- twilight-cache-inmemory/src/lib.rs
- twilight-gateway/src/event.rs
- twilight-gateway/src/lib.rs
- twilight-gateway/src/message.rs
- twilight-gateway/src/shard.rs
- twilight-model/src/gateway/event/kind.rs
- twilight-model/src/gateway/event/mod.rs
- twilight-model/src/gateway/frame.rs
- twilight-model/src/gateway/mod.rs
Adds a sought after equivalent of `Message::Close` to the `Event` enum, avoiding users having to reimplement `Shard::next_event` themselves just for handling closes.
The `CloseFrame`'s fields are now public and it's no longer marked as non-exhaustive.
> feat(gateway)!: add `Event::GatewayClose` variant

- twilight-gateway/Cargo.toml
The RC's [build failed], so this is the workaround I can think of. 
[build failed]: https://docs.rs/crate/twilight-gateway/0.15.0-rc.1/builds/716646
> docs(gateway): don't build all features on docs.rs

- twilight-gateway/src/json.rs
Most events entering `parse` are thrown out due to users' `EventTypeFlags` not wanting them. This PR tries to optimize this path by deferring the creation of the deserializer until the `EventTypeFlags` check.
Moved out of #2024
> perf(gateway): defer creating `Deserializer` until checking event is wanted

- twilight-gateway/src/json.rs
- twilight-gateway/src/lib.rs
- twilight-gateway/src/shard.rs
A crucial component of custom gateways is the logic in this function, so we should expose it.
> feat(gateway): expose `json::parse`

- twilight-http/src/request/channel/webhook/update_webhook_message.rs
Aligns the return value with the one [documented](https://discord.com/developers/docs/resources/webhook#edit-webhook-message).
Closes #2052
> fix(http): return `Message` from `UpdateWebhookMessage`

- twilight-http-ratelimiting/src/request.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/request/get_current_authorization_information.rs
- twilight-http/src/request/mod.rs
- twilight-http/src/request/try_into_request.rs
- twilight-http/src/routing.rs
- twilight-model/src/oauth/current_authorization_information.rs
- twilight-model/src/oauth/mod.rs
Add support for the "Get Current Authorization Information" route, at the endpoint `GET /oauth2/@me`. This endpoint takes a client with a bearer token and fetches the application, when the access token expires, the authorized scopes, and the user that authorized the access token if applicable.
Manually tested using the written example:
```
stdout:
Application: kona
User: team959818497288982639
```
Closes #1643.
> feat(http, model): get current authorization route

- twilight-model/src/channel/message/sticker/format_type.rs
Add support for the `Gif` sticker format type, represented as value 4.
Closes #2057.
> feat(model): gif sticker format type

- twilight-http/src/error.rs
Manually implement Debug for `twilight_http::error::ErrorType`, providing custom implementations for some error types that contain HTTP body bytes so they can be converted to strings.
Old debug message (reformatted for PR readability):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
source: None,
kind: Response {
body: [
123, 34, 99, 111, 100, 101, 34, 58, 32, 53, 48, 48, 51, 53, 44, 32,
34, 101, 114, 114, 111, 114, 115, 34, 58, 32, 123, 34, 111, 112,
116, 105, 111, 110, 115, 34, 58, 32, 123, 34, 49, 34, 58, 32, 123,
34, 95, 101, 114, 114, 111, 114, 115, 34, 58, 32, 91, 123, 34, 99,
111, 100, 101, 34, 58, 32, 34, 65, 80, 80, 76, 73, 67, 65, 84, 73,
79, 78, 95, 67, 79, 77, 77, 65, 78, 68, 95, 79, 80, 84, 73, 79, 78,
83, 95, 78, 65, 77, 69, 95, 73, 78, …
```
> refactor(http): human legible error debug bodies

- twilight-validate/src/command.rs
This is an issue i ran into, and was mildly inconvenienced by. It could be done in a more compartmentalized way, but it would be a breaking change and wouldn't really create any illumination.
> fix(validate): properly validate context menu commands

- twilight-model/src/gateway/presence/activity.rs
- twilight-model/src/gateway/presence/activity_timestamps.rs
Document that the integer values of `Activity::created_at` and `ActivityTimestamps`' `end` and `start` fields are the Unix timestamp in milliseconds.
Closes #1958.
> docs(model): activity timestamp integer values

- twilight-http/src/client/interaction.rs
- twilight-http/src/request/application/command/update_command_permissions.rs
Add documentation on `InteractionClient::update_command_permissions` and `UpdateCommandPermissions` that an OAuth Bearer token is required to use the endpoint.
Closes #1740.
> docs(http): updating command perms requires oauth

- twilight-model/src/channel/mod.rs
Thread channels that haven't been updated in a while can have negative member counts, so we need to make `Channel::member_count` signed so channels and guilds correctly deserialize.
> fix(model): signed channel member counts

- examples/gateway-metrics.rs
- examples/gateway-shard.rs
- twilight-cache-inmemory/src/lib.rs
- twilight-gateway/src/cluster/mod.rs
- twilight-gateway/src/event.rs
- twilight-model/src/gateway/event/dispatch.rs
- twilight-model/src/gateway/event/kind.rs
- twilight-model/src/gateway/event/mod.rs
- twilight-model/src/gateway/intents.rs
- twilight-model/src/gateway/payload/incoming/guild_audit_log_entry_create.rs
- twilight-model/src/gateway/payload/incoming/mod.rs
- twilight-model/src/guild/audit_log/entry.rs
This patch also deprecates the `GUILD_BANS` intent in favour of the `GUILD_MODERATION` intent.
This will be marked as draft until the API docs PR is merged.
Note that currently the event needs the `GUILDS` intent though this will change soon.
Closes #2066
> feat!(model, gateway): Support the GUILD_AUDIT_LOG_ENTRY_CREATE gateway event

- twilight-http/src/routing.rs
This fixes some clippy errors that seem to have been introduced in the latest rust updates.
> fix(http): resolve new clippy lints

- twilight-http/src/request/guild/auto_moderation/create_auto_moderation_rule.rs
Fix the name of the CreateAutoModerationRule field body's `type` field from `kind` by putting a `#[serde(rename = "type")]` on it.
API docs:
<https://discord.com/developers/docs/resources/auto-moderation#auto-moderation-action-object-auto-moderation-action-structure>
Closes #2092.
> fix(http): create auto moderation type field name

- twilight-gateway/src/latency.rs
- twilight-gateway/src/shard.rs
Redoes a lot of documentation to be more consistent and clearer. Also extends the testing of `Latency::record_received`.
Breaking change: renames `Latency::heartbeats` to `Latency::periods`.
> refactor(gateway)!: touch up `Latency`

- twilight-gateway/src/event.rs
Fixes the broken [`EventTypeFlags`](https://docs.rs/twilight-gateway/0.15.0-rc.2/twilight_gateway/struct.EventTypeFlags.html) intralinks and rewords the docs to be slightly more consice.
Moved out of #2024
> docs(gateway): fix `EventTypeFlags` links

- twilight-http/src/request/channel/update_channel.rs
- twilight-validate/src/channel.rs
Validate channel `user_limit` fields on `UpdateChannel` and `CreateGuildChannel`, introducing a new `user_limit` function in `twilight_validate::channel`.
Part of #1477.
> feat(http, validate)!: channel user limits

- twilight-http/src/client/mod.rs
- twilight-http/src/request/channel/message/delete_messages.rs
- twilight-validate/src/channel.rs
Validate bulk message delete counts by introducing a new `bulk_delete_messages` in `twilight_validate::channel`.
Part of #1477.
> feat(http, validate)!: bulk delete message count

- examples/gateway-parallel.rs
- examples/gateway-reshard.rs
- twilight-gateway/README.md
- twilight-gateway/src/config.rs
- twilight-gateway/src/stream.rs
Instead of removing these functions entirely, accept a primary `Config`, which is then subsequently optionally modified in the callback. The default config creates the default queue, which is then cloned and re-built before it passed to each shard. It also re-uses the TLS container.
Alternative to #2090.
> refactor(gateway)!: reuse queue by default in `create_*` functions

- twilight-gateway/README.md
- twilight-gateway/src/config.rs
- twilight-gateway/src/connection.rs
- twilight-gateway/src/shard.rs
- twilight-gateway/src/stream.rs
Adds important details to the primary examples. Also extends some details about `Config` and TLS context reuse, `Shard::sender` and the gateway identify queue.
> docs(gateway): add helpful details for new users

- twilight-http/src/request/channel/message/create_message.rs
- twilight-http/src/request/channel/thread/create_forum_thread/message.rs
- twilight-model/src/channel/message/flags.rs
Adds support for `@silent` messages via the `SUPPRESS_NOTIFICATIONS` flag. 
Closes #2137.
> feat(model): add `MessageFlags::SUPPRESS_NOTIFICATIONS`

- twilight-gateway/src/shard.rs
Should've been included in #2107
> docs(gateway): remove stale resume_gateway_url notice

- twilight-gateway/src/config.rs
Document that configured shard presences are maintained across gateway reconnections when a shard can be successfully resumed, and that Twilight will automatically send the presence along with new gateway sessions.
Documentation added after a support thread was received in our Discord server:
<https://discord.com/channels/745809834183753828/1075593388503609516>
> docs(gateway): resume behavior of presences

- twilight-gateway/src/event.rs
Add a piece of documentation to `EventTypeFlags` to clarify that all events can be excluded from a selection of flags because shards will always parse portions of events necessary for maintaining gateway connections.
Documentation added after a support thread was received in our Discord server:
<https://discord.com/channels/745809834183753828/1075585618953908344>
> docs(gateway): all event types can be excluded

- .github/workflows/check.yml
- twilight-cache-inmemory/Cargo.toml
Twilight's CI cache regurarely exceeds the maximum provided 10GB storage by GitHub, discarding the oldest caches. The resulting cache misses increases our CI time and wastes GitHub's resources.
By inlining the min-vers CI job into MSRV we reduce it's risk of becoming stale (running dependant jobs quicker) as the dependencies are frozen and also remove an almost duplicate 300MB cache.
By excluding the book from the doctest CI no longer needs to recompile Twilight due to the book's dependencies and this should also reduce this job's cache size.
> ci: speedup & reduce cache storage

- book/tests/src/lib.rs
- twilight-cache-inmemory/src/lib.rs
- twilight-gateway-queue/src/lib.rs
- twilight-gateway/src/lib.rs
- twilight-http-ratelimiting/src/lib.rs
- twilight-http/src/lib.rs
- twilight-lavalink/src/lib.rs
- twilight-mention/src/lib.rs
- twilight-model/src/channel/message/mod.rs
- twilight-model/src/guild/auto_moderation/mod.rs
- twilight-model/src/lib.rs
- twilight-model/src/util/datetime/mod.rs
- twilight-model/src/voice/mod.rs
- twilight-standby/src/lib.rs
- twilight-util/src/lib.rs
- twilight-validate/src/lib.rs
Development of Twilight is somewhat tedious due to warning lints failing compilations of WIP changes. We should instead only fail builds once we submit them to a PR, i.e. fail in CI.
This PR removes the deny by default lints and warns on the remaining one's. Additionally I removed an uncessary allow by default `unused_underscore_binding` lint (useful when `tracing` was optional)
Suggested in https://github.com/twilight-rs/twilight/discussions/1644#discussioncomment-4583127
> refactor: change deny lints to warn

- .github/workflows/check.yml
Left out of #1722 due to the book being inlined after the fact.
> ci: bump book-test checkout workflow version

- twilight-model/src/gateway/opcode.rs
Documents and add methods for the sent/received categorization of `OpCode`.
Split out of #2024
> feat(model): gateway OpCode sent/received categorization

- twilight-model/src/user/current_user.rs
- twilight-model/src/user/mod.rs
- twilight-model/src/user/profile.rs
Add documentation to the `discriminator` field on user models that, because the discriminator is an integer, it's not acceptable for formatting such as in a user tag, and that the `discriminator` method which returns a formatter for just the use case is preferred.
> docs(model): formatting of discriminator field

- twilight-model/src/channel/message/reaction.rs
Clarify that the name of a unicode reaction type
(`ReactionType::Unicode`) is the *value* of the unicode emoji and not the Discord display name for the emoji. For example, instead of using a value of "arrow_right", a name of "➡️" must be specified.
Documentation added after a support thread was received in our Discord server:
<https://discord.com/channels/745809834183753828/1075631047871578153>
> docs(model): clarify reaction type unicode values

- twilight-model/src/gateway/close_code.rs
Simplify the implementation of `CloseCode::can_reconnect` to be a `matches!` statement instead of a `match` statement returning a boolean.
> refactor(model): simplify closecode::can_reconnect

- twilight-model/src/gateway/close_code.rs
Add tests for gateway close codes. This updates the existing test to use the new iterative test approach over known values, adds some trait asserts, and adds tests for `CloseCode::can_reconnect`.
> test(model): tests for gateway clode codes

- twilight-gateway/src/json.rs
- twilight-gateway/src/shard.rs
Ignore errors caused by attempting to parse payloads into events that are unknown to Twilight. Because these are unknown payload types, they couldn't possibly ever produce a parsed event, and therefore it's expected that they fail to deserialize. Because this isn't an *error* in the operation of the shard and is considered a normal operation in the event loop, we should skip over these errors from unknown events. Deserialization error variants can still occur from failing to deserialize *known* event types.
> fix(gateway): ignore unknown event errors

- twilight-http/src/request/guild/auto_moderation/create_auto_moderation_rule.rs
- twilight-model/src/guild/auto_moderation/action.rs
- twilight-model/src/guild/auto_moderation/mod.rs
- twilight-validate/src/request.rs
Add support for the new `custom_message` field available on AutoMod `BLOCK_MESSAGE` actions.
Discord API Docs:
https://github.com/discord/discord-api-docs/pull/5955
> feat(http, model, validate): add support for auto mod custom messages

- twilight-cache-inmemory/src/event/interaction.rs
Replace an instance of finding a HashMap value by key through an iterator with `HashMap::get`.
> perf(cache): replace hashmap .iter().find() with .get()

- twilight-model/src/gateway/event/mod.rs
Fix the documentation for `IntegrationDelete` and `IntegrationUpdate`, which said "A guild integration was updated" and "A guild integration was deleted", respectively, which is the inverse of what they actually are.
Closes issue #2167.
> docs(model): fix event integration variant docs

- twilight-http-ratelimiting/Cargo.toml
- twilight-http-ratelimiting/src/request.rs
- twilight-http/src/client/mod.rs
The `http` crate was exposed in `Method` for `twilight-http` to use when sending requests. Hyper (the underlying HTTP crate), however, accepts string representations of HTTP methods too, so this PR switches to using that instead.
Closes #1456
> feat(http-ratelimiting)!: hide `http` dependency

- book/src/chapter_1_crates/section_7_first_party/section_3_lavalink.md
- examples/lavalink-basic-bot.rs
- twilight-gateway-queue/src/day_limiter.rs
- twilight-gateway-queue/src/large_bot_queue.rs
- twilight-gateway-queue/src/lib.rs
- twilight-gateway/src/stream.rs
- twilight-lavalink/README.md
- twilight-lavalink/src/client.rs
- twilight-model/src/gateway/connection_info/bot_connection_info.rs
- twilight-model/src/gateway/id.rs
- twilight-model/src/gateway/payload/incoming/ready.rs
- twilight-model/src/gateway/session_start_limit.rs
Saves a bit of space, for example, no one is running more than 2^32 shards (in fact the largest bot runs about 10 times under 2^16).
This also happens to fix a bug in the `LargeBotQueue` implementation.
This is a prelude to the `vilgotf/feat/gateway-queue/rewrite` branch (which is essentially ready) where I've done a (mosltly documentation) rework of the gateway-queue crate.
> feat(model)!: reduce size of gateway REST API models

- twilight-gateway-queue/src/day_limiter.rs
This typo was moved out of #2168 to expedite it landing on `main` and subsequently being released to users.
> fix(gateway-queue): correctly update DayLimiter's next_reset field

- twilight-standby/README.md
- twilight-standby/src/lib.rs
Document how to use timeouts with Standby futures by using functions such as `tokio::time::timeout`.
Documentation added after a support thread was received in our Discord server:
<https://discord.com/channels/745809834183753828/1083498439964368966>
> docs(standby): timeout example

- twilight-http/src/request/guild/sticker/update_guild_sticker.rs
The `UpdateGuildSticker` request supports specifying a reason, but doesn't actually use it. This makes it use it when building the request.
Found in #2171.
> fix(http): use reason in update guild sticker

- twilight-model/src/util/image_hash.rs
Properly handle the Clyde AI avatar hash by special-casing the "clyde"
hash as a constant when parsing and serializing image hashes. Includes a
test.
Closes https://github.com/twilight-rs/twilight/issues/2177.
> fix(model): handle clyde ai hash

- twilight-gateway/Cargo.toml
- twilight-gateway/src/ratelimiter.rs
- twilight-gateway/src/shard.rs
In #2143, the ratelimiter's performance was increased due to removing the call to `Instant::now` when the instant queue is not full. This PR goes one step further and removes it for *all* spurious calls, where spurious equates to calling `poll_available` when the timer has not fired.
> perf(gateway): speed up spurious ratelimiter poll

- twilight-http/src/request/guild/update_current_member.rs
Field is documented as being both nullable and optional.
First reported in our Discord server's support forum <https://discord.com/channels/745809834183753828/1092061820610695258>
> fix(http): update current member nullable nick

- twilight-model/src/guild/permissions.rs
- twilight-util/src/permission_calculator/mod.rs
- twilight-util/src/permission_calculator/preset.rs
Adds:
- `USE_SOUNDBOARD` for the upcoming soundboard feature
- `MANAGE_GUILD_EXPRESSIONS`, renamed from `MANAGE_EMOJIS_AND_STICKERS` to now include editing soundboard sounds.
- `VIEW_CREATOR_MONETIZATION_ANALYTICS` for permissions on viewing subscription insights.
Ref:
- https://github.com/discord/discord-api-docs/pull/6017
> feat(model): Add new `USE_SOUNDBOARD`, `MANAGE_GUILD_EXPRESSIONS` and `VIEW_CREATOR_MONETIZATION_ANALYTICS` permissions

- twilight-gateway-queue/src/large_bot_queue.rs
- twilight-gateway-queue/src/lib.rs
- twilight-http/src/request/application/command/mod.rs
- twilight-model/src/id/mod.rs
allow clippy::let-underscore-untyped
> fix(gw-queue, http, model): Fix clippy up to 1.69.0

- twilight-cache-inmemory/src/event/interaction.rs
- twilight-model/src/application/interaction/mod.rs
- twilight-standby/src/lib.rs
This adds support for the new `channel` field sent in interactions. This is used in favor of `channel_id` which is deprecated and will be removed.
Ref:
- https://github.com/discord/discord-api-docs/pull/6051
> feat(model, cache): add `channel` field to `Interaction`

- twilight-model/src/application/interaction/application_command/option.rs
- twilight-model/src/application/interaction/mod.rs
Because of the way [`ValueEnvelope`](https://github.com/twilight-rs/twilight/blob/c5f75d950162dceb997a5544bb8c9b86e9e7bdc1/twilight-model/src/application/interaction/application_command/option.rs#L91) is declared it automatically puts a higher precedence on deserializing to an `Id` rather than a `String`. 
This behavior is desired because currently, the deserialization of option values doesn't take the `kind` of the option JSON into account. So if an option *actually is* a snowflake type it would be serialized as such instead of becoming a `String`. This, however, does not account for situations where the string is a parseable Id, but is supposed to be represented as a `String` regardless.
As a result, this PR removes `ValueEnvelope::Id`. This means that means we *initially* deserialize …
> fix(model): Don't deserialize option values as `Id`'s if option type is `String`

- twilight-cache-inmemory/src/model/message.rs
- twilight-model/src/application/interaction/application_command/resolved.rs
- twilight-model/src/channel/attachment.rs
- twilight-model/src/channel/message/flags.rs
- twilight-model/src/channel/message/mod.rs
- twilight-model/src/gateway/payload/incoming/message_create.rs
- twilight-model/src/gateway/payload/incoming/message_update.rs
- twilight-model/src/guild/permissions.rs
Adds the `waveform` and `duration_secs` to the `Attachment` structure. In addition, the new `SEND_VOICE_MESSAGES` permission has been added.
Ref:
- https://github.com/discord/discord-api-docs/pull/6082
> feat(model, cache): add support for voice messages

- twilight-gateway/Cargo.toml
- twilight-http/Cargo.toml
These versions seem to be API compatible with 0.7 (for our usage)
> build(gateway, http): Allow simd-json 0.8 and 0.9

- Cargo.toml
- README.md
- twilight-cache-inmemory/README.md
- twilight-cache-inmemory/src/event/member.rs
- twilight-cache-inmemory/src/event/reaction.rs
- twilight-cache-inmemory/src/event/voice_state.rs
- twilight-cache-inmemory/src/permission.rs
- twilight-gateway/README.md
- twilight-gateway/src/json.rs
- twilight-http-ratelimiting/src/in_memory/bucket.rs
- twilight-http/README.md
- twilight-lavalink/README.md
- twilight-lavalink/src/node.rs
- twilight-mention/README.md
- twilight-mention/src/parse/iter.rs
- twilight-model/README.md
- twilight-standby/README.md
- twilight-standby/src/lib.rs
- twilight-util/README.md
- twilight-validate/README.md
Bumps the MSRV from 1.64 to 1.67.
Utilizes `let else` statements whereever possible.
1.67 was chosen as it's the current stable - 2, which is not too recent but not too old. Specifically, it was necessary to bump the MSRV as our dependencies (in this case `time`) have a policy of supporting stable - 6 months (currently 1.65).
> build: bump MSRV to 1.67

- twilight-model/src/id/mod.rs
When deserializing JSON that has an ID as a number, not a string, this is required in order to deserialize it without erroring. Might be a `simd-json` quirk and work with `serde_json`, but still means this should be implemented.
Repro:
```rs
use twilight_model::id::{marker::GuildMarker, Id};
fn main() {
let mut input = String::from("1234567890");
let _id: Id<GuildMarker> = unsafe { simd_json::from_str(&mut input).unwrap() };
}
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { index: 0, character: None, error: Serde("invalid type: integer `1234567890`, expected a discord snowflake") }', src/main.rs:5:73
```
> model: Implement visit_i64 for IdVisitor

- twilight-gateway/Cargo.toml
- twilight-gateway/src/tls.rs
- twilight-http/Cargo.toml
- twilight-lavalink/Cargo.toml
PR goes to next because it is not advisable to have two different versions of `rustls` in the dependency tree and we shouldn't force it upon users in a patch release.
> build(gateway, http, lavalink): Dependency updates for rustls 0.21

- twilight-http/src/request/application/interaction/update_followup.rs
closes #2203
also silently fixes a small typo in `attachments's`
> fix(http)!: fix `UpdateFollowup` falsely returning an `EmptyBody` (#2203)

- twilight-validate/src/command.rs
This was apparently missed in a3f933a02675fd0126d121b4f399b70378bd134a.
> docs(validate): Fix broken intra-doc links

- twilight-cache-inmemory/src/event/interaction.rs
- twilight-cache-inmemory/src/event/member.rs
- twilight-cache-inmemory/src/model/member.rs
- twilight-model/src/application/interaction/application_command/mod.rs
- twilight-model/src/application/interaction/message_component.rs
- twilight-model/src/application/interaction/mod.rs
- twilight-model/src/application/interaction/resolved.rs
- twilight-model/src/channel/message/component/kind.rs
- twilight-model/src/channel/message/component/mod.rs
- twilight-model/src/channel/message/component/select_menu.rs
- twilight-standby/src/lib.rs
- twilight-validate/src/component.rs
This merge request implements Discord's new select menu types (user, role, mentionable, and channel) using the fully-flattened approach outlined in [this RFC](https://github.com/twilight-rs/twilight/discussions/2217).
The general idea is to implement all variant-specific fields as `Option`s inside the `SelectMenu` struct. While this might require runtime validation, it's more in line with the rest of the Twilight ecosystem. Moreover, it doesn't duplicate fields that an approach with separate structs would duplicate.
Notably, this differs from the RFC mentioned above. This RFC was indirectly denied with [this review](https://github.com/twilight-rs/twilight/pull/2219#pullrequestreview-1480445162).
This PR introduces multiple breaking changes:
- `ComponentType`'s `SelectMenu` variant was …
> feat(twilight-model)!: Implement additional select menu types

- twilight-gateway/src/json.rs
- twilight-mention/src/parse/iter.rs
rustfmt 1.6.0 just released with support for let-else statements.
> refactor: reformat code with rustfmt 1.6.0

- twilight-gateway/src/ratelimiter.rs
- twilight-gateway/src/shard.rs
This timer registration hack is slightly less horrible.
> refactor(gateway): remove ratelimiter sleep from new

- twilight-http/src/request/guild/create_guild_channel.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/5994
> feat(http): add `default_forum_layout` option for channel creation

- twilight-cache-inmemory/src/event/reaction.rs
- twilight-cache-inmemory/src/test.rs
- twilight-model/src/gateway/reaction.rs
- twilight-standby/src/lib.rs
Refs:
- https://github.com/discord/discord-api-docs/pull/6102
- https://github.com/discord/discord-api-docs/pull/6296
> feat(model, gateway): add `message_author_id` for reaction add events

- twilight-model/src/application/interaction/application_command/resolved.rs
- twilight-model/src/channel/attachment.rs
- twilight-model/src/channel/attachment_flags.rs
- twilight-model/src/channel/mod.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6272
> feat(model): add support for attachment flags

- .github/workflows/deploy-lib.yml
`-C target-cpu=native` causes illegal instructions when using actions cache due to Github Actions' wide range of CPU targets. `haswell` is the earliest target level with mandatory AVX2 and will work fine with everything more recent than that. This also matches our flags in other workflows.
> fix(ci): Target haswell for docs deploy

- twilight-gateway/src/error.rs
- twilight-gateway/src/shard.rs
Instead of trying to respond inside of `process`, where errors result in users not receiving the message, respond in the next invocation of `next_message`.
This allows bots to acknowledge the last received gateway message before encountering a send (IO) error.
> fix(gateway): don't swallow events on send error

- examples/gateway-parallel.rs
It suffers from being unnecessarily complex, just to prove a point. This not only simplifies the code but also improves performance by removing overhead.
> docs(gateway): cleanup parallel example

- twilight-model/Cargo.toml
- twilight-model/src/application/command/permissions.rs
- twilight-model/src/application/interaction/application_command/option.rs
- twilight-model/src/application/interaction/mod.rs
- twilight-model/src/channel/message/component/mod.rs
- twilight-model/src/gateway/event/gateway.rs
- twilight-model/src/gateway/payload/incoming/member_chunk.rs
- twilight-model/src/gateway/presence/activity_button.rs
- twilight-model/src/guild/mod.rs
The `tracing` ecosystem of crates allow for recording events which can then be viewed when debugging. Most `twilight` crates therefore record useful data with it, but its unnecessary for `twilight-model` to do so. This is because deserializers most necessary data on deserialization error for troubleshooting. Including further details is left to dependants. `twilight-gateway`, for example, includes the full gateway event in `ReceiveMessageError`.
> feat(model): remove `tracing`

- twilight-gateway/src/config.rs
- twilight-gateway/src/stream.rs
A `From` implementation is in this case more idiomatic than a free-standing constructor. It loosing `const` is irrelevant as `Config` cannot be built in `const` either way.
Deprecates `ConfigBuilder::with_config` as it's no longer needed.
> feat(gateway): impl `From<Config>` for ConfigBuilder

- .github/workflows/book.yml
Wrangler 3.0.0 renamed `publish` to `deploy`.
Supercedes #2259
> ci: bump wrangler to v3

- twilight-gateway/src/shard.rs
Aligns our code with the spec by removing questionable logic that, even if hit, was completely wrong. The code tried to resume with the *new* sequence (instead of the old) and it's not swallowing the, to be, duplicated event.
> refactor(gateway): cleanup dispatch sequence handling

- twilight-model/src/guild/audit_log/optional_entry_info.rs
- twilight-model/src/guild/integration_type.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6367
This PR also adds a missing `guild_subscription` variant to `GuildIntegrationType`
> feat(model): add `integration_type` to audit log entries

- twilight-http/src/client/mod.rs
- twilight-http/src/request/guild/member/get_guild_members.rs
Without the limit set to 500, discord would default it to 1, so when the comment says it returns 500 members, it should set the limit to 500.
> docs(http): add limit to guild members request

- twilight-model/src/guild/vanity_url.rs
The VanityUrl model used for the response from [/guilds/{guild.id}/vanity-url](https://discord.com/developers/docs/resources/guild#get-guild-vanity-url) is missing the `uses` field. 
Despite what the aforementioned docs say, the code will not be null if the vanity url is not set, instead, you get a `403` response, so I did not make any additional changes beyond adding the uses field.
> fix(models): add VanityUrl uses

- twilight-http/src/routing.rs
Currently the GetInvite `with_counts()` and `with_expiration()` don't work as the query string they append uses `-` instead of `_` in the keys, as specified in the API docs - https://discord.com/developers/docs/resources/invite#get-invite-query-string-params.
> fix(http): fix get invite query params

- twilight-http/src/request/guild/ban/create_ban.rs
- twilight-http/src/routing.rs
> fix(http): Use `default_message_seconds` as a json field for `create_ban`

- examples/gateway-reshard.rs
- twilight-cache-inmemory/src/lib.rs
- twilight-gateway/src/config.rs
- twilight-http/CHANGELOG.md
- twilight-mention/src/timestamp.rs
- twilight-model/src/id/mod.rs
- twilight-standby/src/lib.rs
- Because the CI seems to be using the latest rust version, a redundant `deref()` was removed as the compiler gave a warning.
- The CI for spell checks seems to have an updated dictionary. The new spelling errors found have been corrected in this PR.
- Clippy was throwing an error for inconsistent `PartialOrd` implementations. This was also fixed.
> fix: new rust CI errors

- twilight-cache-inmemory/src/event/reaction.rs
- twilight-model/src/channel/message/mod.rs
- twilight-model/src/channel/message/reaction.rs
- twilight-model/src/util/hex_color.rs
- twilight-model/src/util/mod.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6056
This PR also adds a new `HexColor` struct for efficiently storing hex strings.
> feat(model, cache): add support for super reactions

- twilight-http/src/request/guild/create_guild_channel.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6414
> feat(http): support default thread timeout for channel creation

- twilight-http/Cargo.toml
- twilight-http/README.md
- twilight-http/src/client/connector.rs
The `trust-dns` crate was renamed to `hickory`, so the hyper glue dependency and feature names had to be adjusted accordingly. The remaining changes are to account for `hickory`'s ability to work with any async runtime provider.
> build(http)!: Update trust-dns (now hickory)

- twilight-mention/src/fmt.rs
- twilight-mention/src/parse/error.rs
- twilight-mention/src/parse/impl.rs
I realized that the `mention` crate is missing `Display` implementations for commands. Commands are formatted like this:
- `</NAME:COMMAND_ID>` for commands
- `</NAME SUBCOMMAND:ID>` for subcommands
- `</NAME SUBCOMMAND_GROUP SUBCOMMAND:ID>` for subcommand groups
This is documented [here](https://discord.com/developers/docs/reference#message-formatting) and in the [changelog](https://discord.com/developers/docs/change-log#slash-command-mentions).
For the `Mention` implementation I checked what could be useful implementations. The tuples here are for convenience but maybe obsolete.
I considered implementing `Mention` for `model::application::command::Command` and `model::application::application_command::CommandData` but both them may contain mutiple subcommands or subcommand groups, …
> feat(mention): add mention for commands

- twilight-http/src/json.rs
This was not used anywhere so simply removing it should fix the docs build.
> fix(ci, http): fix docs deploy

- twilight-http/src/response/mod.rs
The conversion is no longer necessary since the decompression changes.
Ref:
- https://github.com/twilight-rs/twilight/pull/1104
> refactor(http): remove unnecessary conversion 

- twilight-http/src/response/mod.rs
The generated code is much smaller.
> perf(http): use optimized `slice::to_vec()`

- twilight-http/src/response/mod.rs
The `TextFuture` now returns `std::str::Utf8Error` as source error if the body is not a valid UTF-8 string.
There is no need to provide the bytes with the error kind variant and as part of the source error.
> refactor(http)!: avoid copying the reponse body on utf8 error

- examples/gateway-queue-http.rs
- twilight-gateway-queue/src/in_memory.rs
- twilight-gateway-queue/src/lib.rs
- twilight-gateway/src/config.rs
- twilight-gateway/src/shard.rs
- twilight-gateway/src/stream.rs
By making `Config`, and its dependants, generic over the queue we avoid an unnecessary pointer indirection through `Arc<dyn Queue>` which has been a pet peeve of mine for some time. This furthers allows dropping the `Debug` requirement from `Queue`, another of my pet peeves.
As everyone not running multi-process bots should be using the `InMemoryQueue`, `Config`, `ConfigBuilder`, and `Shard` default to it. I.e. `Shard` is equivalent to `Shard<InMemoryQueue>`. This might, however, not be ideal if further queues are added. For example, a `SelfRefillableQueue` implementation that calls the "Get Gateway Bot" endpoint in the background at some interval could prove very popular in which case defaulting to any type might not be that useful.
> feat(gateway)!: turn `Queue` into a generic type

- examples/gateway-reshard.rs
Removes irrelevant code & comments and improves identified heuristics.
> docs(gateway): cleanup reshard example

- twilight-model/src/gateway/event/gateway.rs
This field was never used or exposed and `cargo check/doc` on recent nightlies started complaining about it. It is however exposed on the `GatewayEvent` parser so it cannot be removed there and it shouldn't.
> perf(model): Remove sequence from GatewayEventVisitor

- examples/Cargo.toml
- examples/gateway-queue-http.rs
- examples/lavalink-basic-bot.rs
- examples/model-webhook-slash.rs
- twilight-gateway/Cargo.toml
- twilight-gateway/src/connection.rs
- twilight-http-ratelimiting/Cargo.toml
- twilight-http/Cargo.toml
- twilight-http/src/client/builder.rs
- twilight-http/src/client/connector.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/error.rs
- twilight-http/src/request/base.rs
- twilight-http/src/request/guild/ban/create_ban.rs
- twilight-http/src/request/mod.rs
- twilight-http/src/response/future.rs
- twilight-http/src/response/mod.rs
- twilight-lavalink/Cargo.toml
- twilight-lavalink/src/node.rs
This updates the following crates to their latest versions, which are compatible with rustls 0.22, http 1.x and hyper 1.x:
* http
* hyper
* hyper-hickory
* hyper-rustls
* hyper-tls
* tokio-websockets
It also changes the HTTP client to make use of `hyper-util`'s legacy client implementation.
> build(http, gateway, lavalink): Update to rustls 0.22, hyper 1.0, tokio-websockets 0.5

- book/src/chapter_1_crates/section_2_http.md
- book/src/chapter_1_crates/section_3_gateway.md
- book/src/chapter_1_crates/section_7_first_party/section_3_lavalink.md
- twilight-gateway/Cargo.toml
- twilight-gateway/README.md
- twilight-gateway/src/shard.rs
- twilight-http/Cargo.toml
- twilight-http/README.md
- twilight-http/src/client/connector.rs
- twilight-lavalink/Cargo.toml
- twilight-lavalink/README.md
The `native` name is very unconcise. `native` what? CPU target? TLS implementation? Renaming it to `native-tls` makes it more self-explanatory and users less prone to erraneously enabling two TLS features.
> build(gateway, http, lavalink)!: Rename native feature to native-tls

- book/src/versions/0.16/summary.md
- twilight-gateway/Cargo.toml
- twilight-lavalink/Cargo.toml
Fixes TLS issues when using a gateway proxy without TLS.
> build(gateway, lavalink): Update to tokio-websockets 0.7

- twilight-lavalink/src/node.rs
Capitalization in a header is illegal and causes the bot to panic. I posted in discord and figured it out shortly after. https://docs.rs/http/latest/http/header/struct.HeaderName.html#method.from_static
> Panics
> This function panics when the static string is a invalid header.
>
> Until [Allow panicking in constants](https://github.com/rust-lang/rfcs/pull/2345) makes its way into stable, the panic message at > compile-time is going to look cryptic, but should at least point at your header value:
Steps to reproduce:
1. checkout latest branch
2. startup a 3.X.Y lavalink server locally
3. build example lavalink-basic-bot
It would panic immediately on connect. See attached log of the panic. [backtrace.log](https://github.com/twilight-rs/twilight/files/14488252/backtrace.log)
> Lavalink broken in 0.16 rc

- twilight-gateway/src/config.rs
- twilight-gateway/src/shard.rs
Adds equivalents to the existing session related functions for resume_url to Config, ConfigBuilder and Shard
closes #2324
> feat(gateway): Allow setting initial resume_url

- twilight-validate/src/command.rs
User and Message commands must have a description that is a empty string. If the string was not empty it would print the following error:
```
Error: command description must be between 1 and 100 characters
```
Resolves #2306.
> fix(validate): Misleading error message validating commands.

- twilight-cache-inmemory/src/permission.rs
- twilight-http-ratelimiting/src/in_memory/bucket.rs
The dead code warning is for some reason only picked up on nightly.
> fix(cache,ratelimiting): Resolved some warnings when building docs.

- twilight-gateway/src/event.rs
`EventTypeFlag::GUILD_MESSAGES` should include the `EventTypeFlag::MESSAGE_UPDATE` flag and no duplicated `EventTypeFlag::MESSAGE_DELETE` flag.
> fix(gateway): Add missing flag to `EventTypeFlags::GUILD_MESSAGES`

- twilight-http/src/client/mod.rs
- twilight-http/src/request/guild/update_guild_channel_positions.rs
- twilight-model/src/http/channel_position.rs
- twilight-model/src/http/mod.rs
This PR moves the Position struct to the model crate.
It also fixes an issue where it was not possible to create null values in the fields that had the ability to be null or left out.
Resolves #2327
> feat(model, http): Make positions possible to create

- examples/gateway-request-members.rs
- twilight-cache-inmemory/src/event/guild.rs
- twilight-cache-inmemory/src/permission.rs
- twilight-model/src/gateway/event/mod.rs
- twilight-model/src/gateway/payload/incoming/guild_create.rs
This changes `GuildCreate` from being a tuple struct to being a enum that can either be available or unavailable, and containing either a full `Guild` or a `UnavailableGuild`.
> fix(model): Deserialize unavailable guilds in GUILD_CREATE.

- twilight-http/src/request/user/update_current_user.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6710
> feat(http): allow editing app banner

- twilight-model/src/channel/permission_overwrite.rs
Permission overwrites are very small stack allocatables. They should be Copy.
> fix(model): Derive Copy on PermissionOverwrite

- twilight-model/src/channel/message/kind.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6558
> feat(model): add new automod message incident types

- twilight-model/src/guild/auto_moderation/action.rs
- twilight-model/src/guild/auto_moderation/event_type.rs
- twilight-model/src/guild/auto_moderation/trigger_type.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6040
> feat(model): Add support for automod member profile words and member interactions

- twilight-http-ratelimiting/src/request.rs
Auto moderation would not work with rate limiting since paths were missing.
> fix(http-ratelimiting): Add missing automoderation paths.

- twilight-http-ratelimiting/src/request.rs
Whilst using the http-proxy, I discovered that the http-ratelimiting crate was missing a `@` symbol in one of the route paths.
> fix(http): Add missing @ symbol in REST path

- twilight-http/src/client/mod.rs
- twilight-http/src/request/audit_reason.rs
- twilight-http/src/request/guild/role/update_role_positions.rs
- twilight-model/src/guild/mod.rs
- twilight-model/src/guild/role_position.rs
Closes #2338 and adds audit log reason support for this endpoint.
> fix(model, http)!: fix role position update payload and allow audit log reason

- twilight-cache-inmemory/src/event/reaction.rs
- twilight-cache-inmemory/src/test.rs
- twilight-http/src/request/channel/reaction/get_reactions.rs
- twilight-http/src/routing.rs
- twilight-model/src/channel/message/component/button.rs
- twilight-model/src/channel/message/component/mod.rs
- twilight-model/src/channel/message/component/select_menu.rs
- twilight-model/src/channel/message/mod.rs
- twilight-model/src/channel/message/reaction.rs
- twilight-model/src/channel/message/reaction_type.rs
- twilight-model/src/gateway/payload/incoming/reaction_remove_emoji.rs
- twilight-model/src/gateway/reaction.rs
- twilight-model/src/util/hex_color.rs
- twilight-standby/src/lib.rs
- twilight-validate/src/component.rs
Refs:
- https://github.com/discord/discord-api-docs/pull/6375
- https://github.com/discord/discord-api-docs/pull/6377
This PR renames the old `ReactionType` to `EmojiReactionType` as the concept of a reaction type now exists in the API.
> feat(model, http)!: Add support for super reaction types

- twilight-model/src/application/interaction/resolved.rs
- twilight-model/src/channel/attachment.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6945
> feat(model): add attachment titles

- twilight-model/src/application/interaction/mod.rs
> fix(model): Entitlements would only deserialize it was before data

- twilight-gateway/README.md
- twilight-gateway/src/error.rs
- twilight-gateway/src/message.rs
- twilight-gateway/src/shard.rs
Reading received messages on shutdown requires verbosely matching on WebSocket errors to prevent the shard from automatically reconnecting. While potentially useful for debugging, my experience is that WebSocket errors are generally just noise, and as such they are replaced with close messages with a [status code of 1006](https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1) indicating abnormal closure. This has the secondary benefit of removing confusion about transport errors being somehow actionable (any internet connection may naturally error at any time for reasons outside of your control).
> feat(gateway)!: swallow WebSocket errors

- .github/workflows/check.yml
This was an unintended change caused by merging an older PR after the MSRV bump without accounting for it.
> ci: Don't downgrade tokio

- .github/workflows/deploy-lib.yml
Switch the GH Pages API documentation workflow from deploying from a commit to deploying from an artifact.
Twilight currently has an extremely large `gh-pages` branch with all snapshots of our rustdoc rendered documentation for all crates as commits. Due to the nature of how Git stores commits, this ballons the branch's size (>200 MB!) and subsequently the whole repository's size. GitHub has since last year offered publishing to Pages from an uploaded artifact as an alternative to publishing from a branch which avoids storing the contents in Git.
Additionally, this renames the API documentation environment from "github-pages" to "api-documentation" which should make it more discoverable to new users.
> ci: switch API docs to modern GH Pages action

- .github/workflows/check.yml
- twilight-http-ratelimiting/src/request.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/request/application/emoji/add_emoji.rs
- twilight-http/src/request/application/emoji/delete_emoji.rs
- twilight-http/src/request/application/emoji/list_emojis.rs
- twilight-http/src/request/application/emoji/mod.rs
- twilight-http/src/request/application/emoji/update_emoji.rs
- twilight-http/src/request/application/mod.rs
- twilight-http/src/request/try_into_request.rs
- twilight-http/src/routing.rs
Refs:
- https://github.com/discord/discord-api-docs/pull/7010
> feat(http): Add support for application emojis

- twilight-cache-inmemory/src/event/guild.rs
- twilight-cache-inmemory/src/model/guild.rs
- twilight-cache-inmemory/src/permission.rs
- twilight-cache-inmemory/src/test.rs
- twilight-model/src/guild/mod.rs
Add support for the guild field `max_stage_video_channel_users`, which functions similarly to related fields such as `max_video_channel_users`. This has been added on the `Guild` model type and the `CachedGuild` inmemory cache type.
Split out from #2147.
> feat(cache, model): add max_stage_video_channel_users

- twilight-gateway/Cargo.toml
- twilight-gateway/README.md
- twilight-gateway/src/shard.rs
- twilight-http/Cargo.toml
- twilight-http/README.md
- twilight-http/src/client/connector.rs
- twilight-lavalink/Cargo.toml
- twilight-lavalink/README.md
This also adds support for rustls-platform-verifier and makes it the default. Further, support for aws-lc-rs is added, but not enabled by default.
Users disabling default features will have to manually enable a crypto backend for rustls now or install a global default using the rustls' CrytoProvider::install_default method [1].
[1]: https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#method.install_default
> build(gateway,http,lavalink): Update to rustls 0.23

- twilight-http/src/request/application/emoji/list_emojis.rs
- twilight-model/src/application/emoji.rs
- twilight-model/src/application/mod.rs
For some reason "List Application Emojis" returns a object with a single `items` key which caused our use of `ListBody` to fail here.
Resolves: #2373
> fix(http): List application emojis does not return a raw list

- twilight-model/src/channel/thread/auto_archive_duration.rs
- twilight-model/src/visitor.rs
This patch simplifies our implementation of `auto_archive_duration` this also solves the same issue we encountered with simd-json that was resolved in #2370.
> refactor(model): simplify auto_archive_duration de/serialize

- twilight-util/src/builder/command.rs
This also deprecates `dm_permission` in the builder
> feat(util): add contexts and integration types to command builder

- twilight-cache-inmemory/src/event/interaction.rs
- twilight-model/src/application/interaction/mod.rs
- twilight-standby/src/lib.rs
Note that this adds a new partial guild since there is a issue with
the name of the fields of this specific partial guild.
Closes #2381
> feat(model): Add guild field to interaction.

- examples/cache-optimization/models/guild.rs
- twilight-cache-inmemory/src/event/guild.rs
- twilight-cache-inmemory/src/model/guild.rs
- twilight-cache-inmemory/src/permission.rs
- twilight-cache-inmemory/src/test.rs
- twilight-cache-inmemory/src/traits.rs
- twilight-model/src/gateway/payload/incoming/guild_delete.rs
- twilight-model/src/guild/mod.rs
Unavailable would assume false if the field was false if it was not sent.
The ability to tell the difference can be used to tell the difference between a guild becoming available and joining a new guild.
Resolves #2372
> fix(model, cache): unavailable is optional and false and none equal

- twilight-http/src/request/guild/role/update_role.rs
According to [Discord docs](https://discord.com/developers/docs/resources/guild#modify-guild-role), `UpdateRoleFields::icon` is Image Data in [Data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) format. Basically, it must be a string. An example Data URI format is:
```
data:image/jpeg;base64,BASE64_ENCODED_JPEG_IMAGE_DATA
```
Additionally, people should be able to set `UpdateRoleFields::icon` and `UpdateRoleFields::unicode_emoji` to null to remove the role icon (if needed).
Briefly describe this pr, it makes `UpdateRoleFields::icon` and `UpdateRoleFields::unicode_emoji` nullable strings.
> fix(http): update role icon and unicode_emoji using nullable strings

- examples/cache-optimization/models/message.rs
- twilight-cache-inmemory/src/event/message.rs
- twilight-cache-inmemory/src/model/message.rs
- twilight-cache-inmemory/src/traits.rs
- twilight-model/src/gateway/event/mod.rs
- twilight-model/src/gateway/payload/incoming/message_update.rs
`MessageUpdate` event now contains a full `Message` object.
Refs:
- https://github.com/discord/discord-api-docs/pull/7017
> refactor(model, cache): a full message object for `MessageUpdate` event

- twilight-http/src/response/status_code.rs
This is to facilitate matching on specific status codes such as 
```rust
if let ErrorType::Response { status: StatusCode::NOT_FOUND, .. } = err.kind() {
```
> feat(http): Add Discord defined status codes as constants

- .github/workflows/check.yml
- twilight-cache-inmemory/src/lib.rs
- twilight-gateway/src/stream.rs
- twilight-http/src/routing.rs
- twilight-lavalink/src/lib.rs
- twilight-mention/src/parse/iter.rs
- twilight-model/src/gateway/event/dispatch.rs
- twilight-model/src/guild/permissions.rs
- twilight-model/src/lib.rs
- twilight-model/src/user/mod.rs
- twilight-model/src/util/hex_color.rs
- twilight-model/src/util/mustbe.rs
- twilight-model/src/visitor.rs
- twilight-util/src/lib.rs
- twilight-validate/src/command.rs
* `serde_derive` < 1.0.113 no longer work with modern rustc versions.
* `used_underscore_items` is a false positive, see rust-lang/rust-clippy#13478
> chore(clippy, minvers): resolve rust 1.83 issues

- twilight-gateway/src/shard.rs
Instantiating these errors incur allocations (cloning `event` as well as creating the `source` String) so let's create them lazily instead of eagerly.
> perf(gateway): lazily allocate errors

- twilight-gateway/src/ratelimiter.rs
We're always calling `clock_gettime()` when acquiring a permit even if we've just done so already in when checking readiness. This is not a big deal performance wise, but it feels counterintuitive to not reuse already fetched resources as if the alrorithm required it (it does not).
> refactor(gateway): reuse 'now' instant for `poll_acquire`

- twilight-http/src/client/mod.rs
- twilight-http/src/request/guild/role/get_role.rs
- twilight-http/src/request/guild/role/mod.rs
- twilight-http/src/request/try_into_request.rs
- twilight-http/src/routing.rs
Discord supports an endpoint that allows to fetch a single guild role.
- https://github.com/discord/discord-api-docs/pull/7074
> feat(http): add get guild role endpoint

- twilight-gateway/src/latency.rs
[Rotate](https://github.com/rust-lang/rust/blob/37e74596c0b59e81b9ac58657f92297ef4ccb7ef/library/core/src/slice/rotate.rs) is a perhaps surprisingly expensive operation, when we really just want to move stuff one step to the right.
Inspired from a similar optimization in #2395 (tagged as a refactor since this doesn't measurably impact performance).
> refactor(gateway): avoid recent latencies rotate

- twilight-gateway/src/ratelimiter.rs
- twilight-gateway/src/shard.rs
Switches from storing absolute timestamps to relative ones to `delay` as milliseconds (tokio's timer resolution). This reduces the item size from 12 bytes to just 2 (as 60,000 ms fits in a `u16`) and adds a negligible amount of bookkeeping work in rebasing the timestamps on `delay` elapsing. From this I also made the first relative timestamp implicit from whether `delay` is elapsed or not (instead of being zero).
Additionally, this PR fixes the following minor bugs:
* always store waker in `poll_pending` (always call `Sleep::poll`)
* `slice::partition_point` may return any matching element, but we depend upon the first being returned (it should be impossible to acquire two permits at the same time in practice, since we send a gateway command between each acquisition)
* …
> perf(gateway): optimize `CommandRatelimiter` size

- twilight-cache-inmemory/src/test.rs
- twilight-model/src/gateway/payload/incoming/ready.rs
- twilight-model/src/user/current_user.rs
- twilight-model/src/user/mod.rs
- twilight-standby/src/lib.rs
Add `global_name` to `CurrentUser`
Closes: #2411
> fix(model): Add global_name to CurrentUser

- examples/Cargo.toml
- examples/gateway-reshard.rs
- twilight-gateway/Cargo.toml
- twilight-gateway/README.md
- twilight-gateway/src/shard.rs
Shard instrumentation is necessary for following specific shards, but by adding it ourselves users are not able to hook into it, for example on errors. Some work around this by instrumenting their shard running function, but this may lead to duplication if they do not filter their subscriber. This was considered worthwhile, as it cleaned up user's logs at a time when many experienced issues with the gateway and instrumenting a stream combinator (like the old `ShardEventStream`) is difficult.
The `gateway-reshard` example needed to be migrated from using a stream combinator to spawning tasks (which also improves its performance).
> refactor(gateway): remove instrument from shard::poll_next

- twilight-model/src/application/command/option.rs
This commit adds associated types for the integer and floating point range that is allowed.
It also adds a range that contains the allowed length of a string.
Closes #2402
> feat(model): Add associated types to CommandOption(Value).

- twilight-model/src/application/interaction/application_command/option.rs
We skip a couple that I don't think makes sense (`Focused`, `SubCommand`, and `SubCommandGroup`)
Closes #2403
> feat(model): Add various From implementations for CommandOptionValue

- book/src/chapter_1_crates/section_3_gateway.md
- twilight-gateway/Cargo.toml
- twilight-gateway/README.md
- twilight-gateway/src/compression.rs
- twilight-gateway/src/error.rs
- twilight-gateway/src/inflater.rs
- twilight-gateway/src/lib.rs
- twilight-gateway/src/shard.rs
Adds support for `zstd-stream`[^1] transport compression using Facebook's reference implementation (written in C) and deprecates our `zlib-stream` support.
I did not run into any build dependency issues on macOS, Linux, or Windows as Zstd-safe seems to statically link against Zstd. Otherwise there is a pure Rust implementation of Zstandard called ruzstd which we may eventually switch to.
This PR deprecates the `zlib-stock` and `zlib-simd` features since they are replaced by the `zstd` feature. While doing this, I opted to not expose the previous `Inflater` type and its `processed` and `produced` properties as those are not tracked by Zstd itself.
Edit: more radically, should we unconditionally use Zstd transport compression? It's like an implementation detail (or a foot gun).
Update: no, …
> feat(gateway): support `zstd-stream`

- twilight-cache-inmemory/src/lib.rs
- twilight-model/src/gateway/event/gateway.rs
- twilight-model/src/gateway/event/mod.rs
My shard received a heartbeat event and apparently we model that wrongly. Discord documents this event as containing data, but that's only when sent to the gateway.
```
2025-02-14T15:50:16.796316Z DEBUG twilight_gateway::shard: received heartbeat
2025-02-14T15:50:16.796359Z  WARN gateway_request_members: error receiving event source=ReceiveMessageError { kind: Deserializing { event: "{\"t\":null,\"s\":null,\"op\":1,\"d\":null}" }, source: Some(Error("invalid type: null, expected u64", line: 1, column: 34)) }
```
> fix(model)!: incoming heartbeat has null data

- twilight-gateway/src/shard.rs
We should not return more than one `ABNORMAL_CLOSE` messages per connection. Specializing for Discord's incorrect WS implementation is no longer needed since we no longer forward transport errors (and Discord's closure error occurs after exchanging close messages).
> fix(gateway): handle repeat recv errors

- twilight-gateway/src/shard.rs
Zombied connections are unlikely to receive further messages, so there's little use in awaiting a response close frame.
Fixes an issue where dead TCP connections would never be polled to completion.
> fix(gateway): terminate zombied connections

- twilight-http/src/request/channel/message/create_message.rs
the code for adding a forward to a message seems to have been copied from the reply method, but unlike replies, forwards can refer to messages from other channels.
> fix(http): forwarding allows references from other channels

- twilight-model/src/channel/message/snapshot.rs
Add `type`, `components`, and `sticker_items` fields to message snapshot model
This fixes re-serialisation of message snapshot objects to include `type`, which is required in messages, causing other libraries to crash (d.py) when attempting to deserialise a message containing a message snapshot.
> feat(model) Add missing fields to message_snapshots
