- .github/workflows/audit.yml
This version runs once every day at midnight, for prs and for pushes.
> [CI] Added workflow for running cargo-audit.

- http/src/request/guild/member/get_guild_members.rs
- http/src/routing.rs
- model/src/gateway/payload/member_chunk.rs
> Precences field

- model/src/guild/audit_log/optional_entry_info.rs
> Add message_id to optional audit entry info

- cache/in-memory/Cargo.toml
- dawn/Cargo.toml
- gateway/Cargo.toml
- gateway/examples/shard/Cargo.toml
- gateway/src/cluster/impl.rs
- gateway/src/queue.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/mod.rs
- gateway/src/shard/processor/connect.rs
- gateway/src/shard/processor/emit.rs
- gateway/src/shard/processor/heartbeat.rs
- gateway/src/shard/processor/impl.rs
- gateway/src/shard/processor/session.rs
- gateway/src/shard/processor/socket_forwarder.rs
- http/Cargo.toml
- http/examples/get-message/Cargo.toml
- http/examples/proxy/Cargo.toml
- http/src/ratelimiting/bucket.rs
- http/src/ratelimiting/mod.rs
This update seems to fix #40, though more
testing is required to make fully sure that
it does. While doing this update a couple of
subsystems got rewritten.
> Update to tokio 0.2 stable.

- cache/in-memory/src/lib.rs
> (chore): run rustfmt

- model/src/channel/mod.rs
- model/src/channel/webhook.rs
- model/src/channel/webhook_type.rs
> Add new field to Webhook

- command-parser/src/parser.rs
- model/src/gateway/presence/mod.rs
- model/src/id.rs
No issue attached to this PR, this fixes some clippy lints that were complaining on my machine
> Small clippy fixes

- cache/in-memory/src/shard.rs
- cache/in-memory/src/updates.rs
Two out of the four in #25
Signed-off-by: Iris Faey Hoffmeyer <hoffmeyer25@gmail.com>
> Implement ReactionRemove and ReactionRemoveAll cache updates

- model/src/channel/embed/author.rs
- model/src/channel/embed/image.rs
- model/src/channel/embed/mod.rs
- model/src/channel/embed/provider.rs
- model/src/channel/embed/thumbnail.rs
- model/src/channel/embed/video.rs
The structures now follow the definitions given on
discordapp.com
> Make the definitions of the embed structures correct

- gateway/src/shard/processor/impl.rs
Without doing this, we're left with fairly unhelpful messages as to
what we actually need to change.
> Show the actual JSON in debug when we can't seralize a Event

- cache/in-memory/src/config.rs
- cache/in-memory/src/shard.rs
- cache/in-memory/src/updates.rs
- gateway/src/event.rs
- gateway/src/shard/event.rs
- model/src/gateway/payload/mod.rs
- model/src/gateway/payload/webhooks_update.rs
Currently error on `WEBSOCKET_UPDATE` with something like:
`Error receiveing gateway event: Some(Error("Unknown variant WEBHOOKS_UPDATE. Expected one of ", line: 1, column: 114))`
> Handle `WEBHOOKS_UPDATE`

- LICENSE.md
- dawn/Cargo.toml
- gateway/Cargo.toml
- model/Cargo.toml
> Update license and some authors

- command-parser/Cargo.toml
- command-parser/src/arguments.rs
- command-parser/src/config.rs
- command-parser/src/lib.rs
- command-parser/src/parser.rs
> Adds support for case insensitive commands

- http/src/client/mod.rs
The prefix would be added in all cases even if the token already
started with it, witch would lead to authentication errors as the
token would start with `Bot Bot `.
> Fix a bug with adding `Bot ` to tokens that did not need it.

- cache/in-memory/src/config.rs
- command-parser/src/parser.rs
- http/src/client/mod.rs
- http/src/request/channel/reaction/delete_all_reaction.rs
- http/src/request/channel/reaction/mod.rs
- http/src/routing.rs
- model/src/gateway/payload/voice_state_update.rs
- model/src/gateway/presence/mod.rs
Might want to change Self::DeleteMessageSpecficReaction to something else
but I feel like this is at least a good start, as it's clear what it does
> Delete all reaction

- CODEOWNERS
> Add CODEOWNERS to dawn

- gateway/examples/cluster/src/main.rs
- gateway/src/cluster/config.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/config.rs
- model/src/gateway/payload/identify.rs
The sharder was all connecting to the same shard
This also changes how a few builders work, if all the 
builders should work like that is not known yet.
it also changes a small error in a model for identify
> Fix sharder not working

- cache/in-memory/src/model/guild.rs
- gateway/Cargo.toml
- gateway/src/shard/processor/heartbeat.rs
- model/src/guild/mod.rs
dawn_http::Client::guild() wont scream that theres missing things
dawn_gateway::shard::Shard::info().latency().average() wont try and divide by zero bc its an option!
> Fix divide by zero panic, and fix parts of the Guild model

- Cargo.toml
- gateway/examples/intents/Cargo.toml
- gateway/examples/intents/src/main.rs
- gateway/src/event.rs
- gateway/src/lib.rs
- gateway/src/shard/config.rs
- gateway/src/shard/event.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/processor/impl.rs
- http/src/routing.rs
- model/src/gateway/intents.rs
- model/src/gateway/mod.rs
- model/src/gateway/payload/identify.rs
This will as a draft until gateway intents are available for the general public.
> Add support for gateway intents.

- model/src/gateway/payload/member_chunk.rs
- model/src/gateway/payload/presence_update.rs
- model/src/guild/partial_guild.rs
> This fixes some smaller issues with the model

- gateway/src/cluster/impl.rs
This is a small pr that just adds some missing derives
----
#
> Added some derives that were missing.

- gateway/src/cluster/config.rs
Adding this since it's mentioned [here](https://github.com/dawn-rs/dawn/blob/master/gateway/src/cluster/config.rs#L126) but didn't actually exist
The doc comment is extremely terrible and I welcome any and all suggestions ❤️What should I mention in it, etc?
> Expose intents from ClusterConfig

- cache/in-memory/src/lib.rs
- cache/in-memory/src/model/emoji.rs
- cache/in-memory/src/updates.rs
- http/src/client/mod.rs
- http/src/request/channel/update_channel.rs
- http/src/request/guild/get_guild_preview.rs
- http/src/request/guild/mod.rs
- http/src/request/guild/update_guild.rs
- http/src/routing.rs
- model/src/channel/message/kind.rs
- model/src/guild/emoji.rs
- model/src/guild/mod.rs
- model/src/guild/permissions.rs
- model/src/guild/preview.rs
- model/src/user/premium_type.rs
> Updated the lib to support the newest Discord features as of 2020-03-21.

- gateway/src/cluster/impl.rs
- gateway/src/shard/config.rs
This fixes that intents was not working when using it with cluster.
> Properly set ShardConfig

- gateway/src/shard/processor/impl.rs
- gateway/src/shard/processor/session.rs
Implemented it to close with a close code of 1012
> Properly implement the reconnect op code.

- gateway/src/queue/day_limiter.rs
- gateway/src/queue/large_bot_queue.rs
Code would panic if you had logging on because it would try to make a negative duration.
> Fix panic in LargeBotQueue

- cache/in-memory/src/shard.rs
- cache/in-memory/src/updates.rs
- model/src/gateway/payload/voice_state_update.rs
- model/src/guild/emoji.rs
- model/src/lib.rs
- model/src/user/connection.rs
- model/src/voice/voice_region.rs
- model/src/voice/voice_state.rs
> Add some of the missing cache events

- README.md
- cache/in-memory/src/config.rs
- cache/in-memory/src/lib.rs
- command-parser/README.md
- command-parser/src/arguments.rs
- command-parser/src/builder/command.rs
- command-parser/src/config.rs
- command-parser/src/lib.rs
- command-parser/src/parser.rs
- gateway/examples/cluster/src/main.rs
- gateway/examples/intents/src/main.rs
- gateway/src/cluster/config.rs
- gateway/src/cluster/error.rs
- gateway/src/cluster/impl.rs
- gateway/src/cluster/mod.rs
- gateway/src/lib.rs
- gateway/src/shard/config.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/mod.rs
- gateway/src/shard/processor/impl.rs
- http/src/client/config.rs
- http/src/client/mod.rs
> Make config struct names consistent

- Cargo.toml
- builders/Cargo.toml
- builders/src/embed.rs
- builders/src/lib.rs
- model/src/channel/reaction_type.rs
- twilight/Cargo.toml
- twilight/src/lib.rs
It contains builders for various structures
used in connection with Discord. Currently
only contains a builder for Embeds.
> Add new crate: Builders.

- builders/src/embed.rs
> Make the embed builder work better and add a test.

- gateway/src/cluster/error.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/impl.rs
- model/src/gateway/payload/update_voice_state.rs
This makes it much easier to send commands on the gateway.
> Add new method to send a command on the gateway

- gateway/src/shard/impl.rs
- gateway/src/shard/processor/session.rs
- model/src/gateway/payload/member_chunk.rs
Also fixes issue with deserialising presences
> Make the command method keep within the rate limit.

- Cargo.toml
- gateway/examples/request-members/Cargo.toml
- gateway/examples/request-members/src/main.rs
- model/src/gateway/payload/member_chunk.rs
- model/src/gateway/payload/request_guild_members.rs
it now covers the new field for nonces
member chunks now covers all reply fields as well
> expand request guild members

- model/src/gateway/payload/member_add.rs
- model/src/gateway/payload/voice_state_update.rs
- model/src/user/flags.rs
- model/src/user/mod.rs
this adds the public flags field, this allows bots to get those flags for users without using oauth (it's not included in member chunks though)
also added latest flags
> add public flags field and update the flags list

- gateway/src/cluster/error.rs
- gateway/src/cluster/impl.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/processor/heartbeat.rs
- gateway/src/shard/processor/impl.rs
- http/src/request/channel/message/allowed_mentions.rs
With this PR we can reenable Clippy.
> Feedback from clippy.

- model/src/id.rs
quickly convert numbers into ids, just a QOL addition
> add QOL id converters

- .github/workflows/lint.yml
- command-parser/src/parser.rs
- gateway/examples/request-members/src/main.rs
- gateway/src/shard/processor/impl.rs
- http/examples/allowed-mentions/src/main.rs
- model/src/gateway/payload/request_guild_members.rs
Use stable clippy in the lint workflow and fix some lints causing it to fail.
Closes #163.
> actions: use stable clippy

- cache/in-memory/src/lib.rs
In the InMemoryCache, automatically attach Guild IDs to guild channels
as they're added. Guild channels over the gateway don't include their
guild IDs.
A test has been added to show that after a guild channel without a guild
ID is inserted to the cache through a guild create, the channel
retrieved will have the correct guild ID.
Closes #159.
> cache/in-memory: attach guild ids to channels

- http/src/client/mod.rs
https://discord.com/developers/docs/reference#user-agent
> Change the User-Agent to be on the correct format.

- standby/src/lib.rs
In Standby, instead of returning Options for the waiting methods return Results, where the error is a `futures_channel::oneshot::Canceled`. This makes `?`ing up the error possible which is what you want in most cases.
> standby: return results for waiting methods

- http/src/client/mod.rs
- http/src/request/channel/reaction/create_reaction.rs
- http/src/request/channel/reaction/delete_all_reaction.rs
- http/src/request/channel/reaction/delete_reaction.rs
- http/src/request/channel/reaction/mod.rs
> http: require ReactionType for reaction methods (#181)

- standby/src/lib.rs
When iterating over the bystanders of an event being waited on, if the check didn't pass the sender that was taken from the bystander would never be put back. This means that the next time the bystander was going to be checked, the Standby struct would see it had no senders and would remove it. This means that if a check wasn't immediately satisfied on the first check that it would never successfully resolve and be removed.
A test has been included for supporting non-sequential bystander completions.
> standby: fix non-instant bystander waiting

- http/README.md
- http/src/lib.rs
Improve the docs' feature layout into sub-sections, making it clearer to read and easier to link to.
This is separated out from PR #204.
> http: improve feature layout of docs

- http/src/routing.rs
https://github.com/discord/discord-api-docs/commit/b9edace323c9df64c79f104d85984690ae4e2977
> Change delete_message_days to underscore for CreateBan

- README.md
- lavalink/Cargo.toml
- model/README.md
- model/src/lib.rs
- standby/Cargo.toml
- twilight/src/lib.rs
> project: update remaining branch names to trunk

- model/src/guild/mod.rs
These logs don't need to be here. My bad. :(
> model/guild: remove logs that made it through #200

- http/src/client/mod.rs
- http/src/request/get_gateway.rs
- http/src/request/get_gateway_authed.rs
- http/src/request/get_voice_regions.rs
- http/src/request/user/create_private_channel.rs
- http/src/request/user/get_current_user.rs
- http/src/request/user/get_current_user_connections.rs
- http/src/request/user/get_current_user_guilds.rs
- http/src/request/user/get_current_user_private_channels.rs
- http/src/request/user/get_user.rs
- http/src/request/user/leave_guild.rs
- http/src/request/user/mod.rs
- http/src/request/user/update_current_user.rs
As of this PR, there are 246 more missing docs warnings in twilight-http.
> http: document request/user and request/*.rs

- gateway/src/shard/error.rs
- gateway/src/shard/processor/impl.rs
Handle invalid intents (code 4013) and disallowed intents (code 4014) errors from Discord, and log them when they happen with information with the shard ID.
Here's an example log, where I configured the "guild presences" intent but didn't enable it in the bot's privileged gateway intents settings:
```
> Got close code: Some(CloseFrame { code: Library(4014), reason: "Disallowed intent(s)." }).
> At least one of the provided intents for shard 0 are disallowed
```
When one of these errors is encountered, the shard processor will shutdown.
Closes #235.
> gateway/shard: handle bad intents

- gateway/src/shard/config.rs
- gateway/src/shard/processor/impl.rs
the presence was not being passed to the shard from the config, fixes #256
> fix initial precense not being passed in the identify payload

- http/src/request/channel/message/create_message.rs
> http docs: fix channel/message/create_message#attachments

- builders/src/embed.rs
> builders/embed: attachment://, embed limits

- http/src/client/builder.rs
- http/src/client/mod.rs
In the HTTP client, combine the `skip_ratelimiter` and `ratelimiter` fields into one. This can just be done by turning the `Ratelimiter` into an `Option<Ratelimiter>`.
Closes #274.
> http/client: combine skip ratelimiter field

- .github/workflows/doc.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- .github/workflows_disabled/audit.yml
The PR unifies formatting, used actions and adds more caching.
- Unify formatting and used actions
- `actions/cache@v2` supports multiple glob patterns
- Use the rustc-hash from `rustc -V` for the cache key.
- Setup caching for the clippy & doc builds workflows.
> actions: unify workflows and setup more caches

- http/src/request/guild/update_guild.rs
#331 revert had a bad merge where it switched some lines around. This is one I could find, but tomorrow I will comb for more.
> http: fix update_guild merge

- .github/workflows/test.yml
Build matrix
package:
- gateway
- http
- twilight
- lavalink
features:
- native
- rustls
- simd-json
`simd-json` builds fixed by #334
> actions: add build matrix for tls and json features

- gateway/src/cluster/impl.rs
Make the return type of `Cluster::down_resumable` consistent with the parameter type taken by `ClusterConfigBuilder::resume_sessions`. The returned HashMap is keyed by the shard ID with its session resume information. Only shards that are resumable are included.
> gateway/cluster: make down_resumable consistent

- gateway/src/shard/processor/socket_forwarder.rs
In the SocketForwarder, import `std::time::Duration` instead of referencing it via its FQN.
> gateway/socket_forwarder: import duration

- builders/Cargo.toml
- cache/base/Cargo.toml
- cache/in-memory/Cargo.toml
- cache/redis/Cargo.toml
- cache/trait/Cargo.toml
- command-parser/Cargo.toml
- gateway/Cargo.toml
- gateway/examples/cluster/Cargo.toml
- gateway/examples/intents/Cargo.toml
- gateway/examples/metrics/Cargo.toml
- gateway/examples/queue/Cargo.toml
- gateway/examples/request-members/Cargo.toml
- gateway/examples/shard/Cargo.toml
- http/Cargo.toml
- http/examples/allowed-mentions/Cargo.toml
- http/examples/get-message/Cargo.toml
- http/examples/proxy/Cargo.toml
- model/Cargo.toml
- twilight/Cargo.toml
- utils/mention/Cargo.toml
Update the authors of all of the crates to "Twilight Contributors".
> project: update crate authors

- model/src/gateway/event/dispatch.rs
Add "GIFT_CODE_UPDATE" to the variants in the `DispatchEvent` deserialization implementation.
A test has been added for the variant.
This is a continuation of #278 since that accidentally missed adding it to the `DeserializeSeed` implementation. A note has been added to the enum to add an implementation when a new variant is added.
> model/dispatch: add gift code update deser

- gateway/Cargo.toml
- model/Cargo.toml
Update the dependencies of all crates.
gateway:
- async-tungstenite: 0.7 -> 0.8
model:
- serde-value: 0.6 -> 0.7
All upgrades don't require any changes for us.
> project: update dependencies

- cache/in-memory/src/updates.rs
- model/src/gateway/payload/member_update.rs
cf. https://github.com/discord/discord-api-docs/pull/1858
> [model] Guild member update now always contains joined_at

- cache/in-memory/src/lib.rs
- cache/in-memory/src/updates.rs
Properly track the IDs of channels within a guild via the `guild_channels` map. When a channel was added or updated, the sets within the map weren't being updated to insert the channel ID.
Tests have been added for ChannelCreate and ChannelUpdate event updates.
> cache/in-memory: track guild channel IDs

- cache/in-memory/src/updates.rs
- model/src/gateway/payload/channel_pins_update.rs
- model/src/gateway/payload/member_chunk.rs
- model/src/gateway/payload/message_delete.rs
- model/src/gateway/payload/message_delete_bulk.rs
- model/src/gateway/payload/message_update.rs
- model/src/gateway/payload/presence_update.rs
- standby/src/lib.rs
Also updates a guild id to not be optional.
> Update models to include guild id

- http/src/api_error.rs
Handle API message errors. By the looks of it through testing, this can only ever contain an "embed" list key that only ever contains "fields".
A test has been added.
Closes #371.
> http/api_error: handle message errors

- gateway/Cargo.toml
- gateway/README.md
- gateway/src/lib.rs
> Add support for using cloudflare_zlib

- standby/src/lib.rs
In Standby, instead of early returning once a message create or reaction add has been processed by their handlers, allow guild and generic event handlers to process them. Similarly, allow generic event handlers to process all events, including guild events.
A test has been added.
Closes #402.
> standby: process events through all handlers

- README.md
- command-parser/README.md
- command-parser/src/lib.rs
- gateway/README.md
- gateway/src/lib.rs
- http/README.md
- http/src/lib.rs
- lavalink/README.md
- lavalink/src/lib.rs
- model/README.md
- model/src/lib.rs
- standby/README.md
- standby/src/lib.rs
- twilight/src/lib.rs
- utils/embed-builder/README.md
- utils/embed-builder/src/lib.rs
- utils/mention/README.md
- utils/mention/src/lib.rs
Add the server invite to the READMEs in the badges section.
It looks like this:
> project: add server invite to readmes

- lavalink/Cargo.toml
> lavalink: update dependencies

- gateway/src/cluster/builder.rs
- gateway/src/cluster/config.rs
- gateway/src/cluster/impl.rs
- gateway/src/cluster/mod.rs
- gateway/src/event.rs
- gateway/src/lib.rs
- gateway/src/queue/large_bot_queue.rs
- gateway/src/queue/mod.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/impl.rs
Document everything in the gateway, updating much of the old documentation and adding documentation where it was missing.
> gateway: document everything

- standby/Cargo.toml
- standby/src/futures.rs
- standby/src/lib.rs
In the `twilight-standby` crate, test implementations with `static_assertions`.
> standby: test with static_assertions

- CNAME
Add a CNAME file pointing to the domain, twilight.rs.
> project: add cname file

- gateway/src/shard/processor/impl.rs
Change the tracing line emitting received JSON from a DEBUG to a TRACE.
> gateway/shard: make json payload debug line trace

- http/src/client/mod.rs
Use a UserId instead of a u64.
Split off from #478.
> Use UserId for GetUser

- http/src/client/mod.rs
- http/src/request/channel/delete_channel_permission.rs
- http/src/request/channel/delete_channel_permission_configured.rs
- http/src/request/channel/mod.rs
- Make DeleteChannelPermission work the same way as the Update
> Make DeleteChannelPermission work the same way as the UpdateChannelPermission

- cache/in-memory/Cargo.toml
- command-parser/Cargo.toml
- gateway/Cargo.toml
- http/Cargo.toml
- lavalink/Cargo.toml
- model/Cargo.toml
- standby/Cargo.toml
- twilight/Cargo.toml
- utils/embed-builder/Cargo.toml
- utils/mention/Cargo.toml
Fill out the Cargo.toml files for each crate, adding in descriptions, categories, and linking to each crate's section on the `twilight.rs` website as the homepage.
> project: fill out cargo.toml's

- cache/in-memory/Cargo.toml
- cache/in-memory/README.md
- cache/in-memory/src/lib.rs
Document the crate in a style similar to that of others by writing a summary, installation instructions, and an example. Additionally, rewrite a little about the design of the cache.
Closes #467. This is also a part of #459.
> cache/in-memory: document crate, design

- http/src/client/mod.rs
- http/src/request/channel/reaction/create_reaction.rs
- http/src/request/channel/reaction/delete_all_reaction.rs
- http/src/request/channel/reaction/delete_reaction.rs
- http/src/request/channel/reaction/mod.rs
just easier to make if there are no redundant properties to pass in
> add ReactionType to http module without redundant animated property

- gateway/src/shard/processor/impl.rs
Deserialize the ready event only once. Ready events were being specially handled and deserialized only partially by the shard to avoid unnecessarily deserializing the rest if the user wants them. When using `simd-json` it will modify the input, rendering it unusable when deserializing a second time when emitting the full ready. This deserializes it as a full ready event every time, making it deserialized only once.
Closes #491.
> gateway/shard/processor: deserialize ready once

- README.md
- cache/in-memory/README.md
- cache/in-memory/src/lib.rs
- command-parser/README.md
- command-parser/src/lib.rs
- gateway/README.md
- gateway/src/lib.rs
- http/README.md
- http/src/lib.rs
- lavalink/README.md
- lavalink/src/lib.rs
- model/README.md
- model/src/lib.rs
- twilight/src/lib.rs
- utils/embed-builder/README.md
- utils/embed-builder/src/lib.rs
- utils/mention/README.md
- utils/mention/src/lib.rs
Prepare version 0.1 for publishing on crates.io.
Closes #459. Don't merge until everything else is ticked off on it.
> project: prepare 0.1 for publishing

- http/CHANGELOG.md
- http/Cargo.toml
Changelog:
Fixes
- Handle webhooks with tokens in path parsing ([#495] - [@AEnterprise])
[@AEnterprise]: https://github.com/AEnterprise
[#495]: https://github.com/twilight-rs/twilight/pull/495
> http: bump to v0.1.1

- gateway/Cargo.toml
- gateway/src/cluster/builder.rs
- gateway/src/cluster/config.rs
- gateway/src/cluster/impl.rs
- gateway/src/event.rs
- gateway/src/listener.rs
- gateway/src/queue/large_bot_queue.rs
- gateway/src/queue/mod.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/config.rs
- gateway/src/shard/event.rs
- gateway/src/shard/impl.rs
- gateway/src/shard/json.rs
- gateway/src/shard/processor/heartbeat.rs
- gateway/src/shard/sink.rs
- gateway/src/shard/stage.rs
Add tests for all public types in the gateway crate via the `static-assertions` crate.
> gateway: add static-assertions tests

- http/src/client/mod.rs
- http/src/request/get_user_application.rs
- http/src/request/mod.rs
- http/src/routing.rs
allows to retrieve the application info for the current bot. the model for this already existed
> http: support /oauth2/applications/@me endpoint

- gateway/src/shard/processor/impl.rs
Add a multiplying delay when performing a reconnect on a shard. The reconnect will first wait one second, and then two, and then four, etc., up to 128 seconds.
Closes #446.
> gateway/shard: add reconnect delay

- cache/in-memory/src/lib.rs
Add a method to get the set of channels in a guild.
> Add method to fetch sets describing guilds in the cache

- .github/workflows/doc.yml
- .github/workflows/publish.yml
- util/Cargo.toml
This should build the `twilight-util` docs with all features for `gh-pages` and docs.rs
> util: build docs with all features

- .github/workflows/lint.yml
- .github/workflows/test.yml
The action is pretty verbose for the simple task it is doing here.
> actions: replace actions-rs/cargo with run steps

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This removes the need to delete them before submitting.
> project: turn issue templates into comments

- http/src/request/channel/webhook/execute_webhook.rs
The execute webrequest endpoint returns either 200 or 204 depending on
the value of the `wait` argument.
This lead to it not working correctly with `request` because that
method always needs a return body. The solution is to switch between
`request` and `verify` depending on the value and mapping the unit
return value to None.
> http: fix execute_webrequest not working correctly without wait.

- cache/in-memory/src/lib.rs
- gateway/src/shard/processor/impl.rs
- http/src/request/channel/reaction/mod.rs
- mention/src/parse/impl.rs
- model/src/guild/permissions.rs
Added the deny line and ran cargo fix --edition-idioms
> project: fix clippy warning & rust edition idioms

- gateway/src/shard/impl.rs
- gateway/src/shard/processor/heartbeat.rs
- gateway/src/shard/stage.rs
Add serialize & deserialize macros to the Information struct so <cluster>.info() can be serialized/deserialized.
> feat(gateway): add deserialize, serialize to resume information

- http/src/request/guild/create_guild/builder.rs
- http/src/request/guild/create_guild/mod.rs
Also adds related methods to the `CreateGuild` builder
> http: add new fields to CreateGuildFields

- gateway/src/shard/impl.rs
Adds JSON serialization/deserialization to the ResumeSession struct. Forgot to add this in #621
> fix(gateway): add serialization to ResumeSession struct

- .github/workflows/test.yml
> actions: add build job for MSRV

- cache/in-memory/src/lib.rs
`InMemoryCache::clear` cleared some fields but not all. All fields are now cleared. A note has been added to the list of fields about adding to the `clear` method when a new field is added.
Closes #630.
> fix(cache/in-memory): clear all fields

- http/src/api_error.rs
The `Retry-After` ratelimit error body value provided by Discord is a float, unlike in the header where it's an integer.
Closes #611.
> fix(http/api_error): make retry_after an f64

- gateway/src/cluster/impl.rs
- http/src/request/validate.rs
- lavalink/examples/basic-lavalink-bot/src/main.rs
[PR #664]'s CI failed due to [Clippy erroring] on some lints that haven't showed up before. This is the `manual_range_contains` lint.
[Clippy erroring]: https://github.com/twilight-rs/twilight/runs/1630617881
[PR #664]: https://github.com/twilight-rs/twilight/pull/664
> Fix new clippy lints

- http/src/routing.rs
- model/src/guild/audit_log/mod.rs
Contains minor bugfixes that partially address #616
> fix(http, model): properly construct audit log route; expose AuditLog fields

- model/src/channel/embed/mod.rs
- model/src/channel/embed/video.rs
> feat(model): add proxy_url field to `EmbedVideo`

- model/src/invite/guild.rs
- model/src/invite/mod.rs
- model/src/invite/welcome_screen.rs
> feat(model): add `WelcomeScreen` to `InviteGuild`

- http/src/client/builder.rs
- http/src/client/mod.rs
Add the ability for the user to set a group of headers that will be sent on every request
> feat(http): add default headers

- http/src/request/guild/get_guild_prune_count.rs
The way this is written will always cause the check to fail. This brings it in line with create_guild_prune.rs
> Fix incorrect boolean in days check for get_guild_prune_count

- gateway/Cargo.toml
- gateway/README.md
- gateway/src/lib.rs
- gateway/src/shard/processor/impl.rs
- gateway/src/shard/processor/mod.rs
> Optional compression, closes #629

- http/src/request/guild/get_guild_prune_count.rs
- http/src/request/validate.rs
https://github.com/discord/discord-api-docs/commit/cb2a289b1819bcd180b7ffd0d66d3a5a5536127e
> Limit guild prune max days to 30

- http/src/request/channel/message/create_message.rs
- model/src/channel/message/mod.rs
- model/src/channel/message/reference.rs
https://github.com/discord/discord-api-docs/commit/84104023837d038fe6dff4674e2f650b32760a99
> Document `fail_if_not_exists`

- http/src/request/channel/allowed_mentions.rs
- http/src/request/channel/webhook/execute_webhook.rs
> Add allowed mentions builder to `ExecuteWebhook`

- mention/src/lib.rs
> Remove MentionFormat re-export

- .github/workflows/lint.yml
Shouldn't be marked as Required but would allow to fix these before we run into a stable update that marks all PRs unmergable.
> chore: Add a beta clippy CI

- model/src/channel/channel_type.rs
- model/src/channel/mod.rs
- model/src/channel/voice_channel.rs
Support guild stage voice channels. This is denoted by channel type 13. This is, in effect, a voice channel, but with a separate channel type to mark that it has additional external capability.
This is a part of #746.
> Support stage voice channel type

- model/src/channel/message/kind.rs
https://github.com/discord/discord-api-docs/commit/db1fa79b8fc016769c98b229e2f2dedf10b0bc2e
> Add message types 16 and 17

- model/src/channel/message/kind.rs
- model/src/guild/system_channel_flags.rs
https://github.com/discord/discord-api-docs/commit/6b816cb6f542ea813c8f4dab797fc0e7ce203305
> feat(model): add message type 22

- gateway/src/cluster/scheme.rs
- http/src/client/mod.rs
- http/src/request/guild/get_guild_vanity_url.rs
- model/src/gateway/payload/ready.rs
> Fix more clippy from merge

- model/src/user/flags.rs
https://github.com/discord/discord-api-docs/commit/9293f0d490ac6acf9d627e429e5a8131b303b528
> fix(model): remove system user flag

- http/src/request/channel/update_channel.rs
- model/src/channel/mod.rs
- model/src/channel/video_quality_mode.rs
- model/src/channel/voice_channel.rs
https://github.com/discord/discord-api-docs/commit/3ae41f2a5b6ba1c9356919e16a41e91db04713ca
> feat(model): add `VoiceChannel::video_quality_mode`

- model/src/channel/attachment.rs
https://github.com/discord/discord-api-docs/commit/ab7a51ffea418a354562404da51ee609f8bca539
> feat(model): `Attachment::content_type`

- README.md
- lavalink/README.md
- lavalink/src/lib.rs
- lavalink/src/model.rs
- twilight/src/lib.rs
> docs: update freyacodes' github link

- http/src/request/channel/reaction/get_reactions.rs
- http/src/routing.rs
https://github.com/discord/discord-api-docs/commit/f72b084773d4d3989fb19be4fb4d9cf276a1e6b3
> fix!(http): remove `GetReactions::before`

- README.md
- twilight/src/lib.rs
Update the readme to mention 0.4 instead of 0.3.
> Update readme to mention 0.4

- model/src/user/flags.rs
https://github.com/discord/discord-api-docs/commit/55cd3d71082e9dc31cbd007a6e74b1cd6a82beeb
> feat(model): add discord certified moderator flag

- http/src/api_error.rs
https://github.com/discord/discord-api-docs/commit/1418344a6d6eb365cb6fc37b447a456f5099c3d0
https://github.com/discord/discord-api-docs/commit/e528321ccf69447a03ff0f6a1ebd2e72f2ace35f
> feat(http): more json error codes

- http/src/client/mod.rs
- http/src/request/channel/webhook/get_webhook_message.rs
- http/src/request/channel/webhook/mod.rs
- http/src/routing.rs
https://github.com/discord/discord-api-docs/commit/94d57ea3ed3b2c42cbbb488c9f93d2bc81706cff
> feat(http): `Client::get_webhook_message`

- http/src/api_error.rs
This change actually needs to go on the main branch. Closed #843 in
favor of this PR.
> chore(main): fix clippy

- http/src/request/channel/webhook/update_webhook_message.rs
This is something that I missed in #797.
> fix(http): fix logic in update_webhook_message

- http/src/request/channel/invite/create_invite.rs
- model/src/invite/mod.rs
- model/src/invite/target_type.rs
> fix!(http,model): remove deprecated invite methods and model

- gateway/src/shard/processor/impl.rs
Remove the max message size limit on WebSocket connections. The max frame size limit was removed in PR #730, but the max message size limit was not removed. ~~We've seen someone encounter hitting this message size limit in production.~~ This was user error.
The WebSocket configuration is no longer constructed with spread default values so that we can configure new fields.
> Remove shard connection message size limit

- http/src/request/validate.rs
> enhancement(http): Loosen channel name minimum length to one character

- cache/in-memory/src/updates.rs
If a user wanted to update user & member states before (but didn't want to cache messages) on MESSAGE_CREATE they'd need to specify ResourceType::MESSAGE and then set `.message_cache_size(0)`. That to me seems backwards and for me personally I did not expect it
> Update member & user on message_create in a more obvious way

- model/src/guild/audit_log/change_key.rs
- model/src/guild/audit_log/event.rs
> Stage Instance audit log events

- model/src/channel/webhook.rs
> Webhook::application_id

- http/src/api_error.rs
> Add new API error codes

- http/src/request/channel/message/create_message.rs
> Remove deprecated `CreateMessage` methods

- http/src/error.rs
- http/src/lib.rs
> Remove HTTP result

- http/src/api_error.rs
> Rename error code 20031

- model/src/channel/webhook.rs
> `Webhook::url`

- http/src/api_error.rs
> feat(http): thread error codes

- model/src/guild/permissions.rs
> feat(model): `Permissions::MANAGE_THREADS`

- http/src/request/channel/webhook/execute_webhook.rs
> feat(http): `ExecuteWebhook::thread_id`

- gateway/src/shard/processor/compression/inflater.rs
Add tests for the inflater, checking the state of buffers as they're added to and used to deflate messages.
Closes #486.
> Add tests for gateway inflater

- model/src/channel/mod.rs
This has been tested.
Fixes #1014.
> fix(model): deserialize `rtc_region`

- gateway/src/shard/emitter.rs
- http/src/request/validate.rs
- mention/src/parse/impl.rs
Fix broken intradoc links of internal documentation that is not publicly exposed.
Once this is merged I'll make a separate PR to start testing for this in CI.
> Fix private documentation intradoc links

- http/src/request/channel/update_channel.rs
Looks like a small oversight. I can create an issue for it if you prefer.
> Fix empty body on update_channel

- gateway/src/shard/impl.rs
> Fix typo in docs

- http/src/request/application/create_global_command.rs
- http/src/request/application/create_guild_command.rs
- http/src/request/application/set_global_commands.rs
- http/src/request/application/set_guild_commands.rs
- http/src/request/application/update_global_command.rs
- http/src/request/application/update_guild_command.rs
~~Untested~~ Tested
Closes #1036
> Create, Set & Update commands return commands

- gateway/src/cluster/impl.rs
The cluster used to wrap it's `HashMap<u64, Shard>` in a Mutex, this is no longer necessary (was included in the initial cluster release).
> refactor(gateway): remove mutex from cluster

- cache/in-memory/Cargo.toml
- command-parser/Cargo.toml
- embed-builder/Cargo.toml
- gateway/Cargo.toml
- gateway/queue/Cargo.toml
- http/Cargo.toml
- lavalink/Cargo.toml
- mention/Cargo.toml
- model/Cargo.toml
- standby/Cargo.toml
- twilight/Cargo.toml
- util/Cargo.toml
like #1095 but without stripping `default-features = false`
> correct tokio features and sync layout

- http/benches/application_command_permissions.rs
- http/src/request/channel/update_channel.rs
- http/src/request/guild/create_guild_channel.rs
Fixes some warnings I found while setting up VS Code.
> chore: fix various warnings

- .github/workflows/doc.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
This mainly removes unneeded cache & rust stable installations, speeding up CI
> workflow updates

- http-ratelimiting/src/request.rs
- http/src/routing/route.rs
Taken from #1191 and should match the Discord API Docs on this matter (https://discord.com/developers/docs/resources/guild-template).
> http: Fix template paths

- model/src/guild/permissions.rs
Doc comment is copied from Discord's docs.
Closes #1173
> chore(model): `START_EMBEDDED_ACTIVITIES` permission

- model/src/oauth/current_application_info/flags.rs
> chore(model): add 2 application flags

- model/src/guild/system_channel_flags.rs
Additionally documents the entire struct.
Fixes #1239.
> chore(model): new system channel flag

- model/src/user/flags.rs
> chore(model)!: remove deprecated user flags

- model/src/application/command/option.rs
> fix(model): serialize correct order & serde typo

- cache/in-memory/src/event/member.rs
- cache/in-memory/src/model/member.rs
> enhancement(cache): joined_at required

- gateway/src/shard/builder.rs
> fix(gateway)!: large threshold default is 50

- lavalink/src/http.rs
> lavalink: Fix deserializing LoadedTracks responses for playlists without a selected track

- embed-builder/src/author.rs
- embed-builder/src/builder.rs
- http/src/request/validate.rs
- model/src/channel/embed/author.rs
- model/src/channel/embed/image.rs
- model/src/channel/embed/mod.rs
- model/src/channel/embed/thumbnail.rs
The `EmbedThumbnail:url`, `EmbedImage::url` and `EmbedAuthor::name` are now required fields.
Closes: #1148
> fix!: new required embed fields

- util/src/snowflake.rs
#1230 forgot to add this implementation
> fix(util/snowflake): impl `Snowflake` for `CommandVersionId`

- http-ratelimiting/src/in_memory/bucket.rs
Revert "fix(http-ratelimiting): rework started at time (#1348)".
This reverts commit 67adafad73836cb4d360c42df9c4959f8edb4232.
This PR is causing overflows on some types of requests.
> chore(http-ratelimiting): revert #1348

- http-ratelimiting/src/request.rs
- http/src/client/mod.rs
- http/src/request/user/get_current_user_guild_member.rs
- http/src/request/user/mod.rs
- http/src/routing/route.rs
- http/src/routing/route_display.rs
> feat(http): add get current user guild member endpoint

- model/src/guild/audit_log/change.rs
- model/src/guild/audit_log/change_key.rs
> feat(model): add `Invitable` audit log change

- .github/labeler.yml
> ci: add new label schema to labeler

- gateway-queue/src/lib.rs
Adds a queue that immediately allows any requests. Part of #1488
> feat(gateway-queue): Add NoOpQueue

- gateway/Cargo.toml
> refactor(gateway)!: Remove `compression` feature flag

- .gitignore
- validate/src/embed.rs
- validate/src/message.rs
continuing #1498, this is one of the ways to achieve this without being breaking, but i have some concerns about it which i have commented in the lines changed.
> feat(validate): validate embed length

- http/src/client/mod.rs
- http/src/request/guild/get_guild_welcome_screen.rs
> docs(http): welcome screen permissions note

- model/src/channel/message/interaction.rs
> feat(model): add `MessageInteraction::member`

- http/src/request/guild/member/update_guild_member.rs
> docs(http): note about timing out administrator

- model/src/channel/message/interaction.rs
> test(model): add `MessageInteraction` test

- cache/in-memory/src/event/voice_state.rs
- cache/in-memory/src/model/voice_state.rs
~~Some of the tests are uglier, recommendations are welcome.~~
> refactor(cache)!: Remove `Option` around known voice fields

- cache/in-memory/src/event/interaction.rs
- model/src/application/command/option.rs
- model/src/application/interaction/application_command/data/mod.rs
- model/src/application/interaction/application_command/data/resolved.rs
- model/src/application/interaction/mod.rs
- validate/src/command.rs
This pull-request adds support for the new Attachment command option
closes #1523
> feat(model): New command option: Attachment

- cache/in-memory/src/event/stage_instance.rs
- model/src/channel/stage_instance/mod.rs
> feat(model,cache/in-memory): add `StageInstance::guild_scheduled_event_id`

- model/src/guild/permissions.rs
> refactor(model)!: rename `Permissions::START_EMBEDDED_ACTIVITIES` to `USE_EMBEDDED_ACTIVITIES`

- model/src/oauth/current_application_info/flags.rs
> docs(model): document `ApplicationFlags`

- gateway/src/cluster/builder.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/processor/impl.rs
- model/src/gateway/payload/outgoing/identify.rs
> refactor(model)!: remove `IdentifyProperties` referrer

- model/src/application/interaction/application_command/option.rs
This internal function has an odd name, rename it and refactor it into a method.
> refactor(model): Rename `make_unexpected` to `as_unexpected`

- model/src/application/interaction/application_command/mod.rs
- model/src/application/interaction/application_command_autocomplete/mod.rs
- model/src/application/interaction/message_component/mod.rs
- model/src/application/interaction/mod.rs
- model/src/application/interaction/modal/mod.rs
- model/src/application/interaction/ping.rs
Another try at achieving the goals of #1637. Includes consistency fix of relevant test.
> docs(model): Note expected type of `InteractionType`

- gateway/src/cluster/builder.rs
- gateway/src/lib.rs
- gateway/src/shard/builder.rs
- gateway/src/shard/config.rs
- gateway/src/shard/mod.rs
- gateway/src/shard/processor/impl.rs
- gateway/src/shard/tls.rs
Depends on ~~#1392~~, ~~#1482~~
> feat(gateway): Support non tls connections

- http/src/response/future.rs
Replace Self struct deconstruction with the `self` shorthand.
> refactor(http): replace self deconstruction with shorthand

- gateway-queue/src/day_limiter.rs
- http/src/response/future.rs
- model/src/application/command/permissions.rs
- standby/src/lib.rs
> fix: tracing feature remnants

- http/src/request/base.rs
- http/src/request/multipart.rs
Implement Clone on Request, allowing people to re-use built requests.
Related to #600.
> feat(http): implement clone on request

- .github/workflows/check-lib.yml
These steps take only seconds to complete.
> ci: check spelling and code format parallel to msrv

- model/src/channel/message/kind.rs
https://github.com/discord/discord-api-docs/pull/4860 and https://github.com/twilight-rs/twilight/issues/1709
> feat(model): Add AutoModerationAction (24) message type 

- http/src/client/mod.rs
- http/src/request/channel/thread/create_thread_from_message.rs
- http/src/request/channel/thread/update_thread.rs
> docs(http): remove more incorrect documentation

- http/src/client/interaction.rs
- http/src/client/mod.rs
- http/src/lib.rs
- http/src/request/application/command/create_global_command/chat_input.rs
- http/src/request/application/command/create_global_command/message.rs
- http/src/request/application/command/create_global_command/user.rs
- http/src/request/application/command/create_guild_command/chat_input.rs
- http/src/request/application/command/create_guild_command/message.rs
- http/src/request/application/command/create_guild_command/user.rs
- http/src/request/application/interaction/create_followup.rs
- http/src/request/application/interaction/update_followup.rs
- http/src/request/application/interaction/update_response.rs
- http/src/request/attachment.rs
- http/src/request/audit_reason.rs
- http/src/request/channel/invite/create_invite.rs
- http/src/request/channel/message/create_message.rs
- http/src/request/channel/message/update_message.rs
- http/src/request/channel/stage/update_stage_instance.rs
- http/src/request/channel/thread/create_thread_from_message.rs
- http/src/request/channel/thread/update_thread.rs
- http/src/request/channel/update_channel.rs
- http/src/request/channel/webhook/execute_webhook.rs
- http/src/request/channel/webhook/update_webhook_message.rs
- http/src/request/guild/ban/get_bans.rs
- http/src/request/guild/sticker/update_guild_sticker.rs
- http/src/response/future.rs
- http/src/routing.rs
> refactor(http): standardize clippy lints

- lavalink/src/http.rs
- lavalink/src/node.rs
Followup from #1783: [comment]
[comment]: https://github.com/twilight-rs/twilight/pull/1783#discussion_r891609385
> refactor(lavalink): replace an unwrap with expect

- cache/in-memory/src/event/interaction.rs
- model/src/application/interaction/application_command/mod.rs
- model/src/application/interaction/application_command_autocomplete/mod.rs
- model/src/application/interaction/message_component/mod.rs
- model/src/application/interaction/mod.rs
- model/src/application/interaction/modal/mod.rs
- standby/src/lib.rs
cf:
- https://discord.com/developers/docs/change-log#calculated-permissions-in-interaction-payloads,
- https://github.com/discord/discord-api-docs/pull/5131
closes #1804
> Add the app_permissions field on interactions

- model/src/application/command/option.rs
- util/src/builder/command.rs
> feat(model): backport #1825 - `CommandOption` max and min length

- twilight-http-ratelimiting/src/request.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/request/guild/mod.rs
- twilight-http/src/request/guild/update_guild_mfa.rs
- twilight-http/src/request/try_into_request.rs
- twilight-http/src/routing.rs
> feat(http): add `UpdateGuildMfa`

- twilight-http/src/request/channel/webhook/execute_webhook.rs
> feat(http): add `ExecuteWebhook::thread_name`

- twilight-http/src/request/channel/update_channel.rs
- twilight-http/src/request/guild/create_guild_channel.rs
Part of #1715.
Changelog
---------
`CreateGuildChannel`:
- update docs for `bitrate`
- add `default_auto_archive_duration`
- add `rtc_region`
- add `video_quality_mode`
`UpdateChannel`:
- update docs for `bitrate`
- add `rtc_region`
> feat(http): create/update channel updates

- twilight-model/src/application/interaction/application_command/option.rs
Fixes an issue where a focused autocomplete option (which is really a number) was deserializing as an ID (due to the design of `ValueEnvelope`). Now, if an option is focused, it will always deserialize its value as a String, since that is what Discord sends.
> fix(model): autocomplete focused options are always strings

- twilight-http-ratelimiting/src/in_memory/bucket.rs
Fixes a logic false positive with the `unused` lint.
> fix(http-ratelimiting): explicitly drop lock

- twilight-http/src/client/mod.rs
- twilight-http/src/request/guild/user/update_current_user_voice_state.rs
Closes: #1881
Reference: https://github.com/discord/discord-api-docs/pull/5261
> feat(http)!: `channel_id` is optional for `UpdateCurrentUserVoiceState`

- twilight-model/src/oauth/application_flags.rs
Reference: https://github.com/discord/discord-api-docs/pull/5222
Closes: #1887
> feat(model): add application command badge flag

- twilight-http/src/client/mod.rs
- twilight-http/src/request/guild/ban/create_ban.rs
- twilight-http/src/routing.rs
- twilight-validate/src/request.rs
Additionally the delete message days related functionality has been removed.
Reference: https://github.com/discord/discord-api-docs/pull/5219
Closes: #1883
> feat(http,validate)!: add create guild ban delete message seconds

- twilight-gateway/src/shard/processor/impl.rs
Fix URL parameters not getting set on subsequent connections to gateway URL's provided in the READY event.
This caused resumes to fail and thus initiating full reconnections.
> fix(gateway): fix reconnect handling of gateway query parameters

- examples/Cargo.toml
- examples/gateway-reshard.rs
Resharding is an often asked about feature, so I thought there should be an official example. The contents are pretty bare, like all examples, and although I think this should be improved, this PR did not feel like the appropriate time.
> docs(gateway): resharding example

- twilight-gateway/src/shard.rs
As discussed in the Twilight Discord channel.
> fix(gateway): zombied detection accept any event

- twilight-model/src/voice/voice_state.rs
Update the `VoiceState::suppress` field with clarified information.
API docs PR: https://github.com/discord/discord-api-docs/pull/5216
> docs(model): update voice state suppress field

- twilight-http-ratelimiting/src/request.rs
- twilight-http/src/client/mod.rs
- twilight-http/src/request/audit_reason.rs
- twilight-http/src/request/guild/get_guild_widget_settings.rs
- twilight-http/src/request/guild/mod.rs
- twilight-http/src/request/guild/update_guild_widget_settings.rs
- twilight-http/src/request/try_into_request.rs
- twilight-http/src/routing.rs
- twilight-model/src/guild/mod.rs
- twilight-model/src/guild/widget/mod.rs
- twilight-model/src/guild/widget/settings.rs
- twilight-model/src/id/anonymizable.rs
- twilight-model/src/id/mod.rs
Continued from #1487.
Closes #1466.
> feat(http,model)!: bring widgets up to date

- examples/gateway-reshard.rs
- twilight-gateway/src/shard.rs
Simplifies resharding code and #2002.
> feat(gateway): add `is_identified` helper method

- twilight-model/src/guild/role_tags.rs
> feat(model): add `guild_connections` attribute

- twilight-gateway/README.md
- twilight-gateway/src/stream.rs
Proposed from user feedback in the Twilight Discord server.
> docs(gateway): use `while let Some` in stream examples

- twilight-gateway/README.md
Discovered in a Discord support thread https://discord.com/channels/745809834183753828/1073767322529054822
> docs(gateway): correct zlib-simd feature flag name

- .github/workflows/check.yml
This seems to be necessary for the merge_queue to work
> Add merge_group to the triggers

- twilight-cache-inmemory/Cargo.toml
- twilight-cache-inmemory/src/config.rs
- twilight-gateway/Cargo.toml
- twilight-gateway/src/event.rs
- twilight-model/Cargo.toml
- twilight-model/src/channel/flags.rs
- twilight-model/src/channel/message/flags.rs
- twilight-model/src/gateway/intents.rs
- twilight-model/src/gateway/presence/activity_flags.rs
- twilight-model/src/guild/member_flags.rs
- twilight-model/src/guild/permissions.rs
- twilight-model/src/guild/system_channel_flags.rs
- twilight-model/src/oauth/application_flags.rs
- twilight-model/src/user/flags.rs
Updates bitflags to `2`. Bitflags crate changes: https://github.com/bitflags/bitflags/blob/main/CHANGELOG.md#whats-changed-5
> refactor(model, cache, gateway)!: update bitflags crate to v2

- twilight-model/src/guild/audit_log/event_type.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6071
> feat(model): add audit log monetization event types

- twilight-validate/src/command.rs
- twilight-validate/src/request.rs
The validation for several options was incorrect. This PR fixes that issue.
> fix(validate): improve validation of command option descriptions

- twilight-gateway/src/shard.rs
Originally reported in the [Discord suport server](https://discord.com/channels/745809834183753828/1141706497311658095), see the commit messages for implementation details.
> fix(gateway): defer queued commands until sent `Resume`

- twilight-http/src/client/mod.rs
the earlier docs have an irrelevant sentence
> docs(http): fix `Client::delete_messages`

- twilight-http/src/request/channel/stage/create_stage_instance.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/5687
> feat(http): add `guild_scheduled_event_id` to `create_stage_instance`

- twilight-lavalink/src/node.rs
I think this is overall prettier than ignoring the lint.
> fix(lavalink): clippy 1.75 lints

- twilight-gateway-queue/src/in_memory.rs
- **fixup(gateway-queue): don't panic after rebalancing**
- **refactor(gateway-queue): use more precise nouns & verbs**
> fix(gateway-queue): don't panic after rebalancing

- twilight-model/src/guild/permissions.rs
Ref:
- https://github.com/discord/discord-api-docs/pull/6913
> feat(model): add use external apps permission

- twilight-http/src/client/mod.rs
- twilight-model/src/id/marker.rs
This will cause our rustdoc CI to fail since it runs on nightly.
> fix(http, model): Fix nightly compiler and rustdoc warnings

- twilight-gateway/Cargo.toml
- twilight-http/Cargo.toml
This version is the first one to come with a critical bugfix for twilight. We can safely bump to a stable release later without making breaking changes.
> build(gateway, http): Update simd-json to 0.14.0-rc.3

- twilight-model/src/application/interaction/metadata.rs
> feat(model): Add new fields to interaction metadata

- twilight-gateway/src/shard.rs
When fixing a theoretical issue of `poll_flush_pending` immediately returning `Ready` (which should be handled by restarting as now done in `poll_send`) I found two nested loops to be incredibly ugly in the already too long `poll_next` method. Moving the nested loop into its own method improves readability and also allowed me to replace `if is_some; unwrap()` with pattern matching. 🎉
> refactor(gateway): split sending into a separate method

- book/src/versions/0.15/2023-09-10.md
This is mostly to make our spell check happy
> fix(book): small typo

- twilight-cache-inmemory/src/event/member.rs
> fix(cache): update `User` on `MemberUpdate`

- examples/gateway-reshard.rs
The use of `tokio::select!` needlessly complicates the example.
> refactor(example): remove select from gateway-reshard

- twilight-model/src/channel/message/component/mod.rs
- twilight-model/src/channel/message/component/thumbnail.rs
- twilight-util/src/builder/message/thumbnail.rs
- twilight-validate/src/component/component_v2.rs
Ran into another deserialization issue here on this. This is for #2422
> thumbnail descriptions are nullable (V2 Components)

- twilight-model/src/guild/permissions.rs
See https://discord.com/developers/docs/change-log#pin-permission-split
> feat(model): add pin messages permission
