twilight-rs/twilight

model/src/invite/metadata.rs

This field is removed cf. https://github.com/discordapp/discord-api-docs/commit/70390b75377098204ccda75e3a7240a1604c7639

[model] invite/metadata: Remove the `revoked` field

---

gateway/Cargo.toml
gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/event.rs
gateway/src/lib.rs
gateway/src/shard/heartbeat.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor.rs
gateway/src/shard/session.rs
gateway/src/shard/socket_forwarder.rs

Remove all of the unwraps, expects, and panics, using non-poisoning
alternatives like `futures::lock::Mutex` and opting to return errors
instead.

[gateway] remove all unwraps, expects, panics

---

gateway/Cargo.toml
gateway/src/cluster/config.rs
gateway/src/cluster/error.rs
gateway/src/cluster/impl.rs
gateway/src/shard/connect.rs
gateway/src/shard/error.rs
gateway/src/shard/heartbeat.rs
gateway/src/shard/session.rs
gateway/src/shard/stage.rs
http/Cargo.toml
http/src/client/mod.rs
http/src/error.rs
http/src/ratelimiting/error.rs
http/src/ratelimiting/headers.rs
http/src/routing.rs

Remove snafu as a dependency, opting to instead use `Result::map_err`
and `Option::ok_or` directly and implementing `std::error::Error` and
`std::fmt::Display` on error types directly.
This cuts 7 dependencies from the total tree.

[gateway/http] remove 'snafu' dependency

---

http/Cargo.toml
http/src/client/mod.rs
http/src/error.rs
http/src/ratelimiting/error.rs
http/src/ratelimiting/headers.rs
http/src/request/mod.rs
http/src/request/prelude.rs
http/src/routing.rs

Remove the 'http' and 'url' dependencies, because reqwest re-exports
both of these crates' types that we need.
Although this doesn't reduce our dependency tree (reqwest depends on
them), it does cut back the surface of our direct dependencies.
Blocks on #15.

[http] remove 'http' and 'url' dependencies

---

model/src/channel/embed/mod.rs
model/src/channel/reaction_type.rs
model/src/gateway/payload/voice_state_update.rs
model/src/gateway/presence/activity.rs
model/src/gateway/presence/activity_type.rs
model/src/gateway/presence/client_status.rs
model/src/gateway/presence/mod.rs
model/src/guild/member.rs

Fix some of the model definitions and fix compilation without the serde
feature.
- in `channel::embed::Embed`, gate the `color` serde attribute behind
the `serde-support` feature
- make `channel::ReactionType::Custom::id` optional
- make `gateway::payload::VoiceStateUpdate` a newtype around
`voice::VoiceState`
- add `gateway::presence::Activity::created_at` and `id` for custom
presences
- add `gateway::presence::ActivityType::Custom` (variant 4)
- add `guild::Member::hoisted_role`
Additionally, add tests for all of these using payloads that triggered
deserialization fails. These tests use `serde_test` for
implementation-agnostic accuracy.

[model] fix some incorrect model definitions

---

cache/in-memory/src/updates.rs
model/src/gateway/payload/member_add.rs

Make `gateway::payload::MemberAdd` a newtype around `guild::Member`,
because the payload includes no additional information.
A test case for this event has been added with one of the payloads that
failed deserialization.

[model] make gateway::payload::memberadd a newtype

---

cache/base/Cargo.toml
cache/base/src/lib.rs
cache/in-memory/Cargo.toml
cache/in-memory/src/config.rs
cache/in-memory/src/lib.rs
cache/in-memory/src/model/emoji.rs
cache/in-memory/src/model/mod.rs
cache/in-memory/src/updates.rs
cache/trait/Cargo.toml
cache/trait/src/lib.rs

Rework the `dawn_cache_trait::Cache` and `dawn_cache_trait::CacheUpdate`
traits to allow cache implementation pre-dispatches.
That doesn't make sense, but I couldn't make a catchy tagline for it.
Basically, the previous implementation of `CacheUpdate` required
implementing `CacheUpdate<T>` on the cache implementation, where T is
each event type.
This causes problems when a cache implementation wants to expose a
method which accepts any type that it has an update implementation for.
At least, I couldn't figure out how to do it. I don't think the type
system allows for it, and if it does it's wildly complex.
By using this method we switch from the trait definition:
```rust
pub trait UpdateCache<T>: Cache {
async fn update(&self, item: &T) -> Result<(), Self::Error>;
}
```
to:
```rust
pub …
```

[cache] rework 'cache' and 'cacheupdate'

---

.github/workflows/grcov.yml
.github/workflows/lint.yml
.github/workflows/test.yml
command-parser/src/lib.rs
gateway/src/lib.rs
http/src/lib.rs
model/src/lib.rs

Workspaces don't support `--all-features` in commands like `cargo test`,
which is a silent error and ignored, but fails our CI. To fix this,
remove the flag.
Additionally, switch out the deprecated `--all` for the new
`--workspace` flag, and remove the `cargo check` action since it's
covered by the `cargo test` action.

[ci] fix workspace use in actions

---

gateway/src/cluster/config.rs
gateway/src/shard/config.rs
gateway/src/shard/error.rs
gateway/src/shard/processor/impl.rs

Whenever a shard starts a connection, first get the connection from the
HTTP API via a `dawn_http` client. This ensures that the shard has the
most up-to-date URL for the gateway, which should not be hardcoded.
Closes #35.

[gateway] request gateway URL on every connection

---

gateway/src/shard/processor/impl.rs

Before starting a connection, put in a request to the queue and wait for
it to be realized. This will ensure that only one shard is connecting at
a time, due to the ratelimit around how often shards can connect.
Closes #34.

[gateway] queue shards before connecting

---

cache/in-memory/src/lib.rs

Deadlocsk would happen because it tried to aquire a lock while the
lock was locked in the scope.
----
#

Fix deadlocks in cache

---

cache/in-memory/src/shard.rs
model/src/channel/reaction_type.rs

Currently unicode reactions currently throw an error like:
```
Error receiveing gateway event: Some(Error("data did not match any variant of untagged enum ReactionType", line: 1, column: 777))
```

Unicode reactions does not deserialize

---

cache/in-memory/Cargo.toml
cache/in-memory/src/lib.rs
cache/in-memory/src/shard.rs
cache/in-memory/src/updates.rs
gateway/Cargo.toml
gateway/src/cluster/event.rs
gateway/src/cluster/impl.rs
gateway/src/listener.rs
gateway/src/queue.rs
gateway/src/shard/error.rs
gateway/src/shard/event.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/session.rs
gateway/src/shard/processor/socket_forwarder.rs
gateway/src/shard/sink.rs
http/Cargo.toml
http/src/client/mod.rs
http/src/error.rs
http/src/ratelimiting/bucket.rs
http/src/ratelimiting/mod.rs
http/src/request/guild/get_guild_vanity_url.rs

----
This PR makes it so we uses the `futures` crate in the whole repo
instead of using the sub crates `futures_*` this is to better ensure
compatability between crates and make it easier to update.
The real price to users will likely not be any problem as most will
have the futures crate somewhere in their dependency tree anyway.

Use the `futures` crate instead of multiple sub crates.

---

http/src/client/mod.rs
http/src/request/channel/create_pin.rs
http/src/request/channel/create_typing_trigger.rs
http/src/request/channel/delete_channel_permission.rs
http/src/request/channel/delete_pin.rs
http/src/request/channel/message/delete_message.rs
http/src/request/channel/message/delete_messages.rs
http/src/request/channel/reaction/create_reaction.rs
http/src/request/channel/reaction/delete_reaction.rs

Discord have some routes that returns a `204 No Content`
when it is correct, as some of them used the `request`
method they would fail when they tried to deserialize
a empty body into a `()`, this commit changes all the
routes that return a `204 No Content` to use the
`verify` method instead of `request`.

Fix some routes giving an error back for no reason

---

command-parser/src/parser.rs
gateway/src/queue.rs
model/src/channel/reaction_type.rs

This fixes #80, as if trim_start_matches returns anything at all,
it won't match, over starts_with sometimes matching shorter commands to
longer commands.

Match command with trim_start_matches over starts_with

---

gateway/Cargo.toml
gateway/examples/cluster/Cargo.toml
gateway/examples/metrics/Cargo.toml
gateway/examples/shard/Cargo.toml
http/Cargo.toml
http/examples/get-message/Cargo.toml
http/examples/proxy/Cargo.toml

This PR fixes that some examples would not compile as it need features.
They would still compiles from the workspace because the features,
got enabled by another crate.
----
#

Update some crates and fix examples.

---

command-parser/src/builder/command.rs
command-parser/src/builder/mod.rs
command-parser/src/casing.rs
command-parser/src/config.rs
command-parser/src/lib.rs

This pr restructures the command parser into smaller modules.
This change is fully cosmetic, and the only non cosmetic change
is the internal visibility of some fields.
This will make it so that it will error with an error like
the following if `add()` is not called on a command builder
```rust
warning: unused `dawn_command_parser::builder::command::CommandBuilder` that must be used
--> src/main.rs:36:9
|
36 |         config.command("today");
|         ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
= note: If `add` is not called the command will not be added.
```
This will make it harder to accidently forget to call it.

Restructure and `#[must_use]` on `CommandBuilder`

---

gateway/src/shard/impl.rs
gateway/src/shard/processor/connect.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/inflater.rs
gateway/src/shard/processor/socket_forwarder.rs

This change also led to a rewamp of some of the internal
as there was Arc that was getting invalidated, in a way
that no calls would work through it, so I had to change
some of the underlying structure to get the new session
up the call stack.
This is done with having a watch channel, a channel
that only hold the last value sent to it, and then updating
it to the new arc on every reconnect.
----
This includes the update to get it working with the latest version
of tokio-tungstenite.

Added proper support for resume.

---

gateway/src/shard/processor/impl.rs

The id was not correctly updated when resuming so
resumes would fail every other time, when saying
update it should be added that it just updates it
to the value it had before the resume.
This closes #95

Update the id when resuming

---

Cargo.toml
gateway/examples/queue/Cargo.toml
gateway/examples/queue/src/main.rs
gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs
gateway/src/queue.rs
gateway/src/shard/config.rs
gateway/src/shard/processor/impl.rs
http/src/lib.rs
model/src/lib.rs

Made the queue an Arc to make sure that all shards in a cluster use
the same queue.
Loosend a trait bound to make it easier to work with queues.
(fixes #101)
Also added a example with a very bad, but custom queue.
Also makes it so that it will only query the queue when doing a full reconnection.

Made queues work with clusters

---

model/src/gateway/payload/invite_create.rs
model/src/gateway/payload/update_status.rs

UpdateStatus was errorously sending a indentify instead of an status
update opcode.
INVITE_CREATE had some errors in the documentation, they have not yet
been fixed, but I have confirmation that this is correct.
----
OBS: This PR depends on https://github.com/dawn-rs/dawn/pull/103.
Note: This will probably ICE Clippy because of https://github.com/rust-lang/rust-clippy/issues/5238.

Fix to UpdateStatus and INVITE_CREATE

---

http/src/request/channel/message/create_message.rs

Only the second commit is a breaking change. Since Body implements `Into<Vec<u8>>` we simply increased the surface of accepted attachments 
Also I left the `payload_json` as `Vec<u8>` because that's likely to come from serde as a `Vec<u8>` and I personally don't see any use for setting that ever anyway

More ergonomic attachment handling for CreateMessage

---

Cargo.toml
http/examples/allowed-mentions/Cargo.toml
http/examples/allowed-mentions/src/main.rs
http/src/request/channel/message/allowed_mentions.rs
http/src/request/channel/message/create_message.rs
http/src/request/channel/message/mod.rs

It uses a builder that will make sure that it is
always valid at compile time. So you cannot for example
make it parse all users, and then afterwards parse specific
users.
Closes #113 
Thanks to @jhgg for the inspiration to the builder.

Add support for allowed mentions.

---

gateway/examples/queue/src/main.rs
gateway/src/queue.rs
gateway/src/queue/day_limiter.rs
gateway/src/queue/large_bot_queue.rs
gateway/src/shard/processor/impl.rs

This commit changes the queue trait so it can be used to support large
bots. It does that by adding a parameter to request that is the id of
the shard that you are requesting a identify on.
It also adds a new queue that is targeted large bots but can be used
with bot of all sizes if you set the queue size to be 1. This queue
also does bookkeeping so you do not go above the per day limit of
identifies.

Make the queue trait more specific and support for large sharding.

---

gateway/src/queue/day_limiter.rs
gateway/src/queue/large_bot_queue.rs

It was using that the reset was in remaining identifies ms.
Which does not make any sense.
It also adds a small amount of logging when starting it up.

Fix the LargeBotQueue to use correct argument for `next_reset`

---

.github/workflows/test.yml

this makes the github action cache the registry, index and target folders between builds so dependencies don't need to be compiled from scratch every time
cache key is dependant on the lock file so if anything to that changes it will not use the previous cache and instead build from scratch to prevent any possible corruption due to wrong caches

leverage caching to speed up build times

---

http/Cargo.toml
http/src/client/mod.rs
http/src/error.rs

This PR adds webhook url parsing to `http::Client`, allowing you to for example:
```rust
client.execute_webhook_from_url("https://discordapp.com/api/webhooks/123456")?
```
Adds `url = "2"` into Cargo.toml, but reqwest already depends on url so no new dependencies were added

Add webhook_*_from_url methods

---

model/src/gateway/payload/request_guild_members.rs

you can now also pass along if you want to get the member presences as well as request the info of a single user or list of users
the gateway will then sence a member_chunk with the requested info, tracking this is left to the caller
this does break binary compatibility for anyone already manually requesting a member update

add support for optional fields on the request-guild-members websocket message

---

http/examples/allowed-mentions/src/main.rs
http/src/client/config.rs
http/src/client/mod.rs
http/src/request/channel/message/allowed_mentions.rs
http/src/request/channel/message/create_message.rs

this add the "safety net" of being able to (partially or fully) disable pings for the http client on a global level but still allowing it to be overridden per message

add a global option for allowed mentions in the client

---

http/src/request/channel/update_channel.rs

_Finally_ figured out what was causing #149. Wew.
The docs state that the `name` and `type` fields can't be `null`, so this PR prevents the fields from serializing as such if they are not set.

Don't send null `name` and `type` fields for `UpdateChannel` route

---

cache/in-memory/src/lib.rs

Rational is primarly allowing developers to manually cache items outside
of events, such as holding a "cold cache" somewhere with user information
that might've not be cached by an event yet.
This would allow developers to manually cache items whenever they want/need.
This should be eventually documented, but for now:tm: leaving undocumented.

Make all cache methods public

---

.github/workflows/audit.yml

Run the Audit action only when the Cargo.toml file has been updated on
pushes and PRs, instead of on every commit. There isn't a practical
reason to run this on every commit.

actions: run audit only on cargo.toml update

---

README.md
http/src/client/mod.rs
twilight/src/lib.rs

Update to use the discord.com domain, because discordapp.com is now
soft-deprecated but without an official notice on the docs.

project: update to discord.com domain

---

http/Cargo.toml
http/README.md

Add two features to the `http` crate: `native` and `rustls`. `native`
enables `reqwest`'s `default-tls` feature, while `rustls` enables
`reqwest`'s `rustls-tls` feature. `native` is enabled by default.
This is a part of issue #124.

http: add native and rustls features

---

cache/in-memory/src/lib.rs
http/src/client/mod.rs
http/src/request/guild/create_guild_prune.rs
http/src/request/guild/get_guild.rs
http/src/request/guild/get_guild_prune_count.rs
http/src/request/guild/get_guild_widget.rs
http/src/request/guild/mod.rs
http/src/request/guild/update_guild_widget.rs
http/src/routing.rs
model/src/gateway/payload/invite_create.rs
model/src/guild/mod.rs
model/src/guild/widget.rs
model/src/user/connection.rs

- Document optional Connection object fields.
discord/discord-api-docs#1466
- Update invite create event fields and example invite object.
discord/discord-api-docs#1438
- New member count fields on get guilds
discord/discord-api-docs#1528
- Add support for `include_roles` when pruning.
discord/discord-api-docs#1563
- Add `max_video_channel_users` to guilds.
discord/discord-api-docs#1512
- Rename guild embed to guild widget.
discord/discord-api-docs#1536

Updates for discord 2020-05-27

---

model/src/gateway/payload/mod.rs
model/src/gateway/payload/reaction_remove_emoji.rs

In the gateway's payload module, export the `reaction_remove_emoji`
module. The `payload` module already re-exports the
`ReactionRemoveEmoji` struct within it, but that struct contains a
`PartialEmoji` local to its module. The `PartialEmoji` wasn't
re-exported, so the type couldn't be named.
`PartialEmoji` isn't important enough to export from the `payload`
module, so this exports the `reaction_remove_emoji` module.
Also, this fixes a typo in `PartialEmoji`'s name from `ParitalEmoji`.

model/gateway: export reaction_remove_emoji

---

.github/workflows/audit.yml

This should drastically speed up CI times, as cargo-audit is currently the slowest task to run when it does run.
For information on how this works, see this:
https://github.com/actions-rs/install#tool-cache

Enable cargo-audit tool cache

---

http/Cargo.toml
http/src/api_error.rs
http/src/client/mod.rs
http/src/error.rs
http/src/lib.rs

When an error occurs, instead of just giving the user a slightly nested
response around a client/server error enum, provide an error variant
containing the status code, body, and parsed API error.
The API error contains an error code (a number, like 10001, 10002, or
30001) parsed as an enum and the description of the error provided by
the API.
In total, the type schema of a response error looks like this now:
```
Error::Response {
body: [ bytes... ],
error: ApiError {
code: ErrorCode,
message: String,
},
status: StatusCode,
}
```
Closes #28.

http: parse api errors in responses

---

cache/in-memory/src/updates.rs
http/Cargo.toml
http/src/client/mod.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/get_member.rs
model/src/gateway/payload/member_add.rs
model/src/gateway/payload/voice_state_update.rs
model/src/guild/member.rs
model/src/guild/mod.rs
standby/src/lib.rs

Change the `model::guild::Member`'s `guild_id` field from an
`Option<GuildId>` to just a `GuildId`. The reason that this was an
option before is because this was a naive serde-derived
(de)serialization implementation. The HTTP API doesn't return members
with guild IDs, but the gateway does. This made working with members
from the gateway awkward since you know the guild ID is there but had to
go through an extra pattern match to get it.
We can fix this by making a separate seeded deserializer implementation
if you already know the guild ID. The deserializer will just deserialize
into an intermediary member struct and create a real member with the
stored guild ID.
The `http` crate has been updated to do these deserializations and other
crates are updated to work with a guild ID that's …

model: make member guild ids always present

---

cache/in-memory/src/updates.rs
http/Cargo.toml
http/src/client/mod.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/get_member.rs
model/src/gateway/payload/member_add.rs
model/src/gateway/payload/voice_state_update.rs
model/src/guild/member.rs
model/src/guild/mod.rs
standby/src/lib.rs

Revert #180 for now due to not including support for guild members that
don't have a guild ID over the gateway.
Related to #42.
This reverts commit 3ea9cd53e93953eba0836af4adb462571ae34f27.

Revert "model: make member guild ids always present (#180)"

---

cache/in-memory/src/updates.rs

Add back the cache update implementation for
`twilight_model::gateway::event::Event`s, which was accidentally removed
by PR #177.

cache/in-memory: re-impl cache updates for events

---

http/Cargo.toml
http/src/client/mod.rs
http/src/request/channel/get_channel.rs
http/src/request/channel/invite/get_invite.rs
http/src/request/channel/message/get_message.rs
http/src/request/channel/webhook/get_webhook.rs
http/src/request/guild/ban/get_ban.rs
http/src/request/guild/emoji/get_emoji.rs
http/src/request/guild/get_guild_vanity_url.rs
http/src/request/guild/get_guild_widget.rs
http/src/request/guild/member/get_member.rs
http/src/request/mod.rs
http/src/request/prelude.rs
http/src/request/user/get_user.rs

When the user uses a retrieval request, like getting a user by ID, the future output is a `Result<Option<T>>`. The code to handle 404 response status codes didn't actually exist, so it'd always either be `Ok(Some(T))` or `Err(E)`.
This patch adds support for handling 404 responses and returning `Ok(None)` where encountered on select retrieval routes.
Here's an example of output:
```
Getting guild member for user 1
Ok(None)
Getting guild member for user 640434332485287936
Ok(Some(Member { deaf: false, guild_id: None, hoisted_role: Non.....
```
Closes #157.

http: add optional future outputs for requests

---

gateway/src/lib.rs
gateway/src/shard/processor/impl.rs
http/src/lib.rs

Fix stable clippy which introduced a regression into stable that gives
this error message for all awaits:
```
warning: used binding `_task_context` which is prefixed with an
underscore. A leading underscore signals that a binding will not be
used.
```
See clippy issue 5360.
Additionally, allow an unrelated clippy lint that's incorrect.

gateway,http: fix stable clippy

---

cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs

Closes #161. The `cache_voice_state` function of the in memory cache now returns an option, because the voice state updates don't always contain an `channel_id`. The new behavior is to act as before when it exists, and when it doesn't, it finds the full key of that now dead voice state and removes it from the cache so it doesn't fill up with dead voice states. 
One thing to consider is that is the `user_id` alone enough to look for the dead state's key? I didn't think that a user could be in more then one voice channel at once, so technically with dead states being removed it should be a "unique" key in the underlying `HashMap`.

Fix voice state cache panic

---

gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs
gateway/src/shard/config.rs
gateway/src/shard/impl.rs
gateway/src/shard/mod.rs
gateway/src/shard/processor/impl.rs

allows to close the shard without terminating the session and getting it's resume information
this info can then be passed on startup to the new cluster to resume instead of identify
note that while this correctly resumes bots can't receive these events due to twilight dropping events on startup

implement cold resuming

---

standby/src/lib.rs

Add `Send` bounds to the wait methods:
- `wait_for`
- `wait_for_event`
- `wait_for_message`
- `wait_for_reaction`

standby: add send bounds to wait methods

---

standby/Cargo.toml
standby/src/lib.rs

Add a lot of TRACE level logging to the standby crate, which can help users figure out application flow.

standby: add trace level logging

---

cache/in-memory/Cargo.toml

Remove the dependency on `twilight-gateway` from the `twilight-cache-inmemory` crate. This was accidentally left in after PR #177.

cache/in-memory: remove gateway dependency

---

.github/workflows/test.yml

Use the stable toolchain in the Test action, rather than the beta toolchain.

actions/test: use stable toolchain

---

gateway/src/shard/error.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/impl.rs

In the gateway's Shard, handle invalid authorization both early and during processing of the shard processor's loop.
While creating the shard, get the gateway URL from the HTTP API prior to creating the processor. This allows an early return if getting the gateway URL (such as due to invalid authorization) failed. Additionally, during the processing of the shard processor's loop, if a close frame with a 4004 error (invalid authorization) is encountered, remove all of the listeners for the shard and exit the loop.
Closes #152.

gateway/shard: handle invalid authorization

---

lavalink/examples/basic-lavalink-bot/src/main.rs
standby/Cargo.toml
standby/src/futures.rs
standby/src/lib.rs

In Standby, use DashMap for internal maps, which avoids the need for locking and many of the functions needing to be asynchronous.
The waiting methods, such as `Standby::wait_for`, now return futures which resolve to the same return type that they did before. "Voldemort types", or types that can't be named (such as async fns, or `impl Future`s), are sub-par due to needing to be boxed when stored somewhere. By having named structs, this can make handling futures more efficient for users.
This PR could have been separated into two, but that would have nearly doubled work and would end up in conflicts between the two, so it was simpler to combine them together.

standby: use dashmap, return future structs

---

README.md
gateway/examples/cluster/src/main.rs
gateway/examples/intents/src/main.rs
gateway/examples/metrics/src/main.rs
gateway/examples/queue/src/main.rs
gateway/examples/request-members/src/main.rs
gateway/examples/shard/src/main.rs
gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/shard/error.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/impl.rs
lavalink/README.md
lavalink/examples/basic-lavalink-bot/src/main.rs
lavalink/src/lib.rs
twilight/src/lib.rs

Separate the booting of a Shard (connecting to the gateway, aka "running") from the initialisation of the struct.
This means that this code:
```rust
let shard = Shard::new(config).await?;
```
is now:
```rust
let mut shard = Shard::new(config);
shard.start().await?;
```
This is useful for separating the concerns of state initialisation and the processing of an event loop.
Additionally, in the Cluster, instead of creating shards in `Cluster::up`, create the shards on initialisation in the `Cluster::new` method, which is now an async function due to being able to automatically retrieve the total shard count from the gateway.
This means that cluster code may look like:
```rust
let cluster = Cluster::new(config).await?;
let mut events = cluster.events().await;
let cluster_spawn = …
```

Gateway cluster shard creations

---

README.md
cache/in-memory/Cargo.toml
cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs
cache/trait/Cargo.toml
command-parser/Cargo.toml
gateway/Cargo.toml
gateway/src/cluster/impl.rs
gateway/src/listener.rs
gateway/src/queue.rs
gateway/src/queue/large_bot_queue.rs
gateway/src/shard/error.rs
gateway/src/shard/event.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/session.rs
gateway/src/shard/processor/socket_forwarder.rs
gateway/src/shard/sink.rs
http/Cargo.toml
http/src/error.rs
http/src/ratelimiting/bucket.rs
http/src/ratelimiting/mod.rs
lavalink/Cargo.toml
model/Cargo.toml
twilight/Cargo.toml
twilight/src/lib.rs

Reduce the selected features of dependencies, mostly by disabling all default features and only selecting what we need.
This reduces the unique dependency tree of the default feature build of the main 'twilight' crate by 2.
Closes #211.

project: reduce selected dependency features

---

README.md
gateway/README.md
gateway/src/lib.rs
http/README.md
http/src/lib.rs
model/README.md
model/src/lib.rs
twilight/src/lib.rs

Following issue #222, the HEAD branch for the repository was renamed to "trunk". This patch updates the documentation to point to the new branch name in dependency listings.

project: update docs to point to trunk branch

---

http/src/request/channel/invite/create_invite.rs
http/src/request/get_gateway_authed.rs

Make all of the HTTP request structs' initialisers non-public, i.e. `pub(crate)` instead. These are the requests for `CreateInvite`, which is created through the client, and `GetGatewayAuthed`, which is created via `GetGateway`.
Closes #219.

http: make request initialisers non-public

---

http/src/api_error.rs
http/src/client/mod.rs

Handle 429 (ratelimited) API errors during deserialisation. The format of the error is:
```json
{
"global": bool,
"message": "You are being rate limited.",
"retry_after": u64,
}
```
This is accomplished by making `ApiError` an enum instead of a struct, and having two variants: general API errors, and ratelimited errors.
Closes #214.

http: deserialise 429 ratelimited api errors 

---

gateway/Cargo.toml
gateway/src/shard/impl.rs

When the cluster would start a shard, it clones the shard to reduce the time it holds on to the map. The shard didn't hold everything behind an Arc, so some of the data would be cloned and, in *that new clone of the shard*, would be modified. This means that the shard temporarily cloned by the cluster would be in a different state from that of the one stored in the cluster's internal map.
To solve this, put everything behind an Arc. Since we need to lazily initiate some values of the shard after initialization, put it behind a OnceCell.

gateway/cluster: fix command dispatching

---

http/src/request/guild/member/get_member.rs

The following code in my project:
```rust
let maybe_member = match self.client().unwrap().guild_member(guild_id, user_id).await {
Ok(maybe_member) => maybe_member,
Err(e) => {
log::warn!(
"Failed to get guild member for guild_id {} and user_id {}: {}",
guild_id,
user_id,
e
);
None
}
};
```
Was failing with this log message:
```
[06-18-2020][6:39:44 PM][mc_server_wrapper::discord][WARN] Failed to get guild member for guild_id 694351600537567279 and user_id 153991028934705153: Given value couldn't be serialized
```
I dove into the library code to see what was up, and logging an error closer to the source revealed:
```
[06-18-2020][6:42:27 PM][twilight_http::request::guild::member::get_member][WARN] json error: invalid type: byte array, expected a map of member fields
```
But the response …

Fix response deserialization in `GetMember`

---

model/src/gateway/payload/guild_delete.rs

Simplify the `twilight_model::gateway::payload::GuildDelete::unavailable` field from an `Option<bool>` to a `bool` by defaulting the value to false.

model: simplify guild delete unavailable field

---

model/src/gateway/payload/member_chunk.rs
model/src/guild/member.rs
model/src/guild/mod.rs

Add a custom deserializer for `twilight_model::gateway::payload::MemberChunk`, which now special cases the members so a guild ID can be inserted.
A test containing a sample member chunk payload is included.
Closes #236.

model/gateway: add member chunk deserializer

---

gateway/Cargo.toml

In the gateway, enable the `std` feature for the `once_cell` dependency. We need this for our usage, and this would only work if somewhere else in the user's tree `once_cell`'s `std` feature was enabled.

gateway: enable once_cell's 'std' feature

---

model/src/channel/message/kind.rs
model/src/channel/message/mod.rs

Derive `serde_repr::{Deserialize_repr, Serialize_repr}` for the `channel::message::MessageType` type.
A test for message deserialization has been added.
Introduced in #243.
Fixes #250.

model/channel/message/kind: derive repr

---

model/src/gateway/payload/typing_start.rs

Fix the deserialisation of `twilight_model::gateway::payload::TypingStart` events with members, by making use of the `MemberDeserializer`. This adds a custom deserializer to do this.
Additionally, tests for typing start events with and without members have been added.
Closes #238.

 model/typing_start: fix member deserialization

---

gateway/DEVELOPMENT.md
gateway/examples/shard/src/main.rs
gateway/src/shard/processor/impl.rs
gateway/tests/test_shard_state_events.rs

Emit the `twilight_model::gateway::event::shard` events when something happens to the state of the shard, for example connecting, disconnect, resuming, or when the connection is fully established.
This emits events like this:
```
Created shard
Event: ShardConnecting(Connecting { gateway: "wss://gateway.discord.gg?v=6&compress=zlib-stream", shard_id: 0 })
Event: GatewayHello(41250)
Event: ShardConnected(Connected { heartbeat_interval: 41250, shard_id: 0 })
Event: Ready(Ready { gui ......
```
Closes #210.

 gateway/shard/processor: emit shard events

---

model/src/channel/reaction.rs

Fix the deserialization of `twilight_model::channel::Reaction`s with members, by making use of the `MemberDeserializer`. This adds a custom deserializer to do this.
Additionally, tests for reactions with and without members have been added.
Closes #241.

model/channel: fix reaction member deserialization

---

model/src/gateway/payload/request_guild_members.rs

Add a `#[serde(untagged)]` to the `twilight_model::gateway::payload::RequestGuildMembersInfo` enum.

model/request_guild_members: add an untagged

---

model/src/channel/mod.rs

In the GuildChannel deserializer, handle unknown fields. The deserializer, on an unknown field, would simply short-circuit and return an error. This isn't good behaviour, and it should instead just ignore them and continue on.
A test has been included.
Bug introduced by #203.
Closes #245.

model/channel/guild_channel: handle unknown fields

---

model/src/channel/mod.rs
model/src/channel/reaction.rs
model/src/gateway/payload/typing_start.rs
model/src/guild/mod.rs

Delay the defaulting and processing of fields until all of the required fields have already been verified to be present.
This will increase the performance when deserialisation of a model fails.

model: delay visitor field defaulting

---

model/Cargo.toml
model/benches/member_chunk.rs
model/benches/test_benches.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/presence/mod.rs
model/src/guild/member.rs

Optimise the deserialisation of `twilight_model::gateway::payload::MemberChunk` by using seeded member and presence map deserialisers rather than `serde_value::Value` intermediary values.
This reduces the benchmark deserialising a 4 member chunk by 2.5x from:
```
test bench_member_chunk ... bench:      18,799 ns/iter (+/- 975)
```
to:
```
test bench_member_chunk ... bench:       7,644 ns/iter (+/- 383)
```
and a 1000 member chunk by 3.3x from:
```
test bench_member_chunk ... bench:   2,853,826 ns/iter (+/- 926,792)
```
to:
```
test bench_member_chunk ... bench:     873,607 ns/iter (+/- 317,657)
```

model/member_chunk: optimise deserialisation

---

model/Cargo.toml
model/benches/deserialization.rs
model/src/gateway/payload/typing_start.rs
model/src/guild/member.rs

Optimise the deserialisation of the `gateway::payload::TypingStart` model by avoiding deserialising the intermediary member into a `serde_value::Value` and instead deserializing via a custom `OptionalMemberDeserializer` instead.
This increases deserialization performance of typing start events by ~55.5%:
```
typing start            time:   [1.1537 us 1.1571 us 1.1613 us]
change: [-55.731% -55.318% -54.923%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
1 (1.00%) low mild
3 (3.00%) high mild
3 (3.00%) high severe
```

model/typing_start: optimise deserialization

---

model/src/channel/reaction.rs

Update the test suite for `channel::reaction` to use `serde_test` for checking equivalence of deserialisation and serialisation back and forth. It was using `serde_json` for only deserialisation before.
~~Blocks on #263.~~ Merged.

model/reaction: update tests to use serde_test

---

model/benches/deserialization.rs
model/src/channel/reaction.rs

Optimise the deserialisation of `channel::Reaction` by using an `OptionalMemberDeserializer` instead of an intermediary `serde_value::Value`.
This optimises the deserialisation of a reaction with a member by 47.2%:
```
reaction                time:   [1.8670 us 1.8758 us 1.8859 us]
change: [-48.078% -47.175% -46.456%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
5 (5.00%) high mild
```
Blocks on #264.

model/reaction: optimise deserialisation

---

model/src/gateway/payload/reaction_remove_emoji.rs

Make the fields of `gateway::payload::reaction_remove_emoji::PartialEmoji` public. These were all private.

model/partial_emoji: make fields public

---

gateway/src/queue.rs
gateway/src/queue/large_bot_queue.rs

`tokio::time::interval` allows the shard queue to sometimes send more identify requests before waiting for READY to be received from previous requests.
Closes #259

Fix shard queue sending identify requests too quickly

---

http/src/client/builder.rs
http/src/client/mod.rs

Possible bikesheds:
1. Define an enum `TokenType`
2. Define an enum `Token` like `enum Token {Bot(String), Bearer(String)}`
3. Split `ClientBuilder::token` into `bearer_token` and `bot_token`
4. Just do check the string for the prefix and default to "Bot " -- which is what this PR is
Possible issues I may encounter as I attempt to use this branch on a web server I'm writing:
1. Different rate limits?
2. Different error handling?
3. Limitations on what oauth2 bearer token clients can actually do?

allow bearer tokens in Client and ClientBuilder

---

model/src/gateway/payload/guild_delete.rs

For the `gateway::payload::GuildDelete` test suite, use `serde_test` for all of the tests instead of `serde_json` for one of them.

model/guild_delete: use serde_test for tests

---

gateway/src/queue.rs
gateway/src/queue/large_bot_queue.rs

Before this change, the shard queue would send the next request right away if a send fails.

Fix queue ignoring ratelimit when send fails

---

http/src/request/channel/message/update_message.rs

This also fixes an issue that would lead to message content getting
removed if there was no `.content` call on the edit message
structure.
Closes #260

Support for `SUPRESS_EMBEDS` and `allowed_mentions` in edit message.

---

http/src/client/builder.rs
http/src/client/mod.rs

Reqwest client does not needed to be wrapped in an arc as it is
internally handled in Reqwest. Furthermore this pr also removes a
implementation of From<Arc<ReqwestClient>> for HttpClient as it would
only be applicable if anyone else used the Reqwest unnecessarily
wrapped in an Arc.
Closes #275

Do not wrap Reqwest client in Arc.

---

model/src/channel/mod.rs
model/src/guild/emoji.rs
model/src/guild/mod.rs
model/src/guild/role.rs
model/src/voice/mod.rs
model/src/voice/voice_state.rs

Optimise the deserialisation of `twilight_model::guild::Guild` by
avoiding the use of `serde_value::Value` and instead using custom
deserialisers to directly deserialise into maps for guild channels,
emojis, roles, and voice states.
This reduces the time to deserialise a relatively large (1000 member)
guild create event by 33%:
```
guild                   time:   [5.5180 ms 5.5768 ms 5.6433 ms]
change: [-34.867% -33.259% -31.819%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) high mild
3 (3.00%) high severe
```

 model/guild: optimise deserialisation 

---

http/src/request/user/update_current_user.rs

Skip serialising fields in the `UpdateCurrentUser` request if they're empty.

http/request/update_current_user: skip if empty

---

model/src/gateway/payload/typing_start.rs

Use `serde_test` for the `twilight_model::gateway::payload::TypingStart` model to test (de)serialisation.

model/typing_start: use serde_test

---

standby/Cargo.toml
standby/README.md
standby/src/lib.rs

Add additional documentation to the crate docs which includes a full sample bot and slightly clearer small example.
Additionally, clarify in `Standby::process` that it must be called with events for returned futures to be fulfilled.

standby: add more documentation

---

model/src/gateway/event/shard.rs

Derive `Deserialize` and `Serialize` on all of the shard events, marking the `ShardEvent` enum as untagged.

model/gateway/event/shard: derive (de)serialize

---

gateway/Cargo.toml
gateway/src/listener.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/emit.rs
gateway/src/shard/processor/impl.rs

this makes sure they always get handled in the same order, doesn't require pinning them anymore and solves events sometimes getting out of order

make event listeners non async

---

cache/in-memory/src/lib.rs

With #292, the issue ended up being I made a wrong assumption about the way the cache was designed. This PR changes that to A. Fix the current issue, and B. Make a bit more sense. It doesn't make a whole lot of sense to "cache" anything until the maps and the like are in place to do so.
Closes #292

Reorder guild caching to uphold voice state invariant

---

gateway/Cargo.toml

Remove the `serde-value` dependency from the Gateway since it's not used.

gateway: remove serde-value dependency

---

lavalink/README.md
lavalink/src/client.rs
lavalink/src/lib.rs

Add a few notices in the crate-level docs, Lavalink client docs, and `Lavalink::process` method docs that the `Lavalink::process` method must be called with every Voice Server Update and Voice State Update event.

lavalink: add notices about lavalink::process

---

cache/in-memory/Cargo.toml
cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs

Use DashMap instead of mutexed hashmaps. This means that most operations will no longer be locking. The current user is still behind a mutex since it's a single object, but this isn't too bad since it's so infrequently accessed.

cache/in-memory: use dashmap where possible

---

standby/README.md
standby/src/futures.rs
standby/src/lib.rs

Add variants of each method that return a Stream instead of a Future. This is useful when you need to iterate over received events in a loop, and can help ensure that you won't miss any events during the processing of another.

standby: add streaming variants

---

model/src/channel/mod.rs
model/src/channel/reaction.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/payload/typing_start.rs
model/src/guild/mod.rs
model/src/voice/voice_state.rs

Properly handle unknown map keys by also deserializing the associated value via `serde::de::IgnoredAny`.

model: properly handle unknown map keys

---

Cargo.toml
README.md
twilight/src/lib.rs
utils/mention/Cargo.toml
utils/mention/README.md
utils/mention/src/lib.rs

Add a small utility crate named 'twilight-mention'. twilight-mention is a crate for creating display formatters that mention various `twilight-model` types.
It includes two types: a `Mention` trait and a `MentionFormat` struct. The Mention trait includes a `mention` method that will create a `MentionFormat` struct. The `MentionFormat` struct implements `std::fmt::Display` and will format a mention for the given resource.
Supported resources include things like channel IDs, guild channels, the current user, emojis and emoji IDs, roles, users.
Here's an example:
```rust
use twilight_mention::Mention;
use twilight_model::id::UserId;
let user_id = UserId(123);
let message = format!("Hey there, {}!", user_id.mention());
```
This crate isn't included as part of the main `twilight` crate and is …

project: add 'twilight-mention' utility crate

---

gateway/src/shard/processor/socket_forwarder.rs

These logs don't belong at the `warn` level since they are encountered during normal operation.
I changed the two inside the match to `info`, maybe they should also be `debug`? :thinking:

Decrease some log levels in `socket_forwarder`

---

gateway/src/cluster/config.rs
gateway/src/shard/config.rs
gateway/src/shard/processor/impl.rs
model/src/gateway/payload/identify.rs

Remove guild subscriptions from the gateway since it has been soft-deprecated-but-not-really in the API and in general superseded by intents:
<https://discord.com/developers/docs/topics/gateway#guild-subscriptions>
Closes #302.

gateway: remove guild subscriptions

---

cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs
model/README.md
model/src/channel/mod.rs
model/src/lib.rs
standby/src/lib.rs

Add a few convenience methods to `twilight_model::channel::{Channel, GuildChannel}`:
- `Channel::id`
- `Channel::name`
- `GuildChannel::guild_id`
- `GuildChannel::id`
- `GuildChannel::name`
These are a few operations that are done a lot, probably by most users. All channels and guild channels have an ID and can have a name, so both have matching methods for retrieving both from the inner variants. `GuildChannel` is the only one with a `guild_id` method since it only applies to guild channels, and not other types of channels.
Since this is a first for the model crate, we should probably all approve it before merging. If anyone has any concerns about doing this (see #217 for my opinion) please comment them.
Closes #217.

model/channel: add a few convenience methods

---

gateway/Cargo.toml
gateway/src/lib.rs
gateway/src/shard/error.rs
gateway/src/shard/processor/impl.rs
model/benches/deserialization.rs
model/src/gateway/event/gateway.rs
model/src/gateway/event/mod.rs
model/src/guild/mod.rs

Optimise the deserialisation of
`twilight_model::gateway::event::GatewayEvent` by scanning the input JSON payload to deserialise prior to actually deserialising it.
Instead of implementing `serde::Deserialize` directly on `GatewayEvent`, make a `GatewayEventDeserializer` that implements `serde::de::DeserializeSeed` and outputs a `GatewayEvent` on success.
When making a `GatewayEventDeserializer`, it will scan the payload for an "op" and parse out the opcode value, and optionally a "t", which denotes the event type in the case that the gateway event is a Dispatch event (op 0).
When deserialising the gateway event itself, the op can be matched on and logic can be applied based on the opcode. For example, for the event op the sequence will be parsed and the dispatch payload will be parsed …

model/event/gateway: optimise deserialiser

---

gateway/Cargo.toml

The futures-channel dependency is missing the `sink` feature.
It is currently activated by tokio-tungistenite `v0.10.1` -> futures `v0.3.5` but tokio-tungistenite `master` depends now on `futures-util`.

gateway: Add missing `sink` feature for futures-channel

---

gateway/Cargo.toml
gateway/src/lib.rs
gateway/src/shard/error.rs
gateway/src/shard/impl.rs
gateway/src/shard/mod.rs
gateway/src/shard/processor/connect.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/session.rs
gateway/src/shard/processor/socket_forwarder.rs
gateway/src/shard/sink.rs
http/src/lib.rs
lavalink/Cargo.toml
lavalink/src/node.rs
twilight/Cargo.toml

This PR adds new features for `twilight` & `twilight-gateway` to switch between `rustls` and `native-tls`.
It also switches to `async-tungstenite`.
Closes: #309 
Closes: #124

twilight/gateway: add features for rustls & native-tls

---

.github/workflows/doc.yml
gateway/README.md
gateway/src/lib.rs
gateway/src/shard/event.rs
lavalink/src/player.rs

The PR fixes unresolved doc links and adds a build job to check the documentation on rust nightly with denied
`intra_doc_link_resolution_failure` warnings.
Related: #202 
What about the use of [intra-doc links][intra-rustdoc-links] instead of urls to the rendered files?
[intra-rustdoc-links]: https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md

Fix doc links and add build job to check the documentation

---

gateway/src/shard/error.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/connect.rs
gateway/src/shard/processor/error.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/mod.rs
gateway/src/shard/processor/session.rs

I moved/copied the error variants used by the `processor` module to its own error type and created a `Error::Processor` variant in the shard error.

gateway: separate shard processor errors

---

.github/workflows/publish.yml

Adds a new workflow to publish the `trunk` docs to the `gh-pages` branch.
See the [build job] and the [deployed docs].
But it needs some additional work for the first deployment when using `GITHUB_TOKEN`.
There two ways to go:
1. Merge PR and the workflow creates the `gh-pages` branch with the docs.
2. Go to Settings and select the `gh-pages` branch again to enable the GitHub Pages.
3. Re-run the workflow build job / Wait for the next commit
Or
1. Create the `gh-pages` branch with a `.nojekyll` file.
2. Go to Settings and select the `gh-pages` branch to enable the GitHub Pages.
3. Merge PR and the workflow creates the docs.
[build job]: https://github.com/nickelc/twilight/runs/883542757?check_suite_focus=true
[deployed docs]: https://nickelc.github.io/twilight/

actions: publish docs to gh-pages branch

---

lavalink/src/model.rs

Fix some documentation for the `twilight_lavalink::model::Play` model due to me getting it mixed up with something else.

lavalink/model/play: fix docs

---

model/src/gateway/event/dispatch.rs
model/src/gateway/event/gateway.rs
model/src/gateway/event/kind.rs

Implement `serde::Serialize` for the `DispatchEvent` and `GatewayEvent` models. The `DispatchEvent` enum is just a simple derive, but `GatewayEvent` is a custom serializer. For Dispatch variants it will serialize the T, S, Op, and D keys. For other variants, it will serialize T and S as null and then serialize the Op and, possibly nullably, serialize the D key.
Tests for all GatewayEvent variants (dispatch, heartbeat, heartbeat ack, hello, invalidate session, reconnect) have been added.
Additionally, this makes the `EventType` enum derive `Deserialize` and `Serialize`.
Closes #102.

model: impl serialize for dispatch, gateway models

---

gateway/src/lib.rs
http/src/lib.rs

In the gateway and http crates, remove the lint allows for the `clippy::used_underscore_binding` lint.
See #189 for why this was originally added, but basically it was because Clippy would error on code generated from awaits.

gateway,http: remove allow used_underscore_binding

---

model/src/voice/voice_region.rs

Fix the field name of the `twilight_model::voice::VoiceRegion` model's incorrect `optional` field to `optimal`.
Additionally, add a (de)serialization test using a payload from the HTTP API.

model/voice/region: fix 'optimal' field name

---

http/src/request/guild/update_guild.rs

Don't send `name` or `owner_id` if they aren't set. Related issue: #281

http: skip serializing name/owner in request/guild/update_guild

---

gateway/Cargo.toml
gateway/README.md
gateway/src/lib.rs
gateway/src/shard/error.rs
gateway/src/shard/processor/error.rs
gateway/src/shard/processor/impl.rs
http/Cargo.toml
http/README.md
http/src/error.rs
http/src/lib.rs
http/src/request/guild/get_guild_vanity_url.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/get_member.rs
http/src/request/mod.rs
twilight/Cargo.toml

`serde_json` is no longer optional
http:
- enable `serde-impl` & `sway-number-parsing` features for `simd-json`
- use `crate::json_from_slice`
- use of `simd_json::value::OwnedValue`
gateway:
- fix the error mapping of `GatewayEventDeserializerOwned::from_json(json)`
Fixes the simd-json builds for #332

gateway, http, twilight: fix the `simd-json` feature / serde_json is no longer optional

---

model/src/gateway/event/gateway.rs

Fix the deserialization of the Reconnect variant by deserializing and ignoring the rest of the fields.
Tests for all variants have been added.

 model/gateway/event: fix reconnect deserialization 

---

gateway/Cargo.toml
gateway/README.md
gateway/src/lib.rs
http/Cargo.toml
http/README.md
http/src/lib.rs
lavalink/Cargo.toml
lavalink/README.md
lavalink/src/lib.rs

Switch out the `gateway`, `http`, and `lavalink` crates' default TLS feature from being `native` to `rustls`.
See #124 for justification.
Closes #313.

gateway,http,lavalink: use rustls for default

---

model/src/channel/reaction_type.rs

Add a test for the `ReactionType::Custom` variant's `animated` field when it's missing. The field may not be included by Discord when it's `false`, so the test reflects that scenario. Additionally, make other tests test for serialization in addition to the existing deserialization tests.

model/reaction_type: add test for animated field

---

utils/mention/README.md
utils/mention/src/lib.rs

Fix a grammatical typo in the `twilight-mention` README that left out a word.

utils/mention: fix grammatical typo in readme

---

utils/mention/src/lib.rs

Refactor `twilight-mention`'s channel ID code by using `Channel::id` and `GuildChannel::id` to get the ID of a channel.

utils/mention: remove guild channel id function

---

model/src/channel/reaction_type.rs

In the `twilight_model::channel::ReactionType` model, remove a "hack" to create a default boolean value of false for a field. The "hack" was to use a function to do this paired with `#[serde(default = "false_default")], but `#[serde(default)]` on a boolean yields the same result.

model/reaction_type: remove a "hack"

---

lavalink/examples/basic-lavalink-bot/src/main.rs
lavalink/src/node.rs

On every iteration of the node connection loop a branch would run to check if the user hadn't dropped the rx of events received from lavalink, and in the case that they did, break the loop. Not all users want to handle these, so just ignoring if the user closed the channel is fine.
Closes #296.

lavalink/node: ignore when user drops rx

---

gateway/src/shard/impl.rs

When `Shard::shutdown` is called, send a close message with a frame with a normal close code. This will make the bot immediately appear offline.
I have tested this a few times and it worked each time.

gateway/shard: send normal close on shutdown

---

lavalink/src/model.rs

In the `twilight-lavalink` crate's `model` module, expose the `incoming` and `outgoing` modules while re-exporting their contents. This can make code and documentation navigation easier for people to find things relevant to a use case more easily.

lavalink/model: expose incoming, outgoing modules

---

gateway/src/shard/event.rs
gateway/src/shard/impl.rs
gateway/src/shard/mod.rs

Instead of returning a `impl Stream` from `Shard::events` and `Shard::some_events`, return the named `Events` type that implements `Stream`.

gateway/shard: return named event stream type

---

http/src/lib.rs
http/src/request/guild/update_guild.rs

Add the `banner` field to the JSON body. This field is nullable, and is a 16:9 PNG or JPEG base64 encoded image.
Discord docs: <https://discord.com/developers/docs/resources/guild#modify-guild-json-params>

http/update_guild: add 'banner' field

---

gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/inflater.rs

Remove the imports for `metrics` crate macros. It's just simpler to reference the crate instead of conditionally importing the macros at the top, since in their usage they are already bounded by the conditional feature.

gateway: remove metrics imports

---

http/src/client/mod.rs
http/src/ratelimiting/bucket.rs
http/src/ratelimiting/mod.rs
http/src/request/channel/message/get_channel_messages_configured.rs

In the `http` crate, remove comments by either removing them completely (in one case, removing a commented out import), re-ordering their position, or upgrading them to documentation comments.

http: remove comments

---

http/src/request/channel/invite/create_invite.rs
http/src/request/channel/message/create_message.rs
http/src/request/channel/update_channel.rs
http/src/request/channel/webhook/create_webhook.rs
http/src/request/channel/webhook/execute_webhook.rs
http/src/request/channel/webhook/update_webhook.rs
http/src/request/channel/webhook/update_webhook_with_token.rs
http/src/request/guild/create_guild.rs
http/src/request/guild/create_guild_channel.rs
http/src/request/guild/emoji/create_emoji.rs
http/src/request/guild/emoji/update_emoji.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/guild/role/create_role.rs
http/src/request/guild/role/update_role.rs
http/src/request/guild/update_guild.rs
http/src/request/guild/update_guild_widget.rs
http/src/request/user/update_current_user.rs

Update requests to allow for nullable fields, that is fields that are `Option<Option<T>>`. When `None`, the field is not included in the JSON payload, when `Some(None)` the field is included with a null value, and when `Some(Some(T))` the field is included with T value.
Closes #281.

http/request: nullable fields

---

gateway/src/queue/large_bot_queue.rs
gateway/src/queue/mod.rs
gateway/src/shard/processor/session.rs

Simplify some runtime spawns by ignoring the return value of a spawn since they don't need to be used and simply moving futures into `tokio::spawn` rather than wrapping futures in an `async {}` block.

gateway: simplify runtime spawns

---

http/src/request/channel/message/create_message.rs
http/src/request/mod.rs

When sending a multipart request, use `payload_json` to pass parameters such as embeds and content.
Closes #358.

http/create_message: use payload_json form field

---

gateway/src/queue/day_limiter.rs
gateway/src/queue/large_bot_queue.rs
gateway/src/queue/mod.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/emit.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/inflater.rs
gateway/src/shard/processor/socket_forwarder.rs
http/src/client/mod.rs
http/src/ratelimiting/bucket.rs
http/src/ratelimiting/mod.rs
lavalink/examples/basic-lavalink-bot/src/main.rs
lavalink/src/client.rs
lavalink/src/node.rs
lavalink/src/player.rs
standby/src/lib.rs

Make the logging messages included in traces consistent. This focuses
more on the grammar than the wording: lowercase messages, no periods at
the end, removing unnecessary words, and keeping errors at the end of
the message.
Closes #37.

project: make log messages consistent

---

builders/src/embed.rs
cache/in-memory/src/lib.rs
command-parser/README.md
command-parser/src/config.rs
command-parser/src/lib.rs
gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/lib.rs
gateway/src/queue/mod.rs
gateway/src/shard/event.rs
gateway/src/shard/impl.rs
gateway/src/shard/mod.rs
gateway/src/shard/stage.rs
http/src/client/builder.rs
http/src/client/mod.rs
http/src/request/channel/message/get_channel_messages.rs
http/src/request/channel/update_channel.rs
http/src/request/guild/create_guild.rs
http/src/request/guild/create_guild_channel.rs
http/src/request/guild/mod.rs
http/src/request/validate.rs
lavalink/src/client.rs
model/src/gateway/event/mod.rs

Fix all of the dead links using the `cargo-deadlinks` crate, and fix the broken links that had a name but didn't have an anchor URL.
Closes #202.

project: fix dead links

---

model/src/channel/message/kind.rs
model/src/channel/mod.rs

This PR just adds two things: 
- A simple copy derive to `MessageType` to give it a cheaper duplication path and to avoid needing to call `.clone()` on it. 
- A `TryFrom<u8> for MessageType` implementation
Side note : Wow, that derive is ugly when formatted.

Add Copy derive and conversion helper to MessageType

---

model/src/gateway/event/dispatch.rs
model/src/gateway/event/gateway.rs

Add a `#[serde(untagged)]` attribute to `twilight_model::gateway::event::DispatchEvent` to make it serialize into untagged enums instead of externally tagged enums.

model/event: make dispatch event an untagged enum

---

http/src/request/channel/message/create_message.rs
http/src/request/channel/message/get_channel_messages.rs
http/src/request/channel/message/get_channel_messages_configured.rs
http/src/request/channel/message/update_message.rs
http/src/request/channel/reaction/get_reactions.rs
http/src/request/channel/update_channel.rs
http/src/request/guild/ban/create_ban.rs
http/src/request/guild/create_guild.rs
http/src/request/guild/create_guild_channel.rs
http/src/request/guild/create_guild_prune.rs
http/src/request/guild/get_audit_log.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/guild/update_guild.rs
http/src/request/user/get_current_user_guilds.rs
http/src/request/user/update_current_user.rs

In HTTP requests, provide the input in error variants, such as providing the content the user gave when creating a message.
Closes #216.

http/request: provide input in error variants

---

cache/trait/Cargo.toml
lavalink/examples/basic-lavalink-bot/Cargo.toml
model/Cargo.toml

Remove unused dependencies from crates.
cache/trait:
- twilight-model
lavalink:
- twilight-command-parser
model:
- tracing

cache, lavalink, model: remove unused dependencies

---

cache/in-memory/src/updates.rs
gateway/src/queue/day_limiter.rs
gateway/src/queue/large_bot_queue.rs
gateway/src/queue/mod.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/connect.rs
gateway/src/shard/processor/emit.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/inflater.rs
gateway/src/shard/processor/socket_forwarder.rs
http/src/client/mod.rs
http/src/ratelimiting/bucket.rs
http/src/ratelimiting/mod.rs

Remove the imports for `tracing` crate macros. In some cases, these are only needed when a feature is enabled, so we need to put `#[allow(unused)]` on them, but in a couple of cases these imports existed despite no longer being ever used. For consistency with the rest of the libraries and in general, don't import them and just call them via FQN.

cache,gateway,http: remove tracing imports

---

gateway/src/listener.rs
gateway/src/shard/processor/emit.rs
gateway/src/shard/processor/impl.rs

Refactor event emissions to be simpler, faster, reduce allocations, and remove duplicate code.
Instead of creating a `Vec` to store listener IDs to remove, iterating over listeners and determining what to remove, and then iterating over the vec to remove them, use `DashMap::retain` to directly remove listeners that have had their channels closed.
Additionally, simplify and remove code by abstracting the iteration and checks over the listeners map for the `bytes` and `event` emission functions to another function that both call. `bytes` and `event` provide a function to create events, and this function is called when sending an event to a listener channel.
`bytes` now takes a reference to the listeners map and is no longer an async fn.
Additionally, add documentation and tests.

gateway: refactor event emissions

---

model/src/gateway/connection_info/bot_connection_info.rs
model/src/gateway/connection_info/mod.rs
model/src/gateway/session_start_limit.rs

Add `max_concurrency` to the session start limit struct, which indicates how many shard sessions may concurrently be started.
Documentation and tests have been added to go with it.

model/gateway: add 'max_concurrency' field

---

model/src/guild/ban.rs
model/src/guild/emoji.rs
model/src/guild/prune.rs
model/src/guild/widget.rs

Add `serde_test` unit tests for the following `guild` module types:
- Ban
- Emoji
- GuildPrune
- GuildWidget
This is a part of #31.

model/guild: add tests for a few types

---

model/Cargo.toml
model/src/channel/mod.rs
model/src/channel/permission_overwrite.rs
model/src/channel/reaction.rs
model/src/gateway/event/gateway.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/payload/typing_start.rs
model/src/guild/emoji.rs
model/src/guild/mod.rs
model/src/guild/role.rs
model/src/voice/voice_state.rs

Add tracing to the custom deserialization impls of models. This will step through the deserializer and won't repeat information that would be given from error returns.
Closes #251.

model: add deserialization tracing

---

http/src/request/guild/role/create_role.rs
http/src/request/guild/role/update_role.rs

Updates `twilight-http` to use a `u32` instead of the `u64` for representing colors, as to stay consistent with the model.
Fixes #381

http: Change color field to use a u32

---

README.md
gateway/examples/cluster/src/main.rs
gateway/examples/intents/src/main.rs
gateway/examples/metrics/src/main.rs
gateway/examples/queue/src/main.rs
gateway/examples/request-members/src/main.rs
gateway/examples/shard/src/main.rs
gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/session.rs
gateway/tests/test_shard_state_events.rs
lavalink/README.md
lavalink/examples/basic-lavalink-bot/src/main.rs
lavalink/src/lib.rs
standby/README.md
standby/src/lib.rs
twilight/src/lib.rs

Make much of the Cluster and Shard API synchronous. A lot of the functionality, mainly surrounding the usage of asynchronous Mutex locks, doesn't actually need to be asynchronous. The main benefit of async locks is when they're going to be held across context points, i.e. when an `await` is encountered. The running task may be switched to another on the same thread and, if acquiring the same lock, will deadlock. Since this can't happen due to the locks not being used in asynchronous contexts, there's no need for them, thus removing the need for their caller functions to be async.
This makes the following API surface sync:
- `Cluster::down`
- `Cluster::down_resumable`
- `Cluster::events`
- `Cluster::info`
- `Cluster::shard`
- `Cluster::some_events`
- `Shard::events`
- `Shard::info`
- …

gateway: make much of the public api sync

---

.github/workflows/publish.yml

Setup an SSH deploy key for doc deployment to gh-pages.
Closes #343.

workflow/publish: setup ssh deploy key

---

model/src/channel/permission_overwrite.rs
model/src/gateway/event/gateway.rs
model/src/guild/mod.rs
model/src/guild/permissions.rs
model/src/guild/role.rs

Permissions in Permission Overwrites and Roles now have two fields in the API: bitflags stored as an integer and another as a string.
Permission Overwrites now have the following fields:
- allow_new
- deny_new
Roles now have:
- permissions_new
For the motivations behind this change read the link in #365. This patch introduces support for these fields. To make a migration easier (or, requiring no effort), rename the Permission Overwrites' `allow` and `deny` fields to `allow_old` and `deny_old`, adding `allow_new` and `deny_new` as `allow` and `deny`. Additionally, do the same for Role's `permissions`: rename it to `permissions_old` and make the new one `permissions`. This can be done simply via `#[serde(rename)]`.
Tests for permissions, permission overwrites, and roles have been added. …

model: handle new permissions scheme

---

standby/src/lib.rs

Rework `Standby::wait_for_event` and `Standby::wait_for_event_stream` to match any event that's processed by Standby, including from any guild or other source. This allows you to, for example, match for reaction adds and reaction removes from a user, instead of having two separate Standby calls for both events and merging them.
Closes #367.

standby: allow matching over any event processed

---

gateway/src/lib.rs

When re-exporting `event::EventTypeFlags`, inline the documentation. The `event` module is private, so re-exporting the `EventTypeFlags` without inlining the documentation causes it to have no documentation.
See the current <https://twilight-rs.github.io/twilight/twilight_gateway/index.html> for what this looks like before this patch.

gateway: inline eventtypeflags re-export docs

---

gateway/examples/shard/src/main.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/session.rs
gateway/tests/test_shard_command_ratelimit.rs

Fix the ratelimiter for sending events over the shard. The ratelimiter uses tokio's interval, which like documented in #268 and the comments of issue #193, isn't what you'd think it is at first glance.
Tokio's Interval will create an unbounded number of "tickets" available every specified duration, adding a new one each time that the duration has passed. This means that if you have an interval that refreshes every 5 seconds and take from it twice, it'll take 5 seconds to do in total. If you wait a few minutes and then take from it 10 times, all of those tickets will be immediately retrieved. This isn't what you want with a ratelimit.
Instead, use Tokio's Throttle. It's similar but has a differing detail: it will only keep 1 ticket available at a time. This means that if you wait a few …

gateway/shard: fix command send ratelimiter

---

README.md
command-parser/README.md
command-parser/src/lib.rs
gateway/README.md
gateway/src/lib.rs
http/README.md
http/src/lib.rs
lavalink/README.md
lavalink/src/lib.rs
model/README.md
model/src/lib.rs
standby/README.md
standby/src/lib.rs
twilight/src/lib.rs
utils/embed-builder/README.md
utils/embed-builder/src/lib.rs
utils/mention/README.md
utils/mention/src/lib.rs

Make the badges consistent across all of the crate READMEs (and slightly prettier). Some of them have different versions, and most out of them are no longer true. For example, the model crate requires 1.31+ (which is probably not be true), the command parser requires 1.36+, and the main crate requires 1.40+.
Our policy for now is to support latest stable, so instead all of these have been updated to mention "stable". Some of the READMEs don't have badges, to add them to those READMEs.

project: make readme badges consistent

---

model/src/channel/message/mod.rs
model/src/guild/partial_member.rs

Add the missing `nick` field to the `twilight_model::guild::PartialMember` type.
Member documentation can be found here:
<https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-structure>

model/partial_member: add missing 'nick' field

---

model/src/guild/integration.rs
model/src/guild/integration_expire_behavior.rs
model/src/guild/mod.rs

Update the fields of the `guild::GuildIntegration` struct to match the latest documentation.
The following changes are included:
- a `enable_emoticons` optional boolean has been added
- the `role_id` type has been changed from an `IntegrationId` to a
`RoleId`
- the `expire_behavior` field has been changed from an integer to a
typed repr enum
Documentation can be found at: <https://discord.com/developers/docs/resources/guild#integration-object>
Tests have been added.

model/guild/integration: update fields

---

model/src/channel/category_channel.rs
model/src/channel/mod.rs

Remove the `nsfw` and `parent_id` fields of `model::CategoryChannel`. Category channels don't have an NSFW configuration and can't have a parent category channel.
A test has been included.

model/category_channel: remove 'nsfw', 'parent_id'

---

model/src/gateway/presence/activity_flags.rs

Use shifts to declare the values of constants to be consistent with other bitflags. Add tests for all variants.

model/activity_flags: use consistent values

---

model/src/gateway/event/kind.rs

Fix the names of the `ReactionRemove`, `ReactionRemoveAll`, and `ReactionRemoveEmoji` variants of the `gateway::event::EventType` enum. These were missing the `MESSAGE_` prefixes in their serde renames.
This wasn't causing an issue with payload deserialization because the event type isn't used in it.

model/event_type: fix names of variants

---

command-parser/src/parser.rs
http/src/request/validate.rs
model/benches/deserialization.rs
model/src/channel/reaction.rs
model/src/gateway/connection_info/bot_connection_info.rs
model/src/gateway/event/gateway.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/payload/member_update.rs
model/src/gateway/payload/typing_start.rs
model/src/gateway/payload/voice_state_update.rs
model/src/gateway/session_start_limit.rs
model/src/guild/integration.rs
model/src/guild/permissions.rs

Fix all crates' clippy lints via `cargo clippy --tests`. The CI currently does not catch lints in tests.

project: fix all clippy lints

---

gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/socket_forwarder.rs

I some cases the gateway would panic because it would attempt 
to get a event twice after there no longer was any sender. 
This causes a panic in `futures_channel`.

Resume connection when SocketForwarder ends event stream

---

.github/workflows/lint.yml

Run clippy on tests in crates by using Clippy's `--tests` flag.
Closes #410.

workflow/lint: run clippy on tests

---

cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs

Fixes a report from the Twilight Discord. If a user doesn't enable caching guilds then its not possible to always have a place to put the voice states. In these cases, just ignore them and return `None`.
Fixes #411
A relevant test has been added as well.

Dont panic when recieving a voice state when guild caching isn't enabled

---

README.md
command-parser/README.md
command-parser/src/lib.rs
model/README.md
model/src/lib.rs
twilight/src/lib.rs

Correct the readmes in the command-parser, model, and twilight crates by specifying that the latest Rust version is required.

command-parser,model,twilight: correct readmes

---

cache/in-memory/src/lib.rs
cache/in-memory/src/model/presence.rs
cache/in-memory/src/updates.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/presence/mod.rs
model/src/guild/mod.rs

Make `twilight_model::gateway::Presence::guild_id` a non-Optional field. Also make `twilight_model::gateway::payload::PresenceUpdate::guild_id` non-Optional to match it. Since bots can only receive presences from guilds the guild ID will always be present.
To go along with this, update the cache to no longer handle optional guild IDs. The `twilight_cache_inmemory::models::CachedPresence::guild_id` field is now non-Optional, and methods that work with presences now require a `GuildId` parameter.

cache,model: make presence guild id required

---

cache/in-memory/src/lib.rs

Hide unnecessarily public methods in the `InMemoryCache` that should only be used internally. These were made public in #141 on the premise of users using the cache to cache objects over HTTP, but this introduces race conditions and isn't the intent of the cache, which is meant to be used for sequential gateway events.

cache/in-memory: make unnecessary methods private

---

gateway/src/shard/impl.rs

Make the `Shard::session` method private. The Session itself that's returned is private and unavailable to the user and contains internal data, so this shouldn't be public.
This was originally useful to users when the gateway crate was added but isn't anymore.

gateway/shard: make 'session' private

---

gateway/src/shard/impl.rs

Simplify sending close codes on shard shutdown by using `Session::close` instead of sending over a session's tx channel.

gateway/shard: simplify closes on shutdown

---

gateway/src/shard/processor/impl.rs

In the gateway's `ShardProcessor`, actually use the configured `large_threshold` value. It wasn't being used and forced a value of 250.

gateway/shard: use configured large threshold

---

model/src/guild/permissions.rs

It has been confirmed that the permissions bitflags won't go above 64 bits, so this reduces the size from u128 to u64.

model/permissions: make bitflags u64

---

model/src/guild/mod.rs
model/src/guild/partial_guild.rs

After the initial commit (<https://github.com/discord/discord-api-docs/commit/29ec3458f5c561172fb952d1ebcde83c8e6173dd>) to the Discord API docs describing the `permissions_new` fields, another commit has been added for a missing field (<https://github.com/discord/discord-api-docs/commit/15bb9952efdc1688c6717d677f5b595ca098ee67>). This renames the `Guild::permissions` and `PartialGuild::permissions` fields in serde to `permissions_new`, adding on to #385.

model/guild: add missing permissions_new

---

gateway/examples/request-members/src/main.rs
gateway/tests/test_shard_command_ratelimit.rs
model/src/gateway/payload/mod.rs
model/src/gateway/payload/request_guild_members.rs

Rework the `twilight_model::gateway::payload::RequestGuildMembers` type by no longer using a variety of methods to construct an instance of it, and instead using a consuming builder pattern.
Previously, creating a `RequestGuildMembers` that retrieved a single user's member information and presence with a nonce looked something like:
```rust
let request = RequestGuildMembers::new_single_user_with_nonce(
guild_id,
user_id,
Some(true),
Some("nonce".to_owned()),
);
```
It's not clear what the parameters are, and booleans in long parameter lists are notoriously confusing. There were many methods like this for each possible combination: `new_with_nonce`, `new_single_user`, `new_multi_user`, and `new_multi_user_with_nonce`. These were also copied into the child payload struct of …

model: rework request guild members

---

command-parser/src/config.rs
command-parser/src/parser.rs

Instead of using the list of set prefixes can you here define a
function that returns the index at which the prefix ends if it
matches, or return none if there is no prefix that matches.
```rust
use twilight_command_parser::{Command, CommandParserConfig, Parser};
let mut config = CommandParserConfig::new();
config.add_prefix("!");
config.add_command("echo", false);
let parser = Parser::new(config);
let prefix_fn = |buf: &str| if buf.starts_with("=") { Some(1) } else { None };
let command = parser.parse_dynamic_prefix("=echo foo", prefix_fn);
assert!(command.is_some());
let command = command.unwrap();
assert_eq!("=", command.prefix);
assert_eq!("echo", command.name);
```
Related to #389

Add dynamic prefixes to the command parser

---

http/src/request/channel/reaction/delete_all_reactions.rs
http/src/request/guild/delete_guild.rs
http/src/request/guild/emoji/delete_emoji.rs
http/src/request/guild/integration/create_guild_integration.rs
http/src/request/guild/integration/delete_guild_integration.rs
http/src/request/guild/integration/sync_guild_integration.rs
http/src/request/guild/integration/update_guild_integration.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/guild/update_current_user_nick.rs
http/src/request/guild/update_guild_channel_positions.rs

Some future implementations called `Client::request` when `start`ing, while their associated responses returned a `204 No Content` to indicate success. This PR changes those method calls to `Client::verify`.
Fixes #443.

http: replace calls to request with verify

---

utils/mention/Cargo.toml
utils/mention/src/lib.rs

In the `twilight-mention` crate, test implementations with `static_assertions`.

utils/mention: test with static_assertions

---

utils/embed-builder/Cargo.toml
utils/embed-builder/src/author.rs
utils/embed-builder/src/builder.rs
utils/embed-builder/src/field.rs
utils/embed-builder/src/footer.rs
utils/embed-builder/src/image_source.rs

In the `twilight-embed-builder` crate, test implementations with `static_assertions`.

utils/embed-builder: test with static_assertions

---

.github/workflows/publish.yml
CNAME

Make it so the CNAME file gets created on the gh-pages branch.

Fix CNAME in workflow

---

.github/workflows/publish.yml

Point the cname at api.twilight.rs so it does take over the book.

CNAME fix 2

---

README.md
twilight/src/lib.rs

Update the primary example to use individual crates rather than the deprecated main one.

project: update example to use individual crates

---

gateway/src/cluster/impl.rs
gateway/src/event.rs
gateway/src/lib.rs
gateway/src/listener.rs
gateway/src/shard/impl.rs
gateway/src/shard/json.rs
gateway/src/shard/mod.rs
gateway/src/shard/processor/emitter.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/inflater.rs
gateway/src/shard/processor/session.rs
model/src/gateway/event/gateway.rs
model/src/gateway/event/kind.rs
model/src/gateway/event/mod.rs

In the gateway's shard processor, conditionally deserialize received events if the user has specified that they want them.
Intents are a good way of filtering events that a user wants, but it only filters by category. If a user selects the `GUILD_MESSAGES` event then they will receive `MESSAGE_CREATE`s, `MESSAGE_DELETE`s, `MESSAGE_UPDATE`s, and so on. Intents are especially good at reducing network usage, but can cause users to still receive and deserialize more events than they actually use.
Say that a user wants to handle `MESSAGE_CREATE`s but not `MESSAGE_DELETE`s. They don't care if message deletes are deserialized or not since they don't use them. Coincidentally, shards don't use most dispatch events either, such as message deletes. We can utilize event filtering through the …

gateway: conditionally deserialize received events

---

gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs
gateway/src/queue/mod.rs
gateway/src/shard/builder.rs
gateway/src/shard/event.rs
http/src/api_error.rs
http/src/request/channel/message/create_message.rs
lavalink/src/client.rs
lavalink/src/http.rs
lavalink/src/node.rs
lavalink/src/player.rs
utils/embed-builder/src/author.rs
utils/embed-builder/src/builder.rs
utils/embed-builder/src/field.rs
utils/embed-builder/src/footer.rs

Fix all broken links via `cargo deadlinks`. This fixes links in the following crates:
- embed-builder
- gateway
- http
- lavalink
Part of #459.

project: fix all broken links

---

model/src/gateway/presence/mod.rs

When deserializing a map of presences from a sequence of presences, default the guild ID of the presence with the map deserializer's pre-configured default ID if one doesn't exist in the payload.
This fixes the deserialization of a guild creates' list of presences, since the presences in this payload don't contain a guild ID.

model/presence: use deserializer for map deser

---

gateway/examples/metrics/Cargo.toml

In the gateway's "metrics" example, reduce the features of dependencies, mainly `tracing-log` and `metrics-runtime`. `metrics-runtime` in particular by default brings in all observers and exporters, such as HTTP exporters and prometheus observers.
This reduces the example's dependency count from 232 to 216 and the workspace's total dependency count in a build from 262 to 256.

gateway/examples/metrics: reduce features

---

README.md
gateway/examples/intents/src/main.rs
gateway/src/cluster/builder.rs
gateway/src/shard/builder.rs
gateway/src/shard/config.rs
gateway/src/shard/processor/impl.rs
model/src/gateway/intents.rs
model/src/gateway/mod.rs
model/src/gateway/payload/identify.rs
twilight/src/lib.rs

Rename `twilight_model::gateway::GatewayIntents` to just `Intents`. It's not necessary to repeat `Gateway` in the name and `Intents` is more concise.

model/gateway: rename 'gatewayintents'

---

gateway/src/cluster/builder.rs

This change is so we can add more shard schemes without a major
version bump.

Mark ShardScheme as non exhaustive

---

cache/in-memory/Cargo.toml
cache/in-memory/src/model/emoji.rs
cache/in-memory/src/model/guild.rs
cache/in-memory/src/model/member.rs
cache/in-memory/src/model/message.rs
cache/in-memory/src/model/presence.rs
cache/in-memory/src/model/voice_state.rs

This makes the cache struct derive Serialize, allowing for them to be serialized as JSON to e.g. expose the cache to the outside world in any way.
All tests pass, I hope I did not miss out any struct.

Derive from Serialize for cache structs

---

gateway/src/cluster/impl.rs
gateway/src/shard/impl.rs

This adds a method `raw_command` to Shard and Cluster.
I have a usecase for this as I receive bytes from a different source that I need to relay over the gateway, and deserializing just for twilight to serialize it again is unnecessary overhead. This allows for sending the raw JSON as a string (and therefore bytes with `String::from_utf8`).

gateway: add {cluster,shard}::command_raw

---

gateway/src/shard/processor/impl.rs

This downgrades the warnings for gateway events to debug for resumes and info for reconnects as discussed.

Downgrade gateway warnings

---

gateway/Cargo.toml
gateway/README.md
gateway/src/lib.rs

This changeset may look a bit strange in that the zlib-ng-compat
feature is not disabled when setting it to use stock-zlib. This is
because flate2 (through libz) will use stock zlib if it is asked for
anywhere even if zlib-ng-compat is also asked for.

use zlib-ng as default

---

gateway/src/cluster/builder.rs
gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs

Copy: We want to be able to add non-copy variants in the future.
Ordering: It does not make much sense to have a order for
ShardSchemes.

Remove Copy and Ordering derives from ShardScheme

---

gateway/src/shard/processor/inflater.rs

In cases where the second clause needed for a buffer shrink was not true the countdow
would not be reset. This casused a integer underflow the next time it was going to shrink.
If compiled with debug this caused a panic.

Fix integer underflow caused by missing reset of countdown.

---

command-parser/Cargo.toml
command-parser/benches/commands.rs
command-parser/benches/prefix.rs
command-parser/src/config.rs
command-parser/src/parser.rs

Refactor the command-parser to change a HashMap into a HashSet.

command-parser: refactor config prefixes

---

.github/workflows/test.yml
README.md
twilight/Cargo.toml
twilight/src/lib.rs

Turn the "main crate" - `twilight` - into an advertisement crate that documents the existence and usage of other crates, linking to their documentation on the `twilight.rs` website. The crate now has no contents, dependencies, or features, and has a warning in the first few sentences that is has no functionality. The installation instructions now specifically recommend installing the individual crates and provides a sample list of `Cargo.toml` `[dependencies]` entries that are likely to be popularly used.
This is a part of #459.

project: turn main crate into advertisement crate

---

.github/workflows/test.yml
gateway/Cargo.toml
gateway/README.md
gateway/src/lib.rs

This change was made to make the library not need cmake in the
most basic case.

Change default zlib backend to be system zlib.

---

README.md
gateway/examples/intents/src/main.rs
gateway/src/cluster/builder.rs
gateway/src/shard/builder.rs
twilight/src/lib.rs

Make the cluster and shard builders' `intents` methods take an `Intents` instead of an `Option<Intents>`. Taking an option is redundant since there are none by default.

gateway: make 'intents' methods non-optional

---

http/src/routing.rs

When triggering a webhook the url has a token, there was no match for that. This caused the http-proxy to reject it as invalid

correctly match webhook route with token for the proxy

---

command-parser/Cargo.toml

Add the paths for the benchmarks to the command parser's `Cargo.toml` bench entries.
If this isn't present then Cargo complains about it missing when packaging the crate.

command-parser: add bench paths to cargo.toml

---

model/Cargo.toml

Add the path for the benchmark to the model crate's Cargo.toml bench entries.
If this isn't present then Cargo complains about it missing when packaging the crate.

model: add bench path to cargo.toml

---

README.md
twilight/src/lib.rs

Fix the links to the first party crates (embed builder, lavalink, mention) in the advertisement crate's readme.

twilight: fix links to first party crates

---

model/src/id.rs
model/src/oauth/id.rs

In the model's `id` and `oauth::id` crates support the deserialization of IDs from integers. These already support deserializing from strings because that's how Discord provides them, but users may have integers due to their own applications or from other libraries serializing them that way. They continue to serialize back into strings to match Discord's format, regardless of the type they were deserialized from.
Tests and documentation have been added.
Closes #489.

model/id: support deserializing from integers

---

command-parser/Cargo.toml
command-parser/src/arguments.rs
command-parser/src/casing.rs
command-parser/src/config.rs
command-parser/src/parser.rs

Add tests for all types in the command parser crate via the `static-assertions` crate.

command-parser: add static-assertions tests

---

model/CHANGELOG.md
model/Cargo.toml

Changelog:
Fixes
- Handle webhooks with tokens in path parsing ([#499] - [@vivian])
[@vivian]: https://github.com/vivian
[#499]: https://github.com/twilight-rs/twilight/pull/499

model: bump to v0.1.1

---

http/src/request/channel/reaction/mod.rs

This PR implements a simple one-way `From<ReactionType>` conversion for `RequestReactionType`. It also derives `Eq` and `PartialEq`. Manually implementing `PartialEq<ReactionType> for RequestReactionType` would require changes in `model`, and would require `model` to depend on `http`, so convert-and-compare is the simplest way to do this. 
Fixes #505.

http/requestreactiontype: impl eq, from, partialeq

---

model/src/gateway/presence/activity_type.rs

Document the "Competing" activity type with value 5.
Documentation: <https://github.com/discord/discord-api-docs/commit/cd6c72a9a297c32ef59f3243eaddd9167fb4e1c3>

model/activity_type: document 'competing' variant

---

model/src/gateway/presence/mod.rs

Allows the use of `key()` from `PresenceUpdate` events.
Not sure if you intend for the payload types to ever implement `Key`, can remove that if so. Implementing it on `UserOrId` still makes it usable within `PresenceUpdate` so I'm not torn either way.

model/gateway: impl Key for UserOrId

---

lavalink/src/client.rs
lavalink/src/http.rs
lavalink/src/model.rs
lavalink/src/node.rs

Add additional tests for types in the lavalink crate via the `static-assertions`. Many types were missing assertions for fields and Send + Sync bounds.

lavalink: add additional static-assertions tests

---

command-parser/benches/commands.rs
model/benches/deserialization.rs

Small fix of compilation of benches.
The removal of the comma is not a compilation fix, but fixed that the deserialzation would panic.

Fix compilation and running of command and deserialization benchmarks

---

http/src/client/mod.rs

This prevents getting "400 bad request" for non get requests without a body (like DELETE)

don't set content headers when the request doesn't have a body

---

command-parser/src/config.rs
gateway/src/shard/json.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/session.rs
gateway/src/shard/stage.rs
http/src/client/mod.rs
http/src/request/channel/message/get_channel_messages.rs
http/src/request/channel/update_channel.rs
http/src/request/guild/create_guild_channel.rs
utils/embed-builder/src/builder.rs
utils/embed-builder/src/image_source.rs

I found several broken/wrong links while changing them to intra-doc links

command-parser,embed-builder,gateway,http: fix typos in links

---

utils/mention/Cargo.toml
utils/mention/src/lib.rs

Update the documentation link to accurately reflect the current link and update the description to mention the capability of parsing mentions.

mention: update docs link and description

---

http/src/client/mod.rs

Set the `content-length` header when sending requests with `PATCH`, `POST`, or `PUT` verbs. This fixes an issue where CloudFlare or Google edge routers in some physical geolocations will behave in odd ways and require a `content-length`, but won't in others.

http: set content-length for patch/post/put

---

http/src/client/mod.rs
http/src/request/channel/reaction/get_reactions.rs

This route was missing `RequestReactionType`, this PR fixes that.

http: take the correct type in client::reactions

---

twilight/Cargo.toml

Add all of the crates as development dependencies to the `twilight` crate for easy linking on crates.io.

twilight: add all crates as dev dependencies

---

model/src/user/current_user.rs
model/src/user/mod.rs
model/src/user/profile.rs

For the `CurrentUser`, `UserProfile`, and `User` model types, support deserializing discriminators from integers because some userland may have objects with them due to being a more efficient representation. Discriminators will continue to serialize back into strings because this is what Discord provides.
Tests and documentation about the behaviour on the fields have been provided.
Closes #525.

model/user: support discrim deser from integers

---

gateway/src/cluster/impl.rs

This PR adds a convenience method to the Cluster that returns all the shards

gateway: add shards method to the Cluster

---

http/src/api_error.rs

Allows http errors caused by invalid timestamps in an embed to deserialize correctly, rather than returning a serde error.
```
[src/commands/logs/cmd.rs:179] bot.http.create_message(cid).content(content)?.embed(embed.build()?)?.await = Err(
Response {
body: [
[snip]
],
error: Message(
MessageApiError {
embed: Some(
[
Timestamp,
],
),
},
),
status: 400,
},
)
```

Handle invalid timestamp error in embed response

---

http/src/request/get_user_application.rs

The method `current_user_application` used the `GetGatewayBot` routed instead of the `GetCurrentApplicationInfo` route.

Use the correct route for `http.current_user_application()`

---

gateway/queue/Cargo.toml

When I copied all the dependencies straight from gateway's Cargo.toml, it seems like some features were not specified because they were pulled in by other dependencies. This fixes compilation of twilight-gateway-queue standalone, tested on my fork of gateway-queue.
Sorry for missing that one out, I did not test the gateway-queue completely standalone without gateway until now, this definitely works now.

Fix gateway-queue standalone with sink feature

---

http/src/request/guild/integration/get_guild_integrations.rs
http/src/routing.rs
model/src/guild/integration.rs
model/src/guild/integration_application.rs
model/src/guild/mod.rs

This changeset implements the application integrations
as described in https://github.com/discord/discord-api-docs/pull/1886.
----
**Note to reviewers**: This changeset cannot be tested on Discord as they have
begun to return 403 for it even if the bot have the manage guild permission.

Implement application integrations

---

cache/in-memory/src/lib.rs

The cache_role method on the InMemoryCache struct was not inserting the roles into the guild_roles map

fix missing guild specific insert in cache_role(s) and cache_member(s)

---

cache/in-memory/src/updates.rs

there was an extra clone of the arc lead to the cache not being updated, it has been removed and tests have been added
Closes #551

Fix cache not being updated in GuildUpdate event

---

gateway/Cargo.toml
lavalink/Cargo.toml

New `async-tungstenite` version supports `tokio-rustls` which means less dependencies.

Switch to async-tungstenite/tokio-rustls

---

cache/in-memory/src/lib.rs

Same problem as in #540. Just an oversight in the development of the cache. I have added tests to prevent regressions for `cache_emoji` and `cache_emojis`. The tests were proven failing before the fix and are now passing after the fix.

cache: Fix missing guild specific insert in cache_emoji(s)

---

gateway/README.md
gateway/src/lib.rs
lavalink/README.md
lavalink/src/lib.rs

gateway, lavalink: fix async-tungstenite's `tokio-rustls` usage in docs

---

.github/workflows/doc.yml
.github/workflows/publish.yml
util/Cargo.toml
util/src/lib.rs

Rustdoc will render the item with a banner explaining that the item is
only available with certain features. See [tokio docs].
This unstable feature is conditionally enabled for CI & docs.rs
[tokio docs]: https://docs.rs/tokio/0.3.1/tokio/#modules

util: highlight features in documentation with #[doc(cfg)]

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTING.md

This adds guidelines for contributing issues and pull requests to Twilight. This PR should be approved by a majority of contributors. Please discuss and suggest changes.

project: add CONTRIBUTING.md and issue templates

---

cache/in-memory/src/lib.rs

Cache is customized with `InMemoryCache::builder` like the following example shows

cache/in-memory: remove outdated hint of customization

---

http/src/client/builder.rs

There was an oversight in the design of the `ClientBuilder` that caused the given `reqwest_client` to be ignored. My change may not be the right one, so I expect discussion on how we should fix the problem since it is not so easy as just a new line. I chose to replace the input in the `reqwest_client` function from a `ReqwestClient` to a `ReqwestClientBuilder` so that the user can configure the client on their own and the `ClientBuilder` can configure the builder with its defaults (timeout/proxy).
This does remove the `Clone` implementation from the `ClientBuilder` struct since `ReqwestClientBuilder` does not implement `Clone`
Closes #561

http: fix ClientBuilder ignoring reqwest_client

---

http/src/client/mod.rs
http/src/ratelimiting/mod.rs

This adds a method to http::Client that will expose the internal Ratelimiter and one to the Ratelimiter to provide estimates for times on buckets for a path.

http: add bucket remaining time estimation method

---

cache/in-memory/src/lib.rs
model/src/user/current_user.rs
standby/src/lib.rs

The fields `public_flags` and `premium_type` were both missing off of the `CurrentUser` struct. These are both optional, so the serialization was not affected by their absence. This does constitute as a breaking change since any de-structuring of the `CurrentUser` will no longer work, unless the rest syntax is used

model: add missing fields to CurrentUser

---

http/src/request/user/get_current_user_guilds.rs

This adds the missing features field to CurrentUserGuild as per https://discord.com/developers/docs/resources/user#get-current-user-guilds-example-partial-guild.

http: Add features field to CurrentUserGuild

---

gateway/src/cluster/builder.rs
gateway/src/shard/builder.rs
gateway/src/shard/config.rs
gateway/src/shard/impl.rs

Twilight currently gets the gateway url for each shard when starting
up, this is not reccomended by Discord and leads to ratelimiting and
therefore a slower startup for larger bots.
This change set adds a new option to the shard builder `gateway_url`
that if set will be used instead of making a request to Discord.
This is also built into the Cluster so it will only make a single
request for all the shards it is set to start up.

gateway: add option of gateway url to shard config

---

cache/in-memory/src/lib.rs
model/src/user/current_user.rs
standby/src/lib.rs

The response from a current_user request (with the `identify` scope) is as follows:
```json
{
"avatar": "a_05dcf66dd5961e3147bfdbef64282d1a",
"discriminator": "4191",
"flags": 768,
"id": "168827261682843648",
"locale": "en-US",
"mfa_enabled": true,
"premium_type": 2,
"public_flags": 768,
"username": "DusterTheFirst"
}
```
[(also discord docs for more info)](https://discord.com/developers/docs/resources/user#user-object-user-structure)
But the `CurrentUser` struct in the model requires a `verified` member which is only avaliable with the `email` scope.
I have chosen to make it an `Option<bool>` versus adding `#[serde(default)]` like with the bot bool since `verified: false` has a very different meaning than `verified: None`.

model: add Option for CurrentUser::verified

---

model/src/oauth/current_application_info.rs

The `id` field on the `CurrentApplicationInfo` struct was a `UserId` where it is actually the oauth's `ApplicationId`, so the type has been adjusted accordingly.
https://discord.com/developers/docs/topics/oauth2#get-current-application-information-response-structure

model: change type of CurrentApplicationInfo's id field

---

command-parser/Cargo.toml
command-parser/src/arguments.rs

This PR adds Unicode support to the Arguments struct along with quoted support. The previous version was unable to parse them properly, giving a false count. The PR also adds 5 new tests each containing various forms of unicode. It also switches
This also adds in a new dependency: `unicode-segmentation`

command-parser: add unicode support to the Arguments struct

---

.github/workflows/test.yml

The util crate was not fully tested via CI and needs to be added to the `test-features` build matrix.

actions: add the util crate to the test matrix

---

cache/in-memory/src/lib.rs
model/src/gateway/intents.rs

This documents gateway intents in the model crate, and also specifies in
each cache method the intents required for the method to act as
expected.
Fixes #577.

cache, model: document gateway intents

---

command-parser/src/parser.rs

Handle whitespace after the prefix. While the buffer `!bar baz` parses into the prefix `!`, command `bar`, and argument `baz` fine, the buffer `foo bar baz` parses incorrectly as the prefix `foo`, the command `bar`, and the argument buffer `r baz`.
By advancing the starting index of the Arguments iterator by the amount of the whitespace before the command name, this will properly parse. In the listed example, the iterator would be advanced by 1, due to there being 1 byte of whitespace.
A test is included.

command-parser: handle whitespace after prefix

---

README.md
gateway/README.md
gateway/src/lib.rs
http/README.md
http/src/lib.rs
lavalink/README.md
lavalink/src/lib.rs
twilight/src/lib.rs

Update the READMEs of the gateway, http, lavalink, and advertisement crates to mention version `0.2` in the installation instructions.

project: update readme installation version to 0.2

---

command-parser/Cargo.toml
command-parser/src/arguments.rs

Remove the `unicode-segmentation` dependency from the Command Parser. It was added in #575 to support unicode via `unicode_segmentation::GrapheneIndices`, but it's not actually required, as the `std::str::CharIndices` iterator is effectively the same with how it's used. Tests for unicode support are unchanged and continue to pass.

command-parser: remove 'unicode-segmentation' dependency

---

cache/in-memory/src/lib.rs
cache/in-memory/src/model/member.rs
cache/in-memory/src/updates.rs

Since `MessageCreate` events contain a `Message` which in turn contains an author `User` and a potential `PartialMember`, one might aswell cache these two.
To avoid cloning them on each event unnecessarily if they're already in the cache, I added new user/member cache functions to handle the values as references.
Also added a test case for a `MessageCreate` event.

cache/in-memory: cache MessageCreate's user & member

---

http/src/client/mod.rs
http/src/error.rs

When handling HTTP responses, check if the status code is a 503 (Service Unavailable). If so, return a new `twilight_http::Error` variant of `ServiceUnavailable` containing the response.
This fixes deserialization of the response body failing.

http: handle service unavailability errors

---

model/src/gateway/opcode.rs

Make the `twilight_model::gateway::OpCode` enum non-exhaustive, allowing us to add variants to it in the future without needing a breaking change.

model/gateway/opcode: make non-exhaustive

---

gateway/queue/src/lib.rs

Remove cross-crate links, causing broken links in rendered documentation.
Closes #559.

gateway-queue: remove cross-crate links

---

http/src/api_error.rs

Add API error codes 20022, 50024, and 50033.
- 20022: This message cannot be edited due to announcement rate limits
- 50024: Cannot execute action on this channel type
- 50033: Invalid Recipient(s)
Closes #544.

http/api_error: add variants 20022, 50024, 50033

---

http/src/client/builder.rs
http/src/client/mod.rs
http/src/error.rs

In the HTTP client take note of when the configured token is invalid and prevent new requests from being executed. This will prevent potential API bans. When an unauthorized response is encountered, the `Error::Unauthorized` variant is returned, and future request executions will short-circuit it and return it as well. A new client must be configured with a new token to issue further requests.

http/client: take note of invalid tokens

---

cache/in-memory/src/lib.rs

`cache_*` methods such as `cache_members` are private and return a collection which is never made use of.
One could make all these methods public and provide a way for the user to cache their own objects that they retrieved through `twilight_http` and let them use the cached `Arc`s straight away.
I would assume that the unnecessary overhead of creating a `HashSet` on events would still not be worth it though, so I'd just omit the return values.

cache/inmemory: cache_* methods no longer return HashSet

---

http/src/client/mod.rs
http/src/lib.rs

exposes the api version the crate uses, allows for the proxy crate to stay in sync with this

http: move api version to a public const

---

gateway/src/event.rs
model/Cargo.toml
model/src/gateway/event/kind.rs
model/src/gateway/event/mod.rs

Add error enums to use when `EventType`'s `TryFrom<&str>` implementation fails. Instead of returning the source string, return an error wrapping it that implements `Error` (and thus `Display`).

model/gateway/event_type: add error enums

---

http/src/request/guild/create_guild/mod.rs

Currently, `RoleFields` renames the `permissions` field to `permissions_new` on serialization. Since the switch to Discord API v8, this rename is no longer necessary, and leads to permissions not being applied correctly.

http: fix create guild endpoint

---

model/src/invite/channel.rs
model/src/invite/mod.rs

Discord returns only a partial channel, which cannot be deserialized into a full channel.
This commit adds a model for the partial channel (named `InviteChannel` following the convention set by `InviteGuild`)
Associated tests updated, and test for `InviteChannel` added.

model: fix invites

---

cache/in-memory/src/lib.rs
gateway/src/cluster/impl.rs
gateway/src/shard/impl.rs
http/src/client/mod.rs
lavalink/src/client.rs
standby/src/lib.rs

Clarify the cloning behavior of the cache, gateway's cluster and shard, HTTP client, Lavalink client, and Standby. Specifically, clarify that they internally wrap their data in an Arc, and so can be cheaply cloned.
Closes #562.

docs: clarify cloning behavior

---

README.md
twilight/src/lib.rs

Link to crates where possible in the advertisement crate's README.
Closes #605.

chore(twilight/readme): link to crates

---

gateway/src/shard/impl.rs

This provides a way of retrieving the session ID for a shard connection without having to call shutdown_resumable, and can be very useful in my case of validating that a certain state cache is valid.

feat(gateway): add session id to shard info

---

cache/in-memory/src/model/member.rs
cache/in-memory/src/updates.rs
model/src/channel/message/mention.rs
model/src/channel/message/mod.rs
model/src/guild/partial_member.rs
model/src/user/mod.rs

Support partial members included in mentions within messages by creating a new `Mention` type.
Closes #566.

feat(model): support message mention members

---

cache/in-memory/src/model/message.rs
cache/in-memory/src/updates.rs
http/src/api_error.rs
model/src/channel/message/mod.rs
model/src/channel/message/sticker/id.rs
model/src/channel/message/sticker/kind.rs
model/src/channel/message/sticker/mod.rs
standby/src/lib.rs

Support Message Stickers, including the Sticker itself as well Sticker and Sticker Pack IDs and Sticker Format Types.
Discord API documentation: discord/discord-api-docs@b9ffd52
Closes #589.

feat(http,model): support message stickers

---

gateway/src/cluster/builder.rs

The current `gateway_url` config on cluster builder is no-op, and is always fetched from the rest api.

fix(gateway): fix unused gateway_url config

---

http/src/client/mod.rs

Use reqwest's `HeaderName` constants for insertion into header maps and when specifying a header name in errors. This avoids hardcoded strings.
Closes #617.

fix(http/client): use reqwest header name consts

---

model/src/channel/message/mod.rs

Messages may not contain a `stickers` field, this fixes deserialization when the field is absent.

fix(model): fix deserialization for message without stickers

---

cache/in-memory/src/updates.rs
http/src/request/channel/message/allowed_mentions.rs
http/src/request/channel/message/create_message.rs
model/src/channel/message/kind.rs
model/src/channel/message/mod.rs
model/src/channel/message/reference.rs
standby/src/lib.rs

This changeset adds support for replies as described in the
following pr:
https://github.com/discord/discord-api-docs/pull/2118
and the subsequent commit
https://github.com/discord/discord-api-docs/commit/e2cbad6830e627721e4b2d10cf71770ab3a94fa3
The `referenced_message` field in the `Message` struct is boxed as I
think it is a good compromise instead of doubling the memory usage of
the object, I would like to hear others opinion of this.

http,model: add support for message type 19 replies

---

http/src/request/channel/update_channel_permission.rs
http/src/request/channel/update_channel_permission_configured.rs
model/src/channel/permission_overwrite.rs

In the `UpdateChannelPermission` request builder, use the integer values of permission types (0 for role, 1 for member) instead of string values ("role" and "member", respectively). This required v8 change wasn't picked up in the initial implementation. To do this, the internal `PermissionOverwriteTypeName` repr enum has been exposed.
Tests have been added for the permission overwrite type name and the request body itself.
Closes #613.

fix(http/update_channel_permission): use type ints

---

gateway/src/shard/processor/impl.rs
model/src/gateway/payload/identify.rs

The field is named `compress` and not `compression`.
See https://discord.com/developers/docs/topics/gateway#identify-identify-structure.

fix(model): fix identify compress field

---

http/src/request/user/get_current_user_guilds.rs
model/src/user/current_user_guild.rs
model/src/user/mod.rs

This PR moves the CurrentUserGuild struct from http to model. This allows developers to prevent pulling in the http crate for cases where the http client is not needed. (e.g. oauth-related workflows)

model: move CurrentUserGuild from http to model

---

README.md
cache/in-memory/README.md
cache/in-memory/src/lib.rs
command-parser/README.md
command-parser/src/lib.rs
embed-builder/README.md
embed-builder/src/lib.rs
gateway/README.md
gateway/src/lib.rs
http/README.md
http/src/lib.rs
lavalink/README.md
lavalink/src/lib.rs
mention/README.md
mention/src/lib.rs
model/README.md
model/src/lib.rs
standby/README.md
standby/src/lib.rs
twilight/src/lib.rs
util/README.md
util/src/lib.rs

In the badges and root installation instructions, note the MSRV required via #636 of Rust 1.48+.
Closes #635.

docs: note msrv of 1.48+

---

cache/in-memory/src/lib.rs
model/src/gateway/payload/role_update.rs
model/src/guild/mod.rs
model/src/guild/role.rs
model/src/guild/role_tags.rs

Support Role Tags as part of Roles. The Role Tags type has 2 "normal" fields: `bot_id` and `integration_id`. These fields are either not present (meaning null) or present with a value.
There is also a third field called `premium_subscriber`. When not present, the field's real meaning is false. When present, the value is null, with a real meaning of true.
When serializing the Role Tags, we can use this information to conditionally serialize back into the source payload by serializing fields back into the way they started.
Closes #631.

feat(model/guild): support role tags 

---

gateway/src/cluster/builder.rs
gateway/src/cluster/impl.rs
gateway/src/shard/builder.rs
gateway/src/shard/config.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/session.rs
http/src/client/builder.rs
http/src/client/mod.rs

Where possible, internally use `Box<str>` over Strings. This is particularly useful where we keep strings but won't ever mutate them again. This will reduce the size from 24 bytes to 16 bytes.
This does not change public APIs.

Gateway, HTTP: Use Box<str> over String

---

command-parser/src/casing.rs
command-parser/src/config.rs
command-parser/src/lib.rs

`CommandParserConfig` exposes four iterators in total for iterating over the commands and prefixes of a configuration. These iterators aren't public and can't be named or documented due to not being re-exported from the root and the containing module being private. To fix this, make the `config` module public and document them.

docs(command-parser): export config iterators

---

gateway/README.md
gateway/src/lib.rs

Document the gateway's `metrics` feature and a couple examples of metrics logged. This feature is disabled by default.
Closes #627.

docs(gateway): document the 'metrics' feature

---

cache/in-memory/src/updates.rs

The voice state update event contains a partial member object from which a full member object can be constructed using other fields on the event.
This deserialisation is already done, so the member object may as well be added to the cache.
This is useful for bots that do not have the members intent but want to know about members when they are connected to voice.

feat(cache): add member deserialized from voice state event to cache

---

model/src/guild/role_tags.rs

Add a `Visitor::visit_unit` implementation to the `PremiumSubscriberVisitor` in the `RoleTags` deserializer.
`serde_json` uses `Visitor::visit_none` to handle present `null` values, but other implementations such as `simd-json` can/do use `Visitor::visit_unit` instead. `serde_json` does not use `visit_unit`, so we need to support both. In order to handle `simd-json` and any other implementations, handle both.
Refer to https://github.com/simd-lite/simd-json/issues/160 for bug details.

fix(model/role_tags): add visit_unit visitor

---

http/Cargo.toml
http/src/client/mod.rs
http/src/request/audit_reason.rs
http/src/request/channel/allowed_mentions.rs
http/src/request/channel/message/mod.rs
http/src/request/channel/mod.rs
http/src/request/channel/webhook/delete_webhook_message.rs
http/src/request/channel/webhook/mod.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/routing.rs

Support two new Webhook routes: message updating and message deleting.
If the ID of a message created by a webhook is kept, it can be used with `Client::update_webhook_message` to update a webhook's created message by ID. The route supports updating the content and embeds.
Additionally, `Client::delete_webhook_message` can take the message ID to delete it, but only if the message was created by the webhook.
Checklist:
Closes #640.

feat(http): support webhook message delete, update

---

gateway/src/shard/processor/inflater.rs

The inflater buffer is changed to resize on an interval of at least 60 seconds, instead of once per 255 payloads if the shrink capacity is less than 4 times the size. The issue of sometimes not shrinking the buffer at all is also fixed.

refactor(gateway): refactor inflater buffer resize

---

http/Cargo.toml
http/README.md
http/examples/allowed-mentions/src/main.rs
http/examples/proxy/src/main.rs
http/src/client/builder.rs
http/src/client/mod.rs
http/src/error.rs
http/src/lib.rs
http/src/ratelimiting/error.rs
http/src/ratelimiting/headers.rs
http/src/request/channel/message/create_message.rs
http/src/request/guild/get_guild_vanity_url.rs
http/src/request/guild/member/get_member.rs
http/src/request/mod.rs
http/src/request/multipart.rs
http/src/routing.rs
lavalink/examples/basic-lavalink-bot/Cargo.toml
lavalink/examples/basic-lavalink-bot/src/main.rs

Use `hyper` as the backing HTTP client instead of `reqwest`.
This reduces the depth of the dependency tree and allows us to update faster when downstream crates have breaking changes that break our API and reduces the dependency count. The dependency count has been reduced from 126 to 111.
This comes with mostly minimal API changes:
- `ClientBuilder::build` no longer returns a `Result`
- `ClientBuilder::reqwest_client` is now `hyper_client`
- `ClientBuilder::{proxy_http, proxy}` are combined into `ClientBuilder::proxy` and take an `impl Into<Box<str>>`
- `Client::raw` now returns a Hyper `Response<Body>` instead of a Reqwest one
- `error::UrlError::UrlParsing` has been removed
- `error::Error::BuildingClient` has been removed
- `error::Error::{ChunkingResponse, RequestError}` are now …

feat!(http): use hyper instead of reqwest

---

gateway/src/shard/mod.rs
gateway/src/shard/raw_message.rs
gateway/src/shard/sink.rs

Hide the `tungstenite` dependency from the public API. Currently, this is exposed via `shard::Sink` and `shard::Shard::sink`, which take `tungstenite::Message`s as input.
To avoid locking the public API to a specific version of a mostly internal dependency, create our own `Message` that mostly maps to `tungstenite::Message`. This new message can be constructed by users and passed in, and will be translated to a `tungstenite::Message` internally.
This means we can upgrade `async-tungstenite` without breaking the public API.

Hide `tungstenite` from public API

---

cache/in-memory/Cargo.toml
command-parser/Cargo.toml
gateway/Cargo.toml
lavalink/Cargo.toml
standby/Cargo.toml

Update `dashmap` from `3` to `4.0` which is used in the `cache-inmemory`, `gateway`, `lavalink`, and `standby` crates. 
Additionally, update `patricia_tree` which is a benchmark development dependency of `command-parser`.
Since these aren't exposed via public API these aren't breaking changes.
PR note: I typo'd dashmap as hyper in the branch name. Hyper is unrelated.

chore: update dashmap, patricia_tree

---

http/src/client/mod.rs
http/src/request/guild/member/add_role_to_member.rs

Remove `Client::add_role` because it's a duplicate of `Client::add_guild_member_role`. `Client::remove_role` doesn't exist but `Client::remove_guild_member_role` does, so that is the established pattern.
Supersedes #668.

Remove the HTTP client's `add_role` method

---

http/src/client/mod.rs
http/src/error.rs
util/Cargo.toml
util/src/lib.rs
util/src/link/mod.rs
util/src/link/webhook.rs

Remove methods in the client to perform webhook actions by webhook URL.
These methods include:
- delete_webhook_from_url
- execute_webhook_from_url
- update_webhook_with_token_from_url
- update_webhook_from_url
There's not really any *programmatic* reason to have these methods. You don't receive URLs from the API. The only place you get them from is the GUI desktop client, which can easily have the token and ID manually taken out from anyway.
This also removes the `error::UrlError` type and `error::Error::Url` variant, as well as the `url` dependency.

Move webhook URL methods to util

---

README.md
cache/in-memory/src/builder.rs
cache/in-memory/src/config.rs
cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs
twilight/src/lib.rs

Simplify the `EventType` bitflags for configuring what events to cache into new `ResourceType` bitflags. `ResourceType` instead has variants like `CHANNEL` and `MEMBER`, combining all of the possible related event types.
In a longer example, say that you had:
- `EventType::CHANNEL_CREATE`
- `EventType::CHANNEL_DELETE`
- `EventType::CHANNEL_PINS_UPDATE`
- `EventType::CHANNEL_UPDATE`
- `EventType::MESSAGE_CREATE`
- `EventType::MESSAGE_DELETE`
- `EventType::MESSAGE_DELETE_BULK`
- `EventType::MESSAGE_UPDATE`
These are now `ResourceType::CHANNEL` and `ResourceType::MESSAGE`.

Replace cache event type flags with resource type flags

---

http/Cargo.toml
lavalink/examples/basic-lavalink-bot/Cargo.toml

This removes the http1 feature flag from hyper. It means that all connections made will use http2, which is supported by Cloudflare and Discord and has [several advantages](https://blog.restcase.com/http2-benefits-for-rest-apis/) over http1, especially when the same server is requested over and over again, which is the case here.
http1 pulls in quite a bit of conditionally compiled code that won't be used and might make the connections use http1, which isn't desired. Both Discord/Cloudflare and Lavalink support http2 and would benefit from it, so forcing the use of it would only make sense. If a user would like to keep using http1, they can add a `hyper = { version = 0.14, features = ["http1"] }` to their Cargo.toml to force enabling the feature.
Not adding lavalink tag because it only …

http, lavalink: Remove http1 feature flag from hyper

---

cache/in-memory/src/lib.rs
cache/in-memory/src/model/message.rs
cache/in-memory/src/updates.rs
model/Cargo.toml
model/src/channel/message/mention.rs
model/src/channel/message/mod.rs
model/src/channel/mod.rs
model/src/gateway/payload/guild_emojis_update.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/payload/ready.rs
model/src/gateway/presence/mod.rs
model/src/guild/emoji.rs
model/src/guild/integration.rs
model/src/guild/member.rs
model/src/guild/mod.rs
model/src/guild/partial_guild.rs
model/src/guild/role.rs
model/src/guild/status.rs
model/src/user/connection.rs
model/src/user/mod.rs
model/src/voice/voice_state.rs
standby/src/lib.rs

Use Vecs to store lists of entities instead of HashMaps. HashMaps will take a bit more memory and time to deserialize and a `Vec` is closer to the actual API representation. If users need a HashMap of a list of entities then one can easily be made via `HashMap::from_iter`.
This also removes the `serde-mappable-seq` dependency, which is deprecated.

Use Vecs in models instead of HashMaps

---

LICENSE.md

Only the year the copyright was introduced by a new party is needed in
the MIT license, so this patch makes the license file more simple so
it does not need to be updated in the future.

Simplify license.

---

http/examples/allowed-mentions/src/main.rs
http/src/client/builder.rs
http/src/client/mod.rs
http/src/request/channel/allowed_mentions.rs
http/src/request/channel/message/create_message.rs
http/src/request/channel/message/mod.rs
http/src/request/channel/message/update_message.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/request/user/get_current_user_guilds.rs

Remove the following re-exports:
- `request::user::get_current_user_guilds::CurrentUserGuild`: instead use `twilight_model::user::CurrentUserGuild`
- `request::channel::message::allowed_mentions`: instead use `request::channel::allowed_mentions`

chore(http): remove re-exports

---

gateway/Cargo.toml
lavalink/Cargo.toml
lavalink/src/node.rs

Newest version no longer pulls in `pin-project` and `bytes` 0.5

chore(gateway,lavalink): update to async-tungstenite 0.12

---

gateway/src/shard/processor/impl.rs
http/Cargo.toml
http/src/client/builder.rs

Alternative to #678 
hyper-tls currently is broken when only http2 is enabled because it does not send ALPN protocols unlike rustls (https://github.com/hyperium/hyper-tls/pull/85 is pending for a while now, hyper-rustls pulls in http1 always (see https://github.com/ctz/hyper-rustls/pull/139)).
As we know that http2 is enabled, we can safely send the ALPN ourselves until the hyper-tls PR gets merged, which will require hyper to expose which http versions are enabled and therefore will take longer.

http: Work around http2 hyper-tls bug

---

command-parser/src/arguments.rs
http/src/client/mod.rs

hyper's `RequestBuilder.header` method internally calls `.append` on the HeaderMap (see [here](https://docs.rs/http/0.2.3/http/request/struct.Builder.html#method.header)), which allows for duplicate headers. This won't happen unless a custom `TwilightRequest` is used to make a raw request and happens in the proxy when using the request headers and trying to merge them with the ones twilight adds, as it will just append them, causing 400 errors from Cloudflare.
This makes use of `HeaderMap.insert` to overwrite earlier headers with the same name and prevent this issue. Since hyper's `headers_mut` returns an Option created via `.ok()`, I cannot propagate this into a http::Error and need to do a lot of Option handling for safety.
Tested working with a 0.3 version of the proxy which I will …

http: Use HeaderMap.insert instead of appending

---

http/src/request/channel/reaction/create_reaction.rs
http/src/request/channel/reaction/mod.rs

Going from 0.2 to 0.3 breaks create_emoji, and possibly other endpoints involving emojis.
It seems they are no longer getting percent encoded. This results in `Error: BuildingRequest { source: http::Error(InvalidUri(InvalidUriChar)) }` when running the code from the method's documentation.
I can't find any sign of a change that would have lead to this unless it was done automatically under reqwest, but not when using hyper directly.
Making the following modification to the example code works:
```rust
let emoji = RequestReactionType::Unicode {
name: utf8_percent_encode("🌃", NON_ALPHANUMERIC).to_string(),
};
```
I think it would be better if Twilight did this though; perhaps through a change to format_emoji as found in this PR.

fix(http): percent encode emoji in URIs

---

embed-builder/README.md
embed-builder/src/author.rs
embed-builder/src/builder.rs
embed-builder/src/field.rs
embed-builder/src/footer.rs
embed-builder/src/lib.rs
http/src/request/channel/webhook/update_webhook_message.rs

Simplify the error handling of the Embed Builder and all of its sub-builders. Instead of returning a unique error for any method that can error, use the pattern of delayed error handling: accept potentially invalid input and then, when building the final embed, check all of the input and error if necessary.
Over time we've acquired feedback that the embed builder is difficult to use. There are too many reasons for erroring, and many of the methods can return one. By lazily returning errors when finishing the builder, we can also perform the step of checking the total length of the content of the embed. This removes the duplication of work.

Simplify Embed Builder error handling

---

http/src/client/mod.rs

I missed out in #683 that there is another instance in the http client where a `HttpsConnector` is created, which was in the default `Client::new`.
Since the logic from there is duplicated from the builder defaults, it makes sense to just use the builder defaults and this will also send the ALPN then.

fix(http): Use ClientBuilder defaults in Client::new

---

gateway/src/cluster/mod.rs

Expose the `cluster::r#impl::ClusterSendError` type from `cluster`. `ClusterSendError` is returned by `Cluster::send`, however was not exposed from the module and thus can not be named.
Related to #679.

Expose gateway cluster's send error type

---

command-parser/src/casing.rs
command-parser/src/config.rs
command-parser/src/lib.rs

Hide the `unicase` dependency from the API. Our `CaseSensitivity` enum contains two variants, one which contains `unicase::UniCase`. `CaseSensitivity` is exposed through the `config::Commands` and `config::CommandsMut` iterators. Instead of returning it as the item, return a tuple of the string and whether it's case-sensitive.

Hide command parser's unicase dependency

---

gateway/src/shard/processor/impl.rs
model/src/gateway/payload/identify.rs

Removes the defunct version param from the identify payload

fix(gateway): remove useless version param from identity payload

---

http/src/client/mod.rs

Add a note to the documentation of `twilight_http::client::Client` about the usage of OAuth bearer tokens.

Add note to HTTP client about using bearer tokens

---

model/src/gateway/payload/message_update.rs

The mentions field in the message update payload is updated to use the new mention type.

fix(model): use mention type for message update

---

lavalink/src/client.rs
lavalink/src/node.rs
lavalink/src/player.rs

Rework Lavalink players into not needing mutability by using atomic integers within them. Additionally, simplify the `PlayerManager` interface by returning simple `Player` types from `PlayerManager::get` and `PlayerManager::get_or_insert`.
This also now hides `dashmap` from the public API.

Simplify Lavalink player API

---

cache/in-memory/src/lib.rs

The cache wasn't removing emojis when it processed GuildEmojisUpdate events, so the only way they would ever get nuked is when the guild itself left. 
Fixes it by checking what emotes the cache has vs the update has and removing the difference from the cache before proceeding to cache the emojis in the update. Test included :D

Remove deleted emojis from cache when processing GuildEmojisUpdate events

---

http/src/api_error.rs

https://github.com/discord/discord-api-docs/commit/0345b9fc3332d54820c0f728c7377a36b19a846f#diff-2adb841744dbfb715ce95d82e0c7bad2a498da041ee52c1282e2336286b8361a

Add `InvalidWebhookToken` variant to `api_error`

---

gateway/Cargo.toml
lavalink/Cargo.toml

New version for `tungstenite` 0.13

chore(gateway,lavalink): update to async-tungstenite 0.13

---

cache/in-memory/src/lib.rs
command-parser/benches/commands.rs
command-parser/src/arguments.rs
embed-builder/src/builder.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/emitter.rs
http/src/lib.rs
http/src/ratelimiting/bucket.rs
model/src/gateway/payload/guild_delete.rs

Clippy got an upgrade in Rust 1.50 apparently. This should make CI stop failing the lint step.

chore(command-parser): Get rid of new Clippy warnings

---

model/src/gateway/payload/member_update.rs

In response to https://github.com/discord/discord-api-docs/issues/2567#issuecomment-780844670, a `#[serde(default]` has been added to the `pending` field on Guild Member Update

Fix missing pending field warning on Guild Member Update

---

embed-builder/src/author.rs
gateway/Cargo.toml
gateway/queue/Cargo.toml
gateway/src/lib.rs
gateway/src/shard/processor/impl.rs
http/Cargo.toml
http/src/client/builder.rs
http/src/lib.rs
util/src/link/webhook.rs

This cleans up some TLS stuff to make it work in every scenario possible.
It effectively reverts #683 and replaces it with the `http1` feature flag because hyper-tls is not currently in a state where we can use ALPN at all. Enabling http1 would cause it to always handle everything as http1 even when http2 ALPN is negotiated. For that we should keep an eye on https://github.com/hyperium/hyper-tls/pull/85.
It also fixes #703 by adding features for webpki-roots called `rustls-webpki-roots` and renaming `rustls` to `rustls-native-roots` while keeping `rustls` as an alias to preserve backwards compatibility.
It might be worthwhile considering not using native roots at all since async-tungstenite can only use webpki-roots and there's no benefit to using two different certificate roots at once. …

Add webpki-roots feature flags and revert hyper-tls workaround

---

model/src/gateway/payload/update_status.rs

It must be null, not omitted. Else gateway will close with "Unknown opcode."

Don't omit activities field of `UpdateStatusInfo` if None

---

lavalink/src/client.rs
lavalink/src/node.rs
lavalink/src/player.rs

Also added PlayerManager::destroy to provide a managed way to destroy players both locally and on remote nodes, and cleaned up several methods that shouldn't be asynchronous or require mutable references.

Fixes #726: Adds mutable volume and channel IDs for players

---

lavalink/src/node.rs

#729, but targeting the right branch. orz
Removes an unnecessary async from Node::players.

v0.4 Lavalink: Remove unnecessary async.

---

gateway/src/shard/processor/impl.rs

This is safe as we know that discord is not a malicious actor.
Also see https://github.com/serenity-rs/serenity/pull/618

Remove the limit on frame size on the websocket

---

cache/in-memory/src/lib.rs
http/src/api_error.rs
http/src/request/channel/allowed_mentions.rs
model/src/gateway/payload/member_chunk.rs
model/src/gateway/presence/mod.rs

Fix Clippy lints introduced in the release of Rust 1.51.
Two enum variants have been marked with an #[allow] to prevent changing their names. These should be renamed at a later major version.

ci(clippy): fix rust 1.51 clippy lints

---

http/src/client/mod.rs

This PR fixes setting the request & default headers after the content headers so that when the raw method is invoked with a `CONTENT-TYPE` header, it is not incorrectly overwritten. This also fixes sending attachments with the http-proxy.

fix(http): Set request headers & default headers after content headers

---

gateway/src/cluster/builder.rs
gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/cluster/scheme.rs

Add a `cluster::ShardScheme` variant for handling large bot buckets. The variant includes three fields: `bucket_id`, `concurrency`, and `total`. Large bots are given a concurrency value for how many shards they are allowed to start at once, and along with the preferred total this can be used to determine the number of buckets the bot uses.
A bot may have a concurrency limit of 16 shards, and if the bot is in around 320'000 servers, then the bot may choose to use 320 shards. This results in 20 buckets. The bot will manage every 20 shards, starting with the shard ID equal to the bucket ID. This means a cluster managing bucket 0 will manage shard IDs 0, 20, 40, and so on, up to 300.
`ShardScheme::TryFrom<(u64, u64, u64)>` has been added for safely constructing bucket schemes.
Supersedes PR …

Add gateway shard scheme bucket variant

---

cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs

Storing the cached messages in a VecDeque instead of a BTreeMap has some performance implications:
- `MessageDelete`, `MessageDeleteBulk`, `MessageUpdate`, `ReactionAdd`, `ReactionRemove`, `ReactionRemoveAll`, and `ReactionRemoveEmoji` events now have a message lookup of O(n) instead of O(log n).
- `MessageCreate` now performs in O(1) instead of O(log n)
Additionally, the cache's `message` method now operates in O(n) instead of O(log n).
Another thing to note is the message order:
- In a BTreeMap messages are ordered by their id. This would be incorrect in case an older message has a larger id than a newer message.
- In a VecDeque messages are ordered by the `MessageCreate` arrival order. This would be incorrect in case older messages arrive after newer messages. It also prevents using a …

cache: use VecDeque instead of BTreeMap for messages

---

Cargo.toml
lavalink/src/model.rs

This event is fired when either Discord or Lavalink close the voice websocket connection. This may happen , for example, when a moderator forcefully disconnects the bot user from the guild channel, and this would be necessary to clean up local resources in the case of a disconnect (i.e. drop a local player queue).
IncomingEvent is tagged with `#[non_exhaustive]`, so this technically isn't a breaking change. If it would be easier to target trunk, I can retarget this PR if need be.

Lavalink: Add missing WebsocketClosed event.

---

http/src/routing.rs

Rename the `Path::WebhooksIdTokenMessageId` enum variant to `Path::WebhooksIdTokenMessagesId` for consistency.
Relates to #743 where a TODO was initially written in.

Rename HTTP path variant variant for consistency

---

http/src/client/mod.rs
http/src/request/channel/invite/create_invite.rs
http/src/request/channel/invite/mod.rs
http/src/request/validate.rs

Return an error from `twilight_http::request::channel::invite::CreateInvite`'s `max_age` and `max_uses` methods when the input is out of the bounds of the API's accepted values.
Tests are included.

Return validation errors from CreateInvite request methods

---

model/src/guild/audit_log/entry.rs

The `AuditLogEntry::user_id` field is now nullable, per <https://github.com/discord/discord-api-docs/commit/367ea81704dd089481e9865678355a5a8b422088>.
Although this is a breaking change our semver policy on the `model` crate is different, so this can go on `trunk`.

`AuditLogEntry::user_id` is now nullable

---

http/src/api_error.rs

Add API error code 60003, which is defined as "Two factor is required for this operation."
Per <https://github.com/discord/discord-api-docs/commit/17a2d897ed94f1f67cee1000d561f2dc49a84b4a>.

feat(http/api_error): add code 60003 'two factor'

---

http/src/request/channel/invite/create_invite.rs

Rename the `target_user` payload field in the Create Invite request to `target_user_id`. The `CreateInvite::target_user` method has been deprecated and `CreateInvite::target_user_id` has been created in its place.
Per <https://github.com/discord/discord-api-docs/commit/ad3a7fd17e8142e086deaa255494be95c7b64635>.

Rename Create Invite payload field `target_user` to `target_user_id`

---

model/src/channel/attachment.rs

https://github.com/discord/discord-api-docs/commit/b7278cbe36107c0b40487e254a00c17fdf62cbd7

fix(model): attachment width/height are optional

---

model/src/channel/mod.rs
model/src/channel/voice_channel.rs

Add the `VoiceChannel::rtc_region` field.
Docs: <https://github.com/discord/discord-api-docs/commit/fd7c6e44a6fdf8c1b0ca88de1faffb2b2b91bb53>

Add `VoiceChannel::rtc_region`

---

http/src/api_error.rs

Add API error code 10062, which is defined as "Unknown interaction."
Per <https://github.com/discord/discord-api-docs/commit/3923a63b548616552112cc0b6bfed3ed8a370dbf>.

Add HTTP error code 10062

---

model/src/guild/role.rs

Role ordering can be done `position`, but Discord provides zero guarantees that positions are unique, positive, or contiguous. In the case of positions being equal, order is deferred to an ordering based on ID. This is not immediately apparent, nor easy to replicate where needed. 
This PR implements both `Ord` and `PartialOrd` on Role to provide a consistent implementation for ordering roles.
Added appropriate unit tests.
There is one thing missing from this PR. The `@everyone` role is always at the bottom of the role list and has an ID equal to the guild's ID. In the odd case that the role doesn't have a position of 0, this implementation might be wrong. However, adding this will require access to the guild ID in some way (changing the actual contents of the model), or using less …

Implement Ord and PartialOrd on Role

---

mention/src/parse/iter.rs

Remove the `Debug` bound on the `mention` crate's `MentionIter` `Iterator` implementation. This isn't necessary as no Debug formatting is performed.

Remove MentionIter's Debug bound

---

http/src/ratelimiting/headers.rs

Global ratelimits were not being parsed prior to other headers, meaning that the absense of other headers would cause all parsing to fail. By parsing the `x-ratelimit-global` header as the first step we short-circuit on global ratelimits.
Notably `x-ratelimit-reset-after` is not in the response but `retry-after` is.

Correctly parse global ratelimit headers

---

http/src/ratelimiting/bucket.rs
http/src/ratelimiting/headers.rs

When a global ratelimit is received and the global lock is locked, sleep for the provided number of seconds instead of milliseconds. These headers with these values are not in milliseconds.

fix(http/bucket): sleep in seconds on global lock

---

http/src/client/builder.rs
http/src/client/mod.rs

Remove the `ClientBuilder::hyper_client` method so that we don't expose `hyper`. This also removes the `From` implementation. We can add an implementation in the future to configure the hyper client if needed.
Part of #714.

Remove hyper builder method

---

command-parser/src/arguments.rs

Remove the `From<&str>` impl for `Arguments` in favor of using `Arguments::new`. There's no reason to have both.

Remove command parser arguments From implementation

---

http/src/client/mod.rs
http/src/request/guild/member/update_guild_member.rs

After updating a member via the `UpdateGuildMember` HTTP request, return an updated copy of the member newly returned from the API.
This was added to the API in [@discord/discord-api-docs:f21d1fa].
Closes #694.
[@discord/discord-api-docs:f21d1fa]: https://github.com/discord/discord-api-docs/commit/f21d1fa8f322e2301959e5c0662a7b14624a9be3

Return updated member on guild member update request

---

cache/in-memory/src/updates.rs
model/src/gateway/payload/member_update.rs

https://github.com/discord/discord-api-docs/commit/fa9a0739eeedf3ff380b77b9fdcf1302aa1b0c26

feat(model): guild member update includes deaf, mute

---

lavalink/src/client.rs
lavalink/src/node.rs
lavalink/src/player.rs

Hide the `futures-channel` dependency from the API by wrapping it with a newtype implementing the same API.
Part of #714.

Hide Lavalink's external dependencies

---

gateway/Cargo.toml
gateway/src/cluster/impl.rs
gateway/src/shard/processor/inflater.rs

Existing metrics exporters currently rely on 0.14. This PR bumps the gateway's dependency to match these crates.

gateway: Update metrics to v0.14

---

lavalink/src/client.rs
lavalink/src/node.rs

- Added `Node::close` to close terminate the connection.
- Added `Lavalink::disconnect` to close the websocket connection to a specified node and remove it from the manager.
- Updated `Lavalink::best` to only consider connected nodes.
- Implemented `Drop` for `Connection` which removes all players associated  with the connection.

Lavalink:  Add methods to close and cleanup connections to Lavalink nodes

---

cache/in-memory/src/lib.rs
cache/in-memory/src/updates.rs
model/src/channel/mod.rs
model/src/gateway/payload/voice_state_update.rs
model/src/guild/mod.rs
model/src/guild/permissions.rs
model/src/voice/voice_state.rs

As seen in: discord/discord-api-docs#2751.
* Added `GuildChannel::Stage` variant, containing a  `VoiceChannel`.
* Added `REQUEST_TO_SPEAK` permission.
* Added optional `request_to_speak_timestamp` to `VoiceState`
* ~~Unrelated: Added missing `USE_SLASH_COMMANDS` permission.~~

models: Implement stage channels

---

model/src/guild/permissions.rs

Adds the missing USE_SLASH_COMMANDS  permission.

model: Add missing USE_SLASH_COMMANDS permission

---

http/src/client/mod.rs
http/src/request/mod.rs
http/src/routing.rs

Use a custom Method enum instead of exposing `hyper`'s. This is mostly equivalent to `hyper`'s `Method` type but uses enum variants instead of struct constants.
Part of #714.

Use custom HTTP Method enum instead of hyper's

---

http/src/api_error.rs

This patch adds support for the following json error codes:
10057 - Unknown guild template
20028 - The channel you are writing has hit the write rate limit
30031 - Guild already has a template
30035 - Maximum number of bans for non-guild members have been exceeded
50074 - Cannot delete a channel required for Community guilds

Add missing JSON errors

---

.github/workflows_disabled/lint.yml

The newest lint we're catching on in beta is still marked as
experimental in stable. This workflow causes PRs to fail while making
fixes for those failures out of scope for the PR.

Disable clippy beta

---

http/src/routing.rs

Percent encode reason, as it would else fail with symbols like space
as they may not be in a url.

Percent encode reason

---

cache/in-memory/CHANGELOG.md
cache/in-memory/Cargo.toml
command-parser/CHANGELOG.md
command-parser/Cargo.toml
embed-builder/CHANGELOG.md
embed-builder/Cargo.toml
gateway/CHANGELOG.md
gateway/Cargo.toml
gateway/queue/CHANGELOG.md
http/CHANGELOG.md
http/Cargo.toml
lavalink/CHANGELOG.md
lavalink/Cargo.toml
mention/CHANGELOG.md
mention/Cargo.toml
model/CHANGELOG.md
model/Cargo.toml
standby/CHANGELOG.md
standby/Cargo.toml
twilight/CHANGELOG.md
twilight/Cargo.toml
util/CHANGELOG.md
util/Cargo.toml

Crate changelogs for version 0.4.0. I imagine I've missed either a named anchor for the GitHub tag at the bottom of each changelog, an author link, or a commit, so if everyone could take a look for their commits I'd appreciate it.

Release v0.4.0

---

gateway/tests/test_shard_command_ratelimit.rs
model/Cargo.toml
model/src/gateway/presence/activity.rs
model/src/gateway/presence/activity_button.rs
model/src/gateway/presence/mod.rs

Support `ActivityButton`s in `Activity`s.
Docs: <https://github.com/discord/discord-api-docs/commit/5d1f03c1ad8c0a83f50e6693aeb8416aa9707a55>

Support activity buttons

---

.github/workflows/publish.yml
CONTRIBUTING.md
README.md
cache/in-memory/README.md
cache/in-memory/src/lib.rs
command-parser/README.md
command-parser/src/lib.rs
embed-builder/README.md
embed-builder/src/builder.rs
embed-builder/src/footer.rs
embed-builder/src/lib.rs
gateway/README.md
gateway/src/lib.rs
http/README.md
http/src/lib.rs
lavalink/README.md
lavalink/src/lib.rs
mention/README.md
mention/src/lib.rs
model/README.md
model/src/lib.rs
standby/README.md
standby/src/lib.rs
twilight/src/lib.rs
util/README.md
util/src/lib.rs

The primary branch has been renamed from 'trunk' to 'main', so the GitHub workflows, CONTRIBUTING document, and crate and project READMEs need to be updated to reflect that.

Rename 'trunk' branch references to 'main'

---

cache/in-memory/src/lib.rs
cache/in-memory/src/stats.rs

Add an interface for retrieving the number of entities of a resource in
the cache.
The new `InMemoryCacheStats` type wraps around an immutable reference to
an `InMemoryCache`. The type contains methods named after each resource,
like `guilds` or `groups` and returns `usize`s of the number of entities
within each. These simply call `DashMap::len`.
Some methods, such as `guild_emojis`, count the number of emojis in a
guild. For these methods an `Option` is returned because the guild may
not be cached yet.
Closes #798.

Add cache stats API

---

http/src/client/mod.rs
http/src/request/channel/mod.rs
http/src/request/channel/stage/create_stage_instance.rs
http/src/request/channel/stage/delete_stage_instance.rs
http/src/request/channel/stage/get_stage_instance.rs
http/src/request/channel/stage/mod.rs
http/src/request/channel/stage/update_stage_instance.rs
http/src/request/prelude.rs
http/src/request/validate.rs
http/src/routing.rs
model/src/channel/mod.rs
model/src/channel/stage_instance.rs
model/src/id.rs

Adds:
* `http` `Client::create_stage_instance`
* `http` `Client::delete_stage_instance`
* `http` `Client::stage_instance`
* `http` `Client::update_stage_instance`
* `model` `StageId`
* `model` `StageInstance`
https://github.com/discord/discord-api-docs/commit/f019fc358047050513c623f3639b6e96809f9280

feat(http, model): implement stage instances

---

gateway/src/lib.rs
gateway/src/shard/processor/socket_forwarder.rs

Remove usage of the `tokio::select!` macro in favor of `futures_util::future::select`. This allows us to remove a peer feature dependency on `tokio`'s `macros` feature; users had to manually enable this feature to use the gateway crate if it wasn't enabled elsewhere.
Additionally, this allows us to remove the recursion limit setting.

Remove gateway `tokio::select!` macro usage

---

http/src/request/channel/update_channel.rs

Set the body of `UpdateChannel` to include the serialized fields.
This was accidentally left out during the method rewrite in #814.

fix(http/update_channel): serialize fields as body

---

cache/in-memory/README.md
cache/in-memory/src/lib.rs
gateway/examples/intents/src/main.rs
gateway/examples/request-members/src/main.rs
gateway/examples/shard/src/main.rs
gateway/src/cluster/impl.rs
gateway/src/shard/impl.rs
gateway/tests/test_shard_command_ratelimit.rs
gateway/tests/test_shard_state_events.rs
lavalink/README.md
lavalink/examples/basic-lavalink-bot/src/main.rs
lavalink/src/lib.rs
standby/README.md
standby/src/lib.rs

Instead of taking `&mut self` in `Shard::start`, take `&self`. Mutability is not required here.

Make `Shard::start` take ref instead of mut

---

http/src/client/mod.rs
http/src/request/base.rs
http/src/request/channel/webhook/delete_webhook_message.rs
http/src/request/channel/webhook/execute_webhook.rs
http/src/request/channel/webhook/get_webhook.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/request/channel/webhook/update_webhook_with_token.rs

When using a request related to webhooks don't send the client's authorization token if a webhook token is provided. This will ensure that these requests don't count against the authorization token's ratelimits.
This has been manually tested and the resultant headers for a webhook execution are:
```json
Some({
"content-length": "18",
"content-type": "application/json",
"user-agent": "DiscordBot (https://twilight.rs/chapter_1_crates/section_2_http.html, 0.4.1) Twilight-rs"
})
```
Closes #752.

enhancement(http): skip auth token on webhooks

---

http/src/client/mod.rs
http/src/request/channel/invite/create_invite.rs
http/src/request/channel/invite/delete_invite.rs
http/src/request/channel/invite/get_channel_invites.rs
http/src/request/channel/invite/get_invite.rs
http/src/request/guild/get_guild_invites.rs
http/src/routing.rs
model/src/gateway/payload/invite_create.rs
model/src/invite/mod.rs
model/src/invite/target_type.rs

This PR brings invite functionality up to date with the current api.
Adds:
* `http` `GetInvite::with_expiration`
* `http` `CreateInvite::target_application_id`
Deprecates:
* `http` `CreateInvite::target_user_type` in favor of `CreateInvite::target_type`
* `model` `TargetUserType` in favor of `TargetType`
Other invite-related documentation has been updated.
Note: The signature of `target_user_type` is technically changed due to the model changes.
https://github.com/discord/discord-api-docs/commit/1b4e363e324eb1f49a47e32cb0108fbe276c8e0e
https://github.com/discord/discord-api-docs/commit/6dc1b2a3e7aad5145420f965e3ec15f3b7ed7074
https://github.com/discord/discord-api-docs/commit/2c9f17887a8e5c95d48b93901f4543beda4c09be

fix(http, model): bring invites up to date

---

http/src/request/guild/create_guild/mod.rs
http/src/request/guild/update_guild.rs

Adds:
* `http` `CreateGuild::afk_channel_id`
* `http` `CreateGuild::afk_timeout`
* `http` `CreateGuild::system_chanel_id`
* `http` `CreateGuild::system_chanel_flags`
* `http` `UpdateGuild::discovery_splash`
* `http` `UpdateGuild::features`
* `http` `UpdateGuild::system_chanel_flags`
https://github.com/discord/discord-api-docs/commit/5b63daebe35a8c0e9d313186f0de5fcf30304057#

feat(http): add missing create/update guild fields

---

.github/workflows/test.yml
gateway/Cargo.toml
gateway/README.md
gateway/src/lib.rs

Rename the two zlib features - `stock-zlib` and `simd-zlib` - for consistency with other feature flags. These have been renamed to `zlib-stock` and `zlib-simd` to properly namespace the feature flags.
Closes #717.

enhancement!(gateway): rename zlib features

---

http/src/client/mod.rs
http/src/json.rs
http/src/lib.rs
http/src/request/base.rs
http/src/request/channel/message/create_message.rs
http/src/request/channel/update_channel.rs
http/src/request/channel/update_channel_permission_configured.rs
http/src/request/channel/webhook/execute_webhook.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/request/guild/get_guild_vanity_url.rs
http/src/request/guild/member/add_guild_member.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/get_member.rs
http/src/request/guild/member/search_guild_members.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/mod.rs

Avoid polluting the crate root by moving the JSON utilities to their own module. Additionally, simplify their definitions.

Move JSON utilities to own module

---

gateway/src/shard/builder.rs
model/src/gateway/presence/minimal_activity.rs
model/src/gateway/presence/mod.rs

The purpose of this struct is to make it a little easier to construct
the requisite Activity struct in `ClusterBuilder` and `ShardBuilder`'s
`presence` functions.
Still, another approach could be taken, which would be to make a builder
for `UpdateStatusInfo`. This approach, however, is opinionated; to avoid
writing too many extranenous methods, the bulder would only support one
`Activity`, which is usually enough for a bot user. If this method is
preferred, I'll repurpose this PR for it.
Fixes #756.

feat(model): add `MinimalActivity`

---

model/src/channel/webhook_type.rs

The first of many small model fixes that I'll spot eventually.
Docs: https://discord.com/developers/docs/resources/webhook#webhook-object-webhook-types

feat(model): add webhook type: application

---

http/src/client/mod.rs
http/src/error.rs
http/src/lib.rs
http/src/request/base.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/request/mod.rs

Deprecate the `error::Result` type alias, as it's unnecessary and importing `error::Error` is not much more work. This will make documentation easier to read if it uses `std::result::Result`.

Deprecate HTTP Result type

---

mention/src/fmt.rs

Refactors Mention to use a blanket implementation across all borrowed types that implement it.

refactor: smoother impl of Mention on borrowed types

---

http/src/error.rs

Remove the `Formatting` and `Ratelimiting` HTTP error variants as they are never used.

Remove unused HTTP error variants

---

cache/in-memory/src/lib.rs
cache/in-memory/src/model/emoji.rs
cache/in-memory/src/model/member.rs
cache/in-memory/src/updates.rs

Remove `Arc`s from the cached versions of models. This results in:
- `CachedEmoji::user` being:
- renamed to `user_id`; and
- being changed from an `Option<Arc<User>>` to an `Option<UserId>`.
- `CachedMember::user` being:
- renamed to `user_id`; and
- changed from an `Arc<User>` to being a `UserId`.
Closes #868.

Remove Arcs from cache models

---

http/src/client/mod.rs
http/src/request/guild/mod.rs
http/src/request/guild/update_guild_channel_positions.rs

This PR changes the signature of `Client::update_guild_channel_positions` from `impl Iterator<Item = (ChannelId, u64)>` to `impl Iterator<Item = impl Into<Position>>`. It adds more fields to the `update_guild_channel_positions::Position` struct, and makes it public.  It also adds a `From<(ChannelId, u64)>` implementation for `Position`, allowing the previous signature to function.
Fixes #846.

New fields for `update_guild_channel_positions`

---

http/src/api_error.rs

Adds support for the new JSON error code 20031, for when you put banned words in a public stage name.
Fixes #879

enhancement(http): Implement JSON error code 20031

---

model/src/application/interaction/application_command/data/resolved.rs

The `InteractionMember` struct mistakenly contained a `GuildId` field,
which is not documented anywhere in the API.
Fixes #892.

Resolved member has no guild id

---

cache/in-memory/src/lib.rs
cache/in-memory/src/model/guild.rs
cache/in-memory/src/updates.rs
model/src/guild/mod.rs
model/src/guild/partial_guild.rs

BREAKING CHANGE: This PR removes the `nsfw` field on guild models, which
has been replaced by Discord with `NSFWLevel`.
Related to #839 and #848.

Remove deprecated nsfw field

---

gateway/src/shard/builder.rs
gateway/tests/test_shard_command_ratelimit.rs
model/src/gateway/payload/update_status.rs

This PR removes the `Some` from `UpdateStatusInfo`, as the list is now
required. It also validates that at least one activity is present when
using the `new` method.
Fixes #858.

Activities is required when updating presence

---

http/src/client/mod.rs
http/src/request/channel/stage/update_stage_instance.rs

BREAKING CHANGE: `UpdateStageInstance` requests like this: 
```rust
client.update_stage_instance(ChannelId(1), "topic")?.await?;
```
are now written like this: 
```rust
client.update_stage_instance(ChannelId(1))
.topic("topic")?
.await?;
```
Continued from #867.

UpdateStageInstance topic no longer required

---

model/src/oauth/current_application_info/mod.rs

` /oauth2/applications/@me` returns the CurrentApplicationInfo without `flags`, so this must be an `Option`.

fix(model): Make CurrentApplicationInfo::flags optional

---

http/Cargo.toml
http/src/client/mod.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/search_guild_members.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/mod.rs

Remove a direct dependency on the `bytes` crate by instead using `hyper`'s re-export.

Remove direct HTTP `bytes` dependency

---

http/Cargo.toml
http/README.md
http/src/client/mod.rs
http/src/lib.rs
http/src/ratelimiting/bucket.rs
http/src/ratelimiting/mod.rs

Make the `tracing` dependency optional. Users can now opt-out of it by disabling `default-features` for the crate in their dependencies section.

Make HTTP `tracing` dependency optional

---

http/Cargo.toml

Remove the unused `native-tls` dependency from the HTTP crate. This was used as workaround for a Hyper issue in PR #683 but was meant to be removed in PR #720.

Remove unused HTTP `native-tls` dependency

---

http/Cargo.toml
http/src/request/channel/webhook/execute_webhook.rs

Remove the `futures-util` dependency from the HTTP crate by replacing its use in the `ExecuteWebhook` request with a custom Future implementation.
This has been tested.

Remove HTTP `futures-util` dependency

---

http/Cargo.toml

Remove `serde_repr` as a dependency of the HTTP crate. It turns out this isn't actually used.

Remove HTTP `serde_repr` dependency

---

http/src/client/mod.rs
http/src/request/guild/member/search_guild_members.rs
http/src/request/template/create_guild_from_template.rs
http/src/request/template/create_template.rs
http/src/request/template/update_template.rs

BREAKING CHANGE: Updates four different errors to the new standard that were missed in a
review or rebase.

Update forgotten error types

---

gateway/src/cluster/builder.rs
gateway/src/shard/builder.rs
gateway/src/shard/config.rs
gateway/tests/test_shard_command_ratelimit.rs
model/src/gateway/event/gateway.rs
model/src/gateway/opcode.rs
model/src/gateway/payload/identify.rs
model/src/gateway/payload/mod.rs
model/src/gateway/payload/update_presence.rs

Renames `UpdateStatus` to `UpdatePresence`, and all similar names, with
the exception of `UpdateStatusInfo` -> `UpdatePresenceData`.
Fixes #859.

Rename `UpdateStatus` to `UpdatePresence`

---

http/src/client/mod.rs
http/src/request/application/mod.rs
http/src/request/application/set_command_permissions.rs
http/src/request/application/update_command_permissions.rs
http/src/request/validate.rs

Adds validation for the amount of overwrites a command can have. For
`set_command_permissions`, since multiple commands' permissions can be
set at once, the per-command count is first accumulated and then
validated.
Fixes #856.

Slash Commands: validate permission overwrite count

---

CONTRIBUTING.md

Adds an example `Error` implementation and updates code and commit conventions to what we've been using recently.

project: bring CONTRIBUTING.md up to current conventions

---

http/src/request/channel/reaction/delete_all_reaction.rs
http/src/routing.rs

The `Route::DeleteMessageSpecficReaction` variant is a typo and should be `Route::DeleteMessageSpecificReaction`. Note the typo "specfic".

Fix HTTP route variant name typo

---

cache/in-memory/src/updates.rs

Fortunately, the published code doesn't technically need to pass clippy, so we can put this in the next release.

Fix clippy error in tests

---

embed-builder/src/builder.rs
http/src/ratelimiting/bucket.rs
http/src/routing.rs

These might not pass MSRV, which in that case I'll just ignore them for
now.

Fix 1.53 Clippy lints

---

http/src/request/channel/stage/create_stage_instance.rs
http/src/routing.rs

Removes paramaters from `Route::CreateStageInstance` that were unused.
Actually sends the request data to Discord.
Fixes #935.

Make `CreateStageInstance` work

---

util/src/snowflake.rs

Implement the `twilight_util::snowflake::Snowflake` trait for the following new IDs:
- `twilight_model::id::ApplicationId`
- `twilight_model::id::CommandId`
- `twilight_model::id::IntegrationId`
- `twilight_model::id::StageId`

Implement Snowflake trait for new ID types

---

gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/shard/impl.rs
http/src/client/mod.rs
http/src/request/channel/get_channel.rs
http/src/request/channel/invite/create_invite.rs
http/src/request/channel/invite/get_invite.rs
http/src/request/channel/message/create_message.rs
http/src/request/channel/message/get_channel_messages.rs
http/src/request/channel/message/update_message.rs
http/src/request/channel/reaction/create_reaction.rs
http/src/request/channel/update_channel_permission.rs
http/src/request/get_gateway.rs
http/src/request/guild/ban/create_ban.rs
http/src/request/guild/ban/delete_ban.rs
http/src/request/guild/ban/get_bans.rs
http/src/request/guild/emoji/get_emoji.rs
http/src/request/guild/emoji/get_emojis.rs
http/src/request/guild/member/add_role_to_member.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/search_guild_members.rs
http/src/request/user/get_current_user_guilds.rs

Remove unnecessary bounds in doc tests in the gateway and HTTP crates, namely changing doc test function return types from `Result<(), Box<dyn std::error::Error + Send + Sync>>` to `Result<(), Box<dyn std::error::Error>>`.

Remove unnecessary doc test bounds

---

gateway/src/cluster/builder.rs
gateway/src/cluster/impl.rs

Adds a missing `Send` bound on cluster return types.
This was forgotten in #939.

Add missing `Send` bound on `Cluster` methods

---

cache/in-memory/src/event/channel.rs
cache/in-memory/src/event/emoji.rs
cache/in-memory/src/event/guild.rs
cache/in-memory/src/event/member.rs
cache/in-memory/src/event/message.rs
cache/in-memory/src/event/mod.rs
cache/in-memory/src/event/presence.rs
cache/in-memory/src/event/role.rs
cache/in-memory/src/event/stage_instance.rs
cache/in-memory/src/event/voice_state.rs
cache/in-memory/src/lib.rs

Moves the accessor methods back to the root level `impl` block, which
makes rustdoc only show one impl block for consistency.
Also adds `#[doc(hidden)]` and `#[deprecated]` on `user_ref` as this was
included by mistake in a previous PR.
Part of #937.

Move accessor methods back to root `impl` block

---

gateway/Cargo.toml
gateway/README.md
gateway/src/lib.rs
gateway/src/shard/emitter.rs
gateway/src/shard/impl.rs
gateway/src/shard/json.rs
gateway/src/shard/processor/compression/inflater.rs
gateway/src/shard/processor/compression/mod.rs
gateway/src/shard/processor/heartbeat.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/processor/socket_forwarder.rs

Make the `tracing` dependency optional. Users can now opt-out of it by disabling `default-features` for the crate in their dependencies section.

Make Gateway `tracing` dependency optional

---

standby/Cargo.toml
standby/README.md
standby/src/lib.rs

Make the `tracing` dependency optional. Users can now opt-out of it by disabling `default-features` for the crate in their dependencies section.

Make Standby `tracing` dependency optional

---

cache/in-memory/Cargo.toml

Remove `tracing` from the cache as a dependency due to no longer being used. Additionally due to #871 we no longer need to enable `serde`'s `rc` feature.

Remove tracing, serde `rc` feature from cache

---

gateway/src/shard/impl.rs

When a session is inactive the shard's ratelimiter will still be ticked, even though an inactive session can't successfully send a message. Instead, only tick the ratelimiter on a successful send.
Closes #633.

Only tick shard ratelimiter on successful sends

---

CONTRIBUTING.md
embed-builder/src/builder.rs
gateway/src/cluster/impl.rs
gateway/src/cluster/scheme.rs
gateway/src/shard/builder.rs
gateway/src/shard/emitter.rs
gateway/src/shard/impl.rs
gateway/src/shard/processor/impl.rs
gateway/src/shard/stage.rs
http/src/api_error.rs
http/src/error.rs
http/src/ratelimiting/error.rs
http/src/request/application/update_followup_message.rs
http/src/request/application/update_original_response.rs
http/src/request/audit_reason.rs
http/src/request/channel/stage/update_stage_instance.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/request/guild/create_guild/builder.rs
http/src/request/validate.rs
lavalink/src/node.rs
mention/benches/fmt.rs
mention/src/parse/error.rs
model/src/application/interaction/interaction_type.rs
model/src/channel/message/sticker/kind.rs
model/src/channel/mod.rs
model/src/gateway/close_code.rs
model/src/gateway/event/mod.rs
model/src/gateway/payload/request_guild_members.rs
model/src/voice/close_code.rs

Instead of using the `write!` and `format_args!` macros use `Display` and `Formatter` method calls. The motivation for doing this is shown in PR #942.
This does not include the work required to replace `write!` calls in `http/src/routing.rs`; this work will be done in a separate PR. Additionally one call is left in `http/src/request/channel/reaction/mod.rs` and will be resolved in another PR extracted from further work on #923.
Relates to #943.

Use Formatter calls over `write!`

---

model/src/guild/audit_log/event.rs

Rename the `AuditLogEntry` variant `GuildCreate` to `GuildUpdate` due to `GuildUpdate` being the correct name.
Docs: <https://github.com/discord/discord-api-docs/blob/101c24dc80460e2e168ffd66551ea22eab72e796/docs/resources/Audit_Log.md#audit-log-events>
Closes #616.

Rename audit log event variant `GuildCreate` to `GuildUpdate`

---

http/src/request/application/update_followup_message.rs
http/src/request/application/update_original_response.rs
http/src/request/channel/message/update_message.rs
http/src/request/channel/update_channel.rs
http/src/request/channel/webhook/update_webhook.rs
http/src/request/channel/webhook/update_webhook_message.rs
http/src/request/channel/webhook/update_webhook_with_token.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/guild/role/update_role.rs
http/src/request/guild/update_guild.rs
http/src/request/guild/update_guild_widget.rs
http/src/request/guild/user/update_current_user_voice_state.rs
http/src/request/mod.rs
http/src/request/user/update_current_user.rs

Instead of setting fields in request field structs as `Option<Option<T>>`s - causing us to need to ignore clippy lints - set `Option<NullableField<T>>`s instead. This `NullableField` represents two states: having a value and not having a value. This is very similar to `Option` except that it's explicit that the state of having no value is clearly represented as serializing to `null` while the state of having a value serializes to that value.
Closes #865.

Use `NullableField` enum for `Option<Option<T>>` representations

---

http/src/request/guild/update_guild_welcome_screen.rs
http/src/request/guild/user/update_current_user_voice_state.rs

Fix an instance of a non-idiomatic usage of `self` by replacing usage from `Self::_foo(self, arg)` with `self._foo(arg)`.

Fix non-idiomatic usage of self in HTTP crate

---

cache/in-memory/src/event/role.rs

Fixes an issue where new roles were cached, but not added to the guild roles map.

Properly insert new roles on RoleCreate

---

cache/in-memory/src/event/reaction.rs
model/src/gateway/payload/reaction_remove_emoji.rs

Turns out, we store a `ReactionType` in the cache, so this change actually
simplifies the cache code.
This has been tested with both `Unicode` and `Custom` `ReactionType`s.
Fixes #850.

Make `ReactionRemoveEmoji::emoji` a `ReactionType`

---

gateway/src/shard/processor/impl.rs

We emit `Event::ShardDisconnected` events when the remote sends a close message, but we don't emit the event when *we're* the ones to close the connection, such as due to a fatal error or between a session invalidation. This fixes that by having the processor emit an event in those situations.
Closes #761.

Emit disconnects on shard self close

---

http/src/request/channel/reaction/create_reaction.rs
http/src/request/channel/reaction/delete_all_reaction.rs
http/src/request/channel/reaction/delete_reaction.rs
http/src/request/channel/reaction/get_reactions.rs
http/src/request/channel/reaction/mod.rs

Add a `Display` formatter for `request::channel::reaction::RequestReactionType`. The new method, `RequestReactionType::display`, returns `RequestReactionTypeDisplay` which in turn implements `std::fmt::Display` to format the reaction into a format acceptable for URLs.
This replaces the private `format_emoji` function which allocates a String. With how the Display formatter is used a string still needs to be allocated, but this will enable an optimization in the future.

Add HTTP reaction display formatter

---

standby/src/lib.rs

This crate was actually already fully documented.
Part of #542.

Standby: Promote `missing_docs` to `deny`

---

http/src/client/mod.rs
http/src/json.rs
http/src/request/channel/webhook/execute_webhook.rs
http/src/request/guild/get_guild_vanity_url.rs
http/src/request/guild/member/add_guild_member.rs
http/src/request/guild/member/get_guild_members.rs
http/src/request/guild/member/get_member.rs
http/src/request/guild/member/search_guild_members.rs
http/src/request/guild/member/update_guild_member.rs
http/src/request/mod.rs

Since `simd_json::from_slice` requires a mutable reference, deserializing always required to copy the response bytes into a `Vec` and then deserialize through a mutable reference to that `Vec`, even if the `simd_json` feature wasn't enabled.
If the feature is not enabled, this PR deserializes through an immutable reference instead of allocating beforehand.
This should clear up a lot of unecessary allocations.
Minor side effect: If the deserialization previously failed, the twilight error would include the bytes. However, since the bytes were potentially mutated while deserializing with simd, the bytes in the error might not have been the actual response bytes. In this PR, it is guaranteed that the error contains the actual response bytes.
I've tested the non-simd version, even if somewhat …

feat(http): Don't allocate without simd feature

---

gateway/src/shard/processor/impl.rs
http/src/ratelimiting/headers.rs

Fixes a lint appearing in our docs CI.

chore(gateway,http): fix `disjoint_capture_migration` lint

---

http/src/routing/route_display.rs

Correctly format the `SetGuildCommands` and `UpdateGlobalCommand` routes, which formatted the string "application" instead of "applications".
These were typos as a result of #962. Tests have been added for these routes.

Correctly format some HTTP application routes

---

http/src/api_error.rs

Add 6 new HTTP API error codes:
- 10059: Unknown discoverable server category
- 10060: Unknown sticker
- 10068: Unknown Guild Member Verification Form
- 10069: Unknown Guild Welcome Screen
- 30030: Maximum number of server categories has been reached
- 30039: Maximum number of stickers reached
Tests have been added.
Closes #1002.

Add 6 new HTTP API error codes

---

util/README.md
util/src/lib.rs

Document the `link` feature by noting that it provides implementations for parsing and formatting entity URLs such as webhook URLs.
Closes #1004.

Document the util `link` feature

---

http/src/client/mod.rs
http/src/request/application/get_original_response.rs
http/src/request/application/mod.rs
http/src/routing/route.rs
http/src/routing/route_display.rs

I've been doing some work on a personal bot that makes use of slash commands and I had no way to get the original interaction response message id. This PR adds a http client function to fetch it. Just like `DeleteOriginalResponse` but instead it requests data and returns it as a `Message`.

feat(http): add http route to get an original interaction response message

---

cache/in-memory/src/event/guild.rs
model/src/channel/mod.rs
model/src/channel/thread/auto_archive_duration.rs
model/src/channel/thread/member.rs
model/src/channel/thread/metadata.rs
model/src/channel/thread/mod.rs
model/src/channel/thread/news.rs
model/src/channel/thread/private.rs
model/src/channel/thread/public.rs
model/src/gateway/payload/thread_list_sync.rs
model/src/gateway/payload/thread_member_update.rs
model/src/gateway/payload/thread_members_update.rs

I felt that threads were causing too much noise in the channel module, so I moved them to a module below channel. I also reorganized the imports in each file.

refactor!(model): reorganize threads into own module

---

http/src/client/mod.rs
http/src/request/channel/update_channel.rs
http/src/request/guild/create_guild/builder.rs
http/src/request/guild/create_guild_channel.rs
http/src/request/guild/update_guild.rs
http/src/request/user/update_current_user.rs

The new minimum channel name length is 1 UTF-16 character.
Relates to #855 which updated the validation function to a minimum of 1 but did not update documentation and other places.
Closes #1007.
**PR note**: I believe I didn't miss anything but it's hard to tell. As an aside, maybe we should expose `validate` and constants describing the minimums and maximums of validations. We appear to have duplicated some of the checks through other exposed constants.

Update minimum channel name length to 1 in all places

---

embed-builder/src/builder.rs
http/src/request/validate.rs

Update the embed description length limit in the EmbedBuilder and in `request::validate` from 2048 to 4096.
Closes #991.

Update embed description limit to 4096

---

http/src/request/application/update_original_response.rs

`UpdateOriginalResponse` currently returns `()` on invoking. This behavior is incorrect according to https://discord.com/developers/docs/interactions/slash-commands#edit-original-interaction-response, which returns a `Message` object on success. This PR fixes this return type.
This same thing is also present in https://github.com/twilight-rs/twilight/blob/main/http/src/request/channel/webhook/update_webhook_message.rs. But I don't think this comes under the scope of this PR.
I have tested this (just once).

Fix return type of `UpdateOriginalResponse`

---

gateway/src/cluster/builder.rs
gateway/src/cluster/event.rs
gateway/src/cluster/impl.rs
gateway/src/cluster/mod.rs
gateway/src/shard/event.rs

Add a concrete `cluster::Events` type wrapping a `SelectAll` of the shards' events. Like the previous cluster events stream the `Events` type is `Send` and `Sync` and returns `Stream` items with a type of `(u64, Event)`.
This is useful for being able to name the return type.

Add concrete cluster events type

---

http/src/client/mod.rs
http/src/request/audit_reason.rs
http/src/request/channel/mod.rs
http/src/request/channel/thread/add_thread_member.rs
http/src/request/channel/thread/create_thread.rs
http/src/request/channel/thread/create_thread_from_message.rs
http/src/request/channel/thread/get_active_threads.rs
http/src/request/channel/thread/get_joined_private_archived_threads.rs
http/src/request/channel/thread/get_private_archived_threads.rs
http/src/request/channel/thread/get_public_archived_threads.rs
http/src/request/channel/thread/get_thread_members.rs
http/src/request/channel/thread/join_thread.rs
http/src/request/channel/thread/leave_thread.rs
http/src/request/channel/thread/mod.rs
http/src/request/channel/thread/remove_thread_member.rs
http/src/request/channel/thread/update_thread.rs
http/src/request/validate.rs
http/src/routing/path.rs
http/src/routing/route.rs
http/src/routing/route_display.rs
model/src/channel/thread/listing.rs
model/src/channel/thread/mod.rs

Adds the current thread methods to the client. This has been tested.
Fixes #973.
Blocks on #1015.

feat(http): thread methods

---

cache/in-memory/src/event/guild.rs
model/src/channel/mod.rs
model/src/channel/thread/metadata.rs
model/src/channel/thread/news.rs
model/src/channel/thread/private.rs
model/src/channel/thread/public.rs

Remove the `channel::thread::ThreadMetadata::archiver_id` field, which is no longer available per the API docs: <https://github.com/discord/discord-api-docs/commit/82c98ba5699b69706cfb493a7c6e08b67ae1a8f3>
Closes #974.

Remove thread metadata `archiver_id` field

---

model/src/guild/permissions.rs

Add the `USE_PRIVATE_THREADS` and `USE_PUBLIC_THREADS` variants to the `guild::Permissions` bitflags.
Closes #1017.

feat(model/threads): use threads permissions

---

cache/in-memory/Cargo.toml
cache/in-memory/src/lib.rs
cache/in-memory/src/permission.rs
model/src/channel/mod.rs

Add an integration for the in-memory cache that uses the `util` crate's permission calculator. This feature is gated behind the optional, non-default "permission-calculator" feature. This interface is exposed via the `twilight_cache_inmemory::permissions` module. This module contains a struct called `InMemoryCachePermissions`, which contains two methods of note: `in_channel` to calculate the permissions of a member in a channel and `root` to calculate the permissions of a member on a guild level. Both of these operations can fail, so error types are included in this module.
`InMemoryCache::permissions` is a new method on the cache that will return an instance of `InMemoryCachePermissions`.
Example to get the permissions of a user in a guild:
```rust
use …
```

Cache permission calculator integration

---

cache/in-memory/src/event/message.rs
cache/in-memory/src/model/message.rs
cache/in-memory/src/test.rs
model/src/channel/message/mod.rs
model/src/channel/message/sticker/message.rs
model/src/channel/message/sticker/mod.rs
standby/src/lib.rs

Adds the `available`, `guild_id`, `sort_value`, and `user` fields to
`Sticker`. Adds the `MessageSticker` struct. Replaces `stickers` with
`sticker_items` in message instantiations.
Fixes #940.

feat(model): bring stickers up to date

---

http/src/routing/route_display.rs

A typo in #962 changed "applications" to "application" for `CreateGuildCommand`, `GetGuildCommands`, `SetGuildCommands`, `DeleteGlobalCommand` & `UpdateGlobalCommand`. This PR fixes this.

Fix typo, application => applications

---

gateway/src/cluster/builder.rs
gateway/src/cluster/config.rs
gateway/src/shard/builder.rs
gateway/src/shard/config.rs

The nested inner `Box` is not needed at all since `Arc` can hold `dyn Trait` objects by itself.

Reduce allocations for gateway queue

---

.codespellrc
.github/workflows/lint.yml
CONTRIBUTING.md
cache/in-memory/src/event/voice_state.rs
gateway/examples/metrics/src/main.rs
gateway/src/cluster/scheme.rs
http/src/client/mod.rs
http/src/request/application/create_global_command.rs
http/src/request/application/create_guild_command.rs
http/src/request/channel/message/delete_messages.rs
http/src/request/guild/create_guild/builder.rs
http/src/request/template/update_template.rs
http/src/request/user/update_current_user.rs
lavalink/src/client.rs
lavalink/src/http.rs
lavalink/src/node.rs
model/src/application/interaction/mod.rs
model/src/channel/reaction_type.rs
model/src/gateway/payload/update_presence.rs

This uses [codespell](https://github.com/codespell-project/codespell) to verify the docs won't have spelling mistakes. While I was on it, all errors that it found were fixed. The action used is the official [codespell action](https://github.com/codespell-project/actions-codespell) that features line annotations for issues found.

Add CI for spell checking and fix spelling mistakes

---

http/src/request/application/create_followup_message.rs
http/src/request/application/update_followup_message.rs
http/src/request/application/update_original_response.rs
http/src/request/channel/message/create_message.rs
http/src/request/channel/message/update_message.rs
http/src/request/channel/webhook/execute_webhook.rs
http/src/request/channel/webhook/update_webhook_message.rs

Deprecate the `attachment`, `embed`, and `file` message setters in favor of their plural forms of `attachments`, `embeds`, and `files`, respectively. This is due to #1009 removing the possibility for these methods.

Deprecate singlular message setters

---

model/src/application/component/mod.rs
model/src/application/component/select_menu.rs

The PR adds the `disabled` field to `SelectMenu`. The field is self-explanatory. The field can be seen at https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure

Add `disabled` field to `SelectMenu`

---

cache/in-memory/src/lib.rs
command-parser/src/lib.rs
gateway/queue/src/lib.rs
gateway/src/lib.rs
gateway/src/shard/emitter.rs
gateway/src/shard/json.rs
gateway/src/shard/processor/compression/mod.rs
gateway/src/shard/processor/impl.rs
http/src/lib.rs
lavalink/src/lib.rs
model/src/lib.rs
standby/src/lib.rs

Remove unsafe code in the `gateway` crate. Its use of `unsafe` was to accommodate `simd-json`, but can be removed by instead continuously working with the mutable buffer rather than going from bytes -> str -> bytes again.
This also adds `#![deny(unsafe_code)]` to all crates that weren't already marked with it.

Remove unsafe code in gateway

---

.github/workflows/doc.yml
.github/workflows/publish.yml

This fixes the permission module not appearing for the `cache-inmemory` docs and any future feature flags getting added to crates that are not `twilight-util`.

Build docs with all features enabled

---

gateway/src/event.rs

This adds associated functions to `EventTypeFlags` that return the `EventTypeFlags` for a given `Intent`. ~~This can not be const nor an associated const until [bitflags/bitflags/#217][bitflags-pr] lands.~~
[bitflags-pr]: https://github.com/bitflags/bitflags/pull/217

Add `EventTypeFlags` categories for `Intents`

---

model/src/application/interaction/message_component/mod.rs

The PR adds a possibly necessary function to `MessageComponent,` i.e., a function to extract the user's id who triggered the interaction. However, as can be seen in the code, it can be painful to extract the user id.
PS: Need some help on the function docs

Add author_id function to MessageComponent

---

http/src/request/user/get_current_user_guilds.rs
http/src/request/validate.rs

The limit for the Get current user guilds request has been increased to 200 (https://github.com/discord/discord-api-docs/commit/daa13f60634396296092da02bb8acd8f3360e03b). This PR reflects this change on the Twilight API.

Update get_current_user_guilds limit to 200

---

model/src/gateway/payload/invite_create.rs
model/src/gateway/payload/mod.rs

`twilight_model::gateway::payload::InviteCreate` has a `target_user` field with a `PartialUser` type unique to the payload, but the type isn't exposed to the API. The `gateway::payload::invite_create` module is private and contains `InviteCreate` and `PartialUser`, but `gateway::payload` only exports `InviteCreate`. Instead we can make the module public.
This commit also makes `PartialUser`'s fields public and documents and
tests the module.

Expose Invite Create payload's user

---

gateway/src/shard/impl.rs

When calling `Shard::shutdown`, `Shard::shutdown_resumable`, `Cluster::down`, or `Cluster::down_resumable`, shards would be stopped but the events stream returned by shards and clusters wouldn't return `None`. This is due to the events stream containing a receiver of events, while shard processors contained a sender. However, shards would keep a copy of the sender, so while the shard processor would be aborted and its sender dropped the shard's would not be dropped.
To fix this we can move the sender into shard processors. When the shard processor is dropped so will the only sender. However, individual shard instances will now only be able to be started the first time; `Shard::start` can no longer be called multiple times. If a user shuts down a shard and wants to start it again they will …

Fix gateway event streams never ending

---

model/src/gateway/payload/ready.rs
model/src/oauth/partial_application.rs
standby/src/lib.rs

This shows up in the ready payload in the example on the site:
```
Event: Ready(Ready { application: PartialApplication { flags: DISCORD_CERTIFIED_MODERATOR, id: ApplicationId(....) }, guilds: [], session_id: "....", shard: Some([0, 1]), user: CurrentUser { avatar: ...., bot: true, discriminator: "....", email: None, flags: Some((empty)), id: UserId(....), locale: None, mfa_enabled: true, name: "....", premium_type: None, public_flags: None, verified: Some(true) }, version: 8 })
```
Evidently bots can't be certified moderators.

Applications should use application flags

---

gateway/src/cluster/builder.rs
gateway/src/cluster/config.rs
gateway/src/cluster/impl.rs

This PR removes some fields on `Cluster`'s Config that are included in all `Shard`s of the cluster. This saves some memory too since the cluster no longer contains a separate `HttpClient`.
`Cluster::config` could return a `(ClusterConfig, ShardConfig`) tuple or it could be left as is.

Revamp `Cluster`'s config

---

gateway/Cargo.toml
gateway/src/shard/impl.rs

This exists in Tokio since 1.5 and makes it possible to eliminate a direct dependency on `once_cell`, but most use cases should still result in this being depended on indirectly through openssl and ring.

gateway: Use tokio's OnceCell
